---
permalink: api-automation/concept_rest_services_offered_in_unified_manager_apis.html 
sidebar: sidebar 
keywords: rest, services, offer, active iq, unified, manager 
summary: 在開始使用Active IQ Unified Manager API 之前，您應該先了解所提供的 REST 服務和操作。 
---
= Active IQ Unified Manager中提供的 REST 服務
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
在開始使用Active IQ Unified Manager API 之前，您應該先了解所提供的 REST 服務和操作。

用於設定 API 伺服器的設定和管理 API 支援讀取（GET）或寫入（POST、PATCH、DELETE）操作。以下是 API 支援的 GET、PATCH、POST 和 DELETE 作業的一些範例：

* GET 範例： `GET /datacenter/cluster/clusters`檢索資料中心中的群集詳細資訊。傳回的最大記錄數 `GET`操作為 1000。
+
[NOTE]
====
API 可讓您根據支援的屬性對記錄進行過濾、排序和排列。

====
* POST 範例： `POST /datacenter/svm/svms`建立自訂儲存虛擬機器 (SVM)。
* PATCH 範例： `PATCH /datacenter/svm/svms/{key}`使用其唯一鍵修改 SVM 的屬性。
* 刪除範例： `DELETE /storage-provider/access-endpoints/{key}`使用其唯一金鑰從 LUN、SVM 或檔案共用中刪除存取端點。


可以使用 API 執行的 REST 操作取決於操作員、儲存管理員或應用程式管理員使用者的角色。

[cols="2*"]
|===
| 使用者角色 | 支援的 REST 方法 


 a| 
操作員
 a| 
對資料的唯讀存取。具有此角色的使用者可以執行所有 GET 請求。



 a| 
儲存管理員
 a| 
讀取所有資料的權限。具有此角色的使用者可以執行所有 GET 請求。

此外，他們還具有寫入存取權（執行 PATCH、POST 和 DELETE 請求）來執行特定活動，例如管理、儲存服務物件和儲存管理選項。



 a| 
應用程式管理員
 a| 
對所有資料的讀寫存取。具有此角色的使用者可以對所有功能執行 GET、PATCH、POST 和 DELETE 請求。

|===
有關所有 REST 操作的更多信息，請參閱_線上 API 文件_。
