---
permalink: api-automation/concept_gateway_apis.html 
sidebar: sidebar 
keywords: access, ONTAP, APIs, proxy, access 
summary: 網關 API 為您提供了使用Active IQ Unified Manager憑證執行ONTAP REST API 和管理儲存物件的優勢。當從 Unified Manager Web UI 啟用 API 閘道功能時，這些 API 可用。 
---
= 透過代理存取存取ONTAP API
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
網關 API 為您提供了使用Active IQ Unified Manager憑證執行ONTAP REST API 和管理儲存物件的優勢。當從 Unified Manager Web UI 啟用 API 閘道功能時，這些 API 可用。

Unified Manager REST API 僅支援在 Unified Manager 資料來源（即ONTAP叢集）上執行一組選定的操作。您可以透過ONTAP API 使用其他功能。網關 API 允許 Unified Manager 成為一個直通接口，用於傳輸在其管理的ONTAP叢集上執行的所有 API 請求，而無需單獨登入每個資料中心叢集。它作為單一管理點，在由 Unified Manager 實例管理的ONTAP叢集中執行 API。 API 閘道功能可讓 Unified Manager 成為單一控制平面，您可以從中管理多個ONTAP集群，而無需單獨登入它們。網關 API 可讓您保持登入 Unified Manager 並透過執行ONTAP REST API 操作來管理ONTAP叢集。

[NOTE]
====
所有使用者都可以使用 GET 操作執行查詢。應用程式管理員可以執行所有ONTAP REST 操作。

====
網關充當代理，透過維護與ONTAP API 相同的格式的標頭和正文請求來傳輸 API 請求。您可以使用 Unified Manager 憑證並執行特定操作來存取和管理ONTAP叢集，而無需傳遞單獨的叢集憑證。它繼續管理叢集身份驗證和叢集管理，但將 API 請求重定向到直接在特定叢集上運行。  API 傳回的回應與直接從ONTAP執行的對應ONTAP REST API 傳回的回應相同。

[cols="3*"]
|===
| HTTP 動詞 | 路徑（URL） | 描述 


 a| 
`GET`
 a| 
`/gateways`
 a| 
此 GET 方法會擷取由 Unified Manager 管理的支援ONTAP REST 呼叫的所有叢集的清單。您可以驗證叢集詳細資訊並選擇根據叢集 UUID 或通用唯一識別碼 (UUID) 執行其他方法。

[NOTE]
====
網關 API 僅檢索ONTAP 9.5 或更高版本支援並透過 HTTPS 新增至 Unified Manager 的叢集。

====


 a| 
`GET`

`POST`

`DELETE`

`PATCH`

`OPTIONS`（Swagger 上不可用）

`HEAD`（Swagger 上不可用）
 a| 
`/gateways/\{uuid}/\{path}`

[NOTE]
====
\{uuid} 的值必須替換為執行 REST 操作的叢集 UUID。此外，請確保 UUID 屬於ONTAP 9.5 或更高版本支援的集群，並透過 HTTPS 新增至 Unified Manager。 \{path} 必須替換為ONTAP REST URL。您必須刪除 `/api/`來自 URL。

==== a| 
這是一個單點代理 API，支援所有ONTAP REST API 的 POST、DELETE、PATCH 操作和 GET。只要受ONTAP支持，任何 API 均不受任何限制。隧道或代理功能無法被停用。

這 `OPTIONS`方法傳回ONTAP REST API 支援的所有操作。例如，如果ONTAP API 僅支援 `GET`操作，運行 `OPTIONS`使用此網關 API 傳回的方法 `GET`作為回應。  Swagger 上不支援此方法，但可以在其他 API 工具上執行。

這 `OPTIONS`方法確定資源是否可用。此操作可用於查看 HTTP 回應頭中有關資源的元資料。  Swagger 上不支援此方法，但可以在其他 API 工具上執行。

|===


== 了解 API 網關隧道

網關 API 可讓您透過 Unified Manager 管理ONTAP物件。 Unified Manager 管理叢集和身份驗證詳細信息，並將請求重新導向到ONTAP REST 端點。網關 API 將標頭和回應主體中的 URL 和超媒體轉換為應用程式狀態引擎 (HATEOAS) 連結以及 API 閘道基本 URL。網關 API 可作為代理基本 URL，您可以將ONTAP REST URL 附加到該 URL 並執行所需的ONTAP REST 端點。


NOTE: 為了使ONTAP API 能夠透過 API 閘道成功運行，該 API 必須得到其所運行的ONTAP叢集版本的支援。執行ONTAP叢集上不支援的 API 不會傳回任何結果。

在此範例中，網關 API（代理基本 URL）為： `+/gateways/{uuid}/+`

採用的ONTAP API 是： `/storage/volumes` 。您需要新增ONTAP API REST URL 作為路徑參數的值。

[NOTE]
====
新增路徑時，請確保已刪除“`/`" symbol at the beginning of the URL. For the API `/storage/volumes,`添加 `storage/volumes.`

====
附加的 URL 是： `+/gateways/{uuid}/storage/volumes+`

在運行 `GET`操作，產生的URL如下： `GEThttps://<hostname\>/api/gateways/<cluster_UUID\>/storage/volumes`

這 `/api`附加 URL 中的ONTAP REST URL 標籤被刪除，而網關 API 的標籤被保留。

*範例 cURL 指令*

[listing]
----
curl -X GET "https://<hostname>/api/gateways/1cd8a442-86d1-11e0-ae1c-9876567890123/storage/volumes" -H "accept: application/hal+json" -H "Authorization: Basic <Base64EncodedCredentials>"
----
API 傳回該叢集中的儲存磁碟區清單。回應格式與您從ONTAP執行相同 API 時收到的格式相同。傳回的狀態代碼是ONTAP REST 狀態代碼。



== 設定 API 範圍

所有 API 都在叢集範圍內設定了上下文。基於儲存虛擬機器操作的API也是以叢集為範圍的，即API操作是在被管理的叢集內的特定儲存虛擬機器上執行的。當你運行 `/gateways/\{uuid}/\{path}`API，請確保輸入執行該操作的叢集的叢集 UUID（Unified Manager 資料來源 UUID）。若要將上下文設定為該叢集內的特定儲存虛擬機，請輸入儲存虛擬機金鑰作為 X-Dot-SVM-UUID 參數或輸入儲存虛擬機名稱作為 X-Dot-SVM-Name 參數。此參數會作為過濾器新增至字串標頭中，並且操作在該叢集內的該儲存虛擬機器範圍內運作。

*範例 cURL 指令*

[listing]
----
curl -X GET "https://<hostname>/api/gateways/e4f33f90-f75f-11e8-9ed9-00a098e3215f/storage/volume" -H "accept: application/hal+json" -H "X-Dot-SVM-UUID: d9c33ec0-5b61-11e9-8760-00a098e3215f"
-H "Authorization: Basic <Base64EncodedCredentials>"
----
有關使用ONTAP REST API 的更多信息，請參閱https://docs.netapp.com/us-en/ontap-automation/index.html["ONTAP REST API 自動化"]
