---
permalink: api-automation/concept_manage_lun.html 
sidebar: sidebar 
keywords: manage, lun 
summary: 您可以使用 /storage-provider/luns API 來檢視、新增、修改和刪除資料中心環境中的 LUN。 
---
= 使用 API 管理 LUN
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以使用 `/storage-provider/luns`API 用於檢視、新增、修改和刪除資料中心環境中的 LUN。

在配置 LUN 之前，請確保已建立 SVM 並使用支援的協定進行設定。如果您在設定時指派效能服務等級 (PSL) 或儲存效率原則 (SEP)，則應在建立 LUN 之前建立 PSL 或 SEP。



== 查看 LUN

您可以使用下列方法檢視 Unified Manager 環境中的 LUN。當您在Active IQ Unified Manager上將ONTAP叢集新增為資料來源時，這些叢集的儲存工作負載會自動新增至您的 Unified Manager 實例中。此 API 會擷取自動和手動新增至 Unified Manager 實例的所有 LUN。您可以透過使用 LUN 鍵執行此 API 來查看特定 LUN 的詳細資訊。

[cols="3*"]
|===
| 類別 | HTTP 動詞 | 小路 


 a| 
儲存提供者
 a| 
得到
 a| 
`/storage-provider/luns`

`/storage-provider/luns/\{key}`

|===


== 添加 LUN

您可以使用以下方法將 LUN 新增至您的 SVM。

[cols="3*"]
|===
| 類別 | HTTP 動詞 | 小路 


 a| 
儲存提供者
 a| 
郵政
 a| 
`/storage-provider/luns`

|===
[NOTE]
====
在您的 cURL 請求中，如果您在輸入中為可選參數 volume_name_tag 提供了一個值，那麼在建立 LUN 期間命名磁碟區時將使用該值。此標籤可以輕鬆搜尋磁碟區。如果您在請求中提供音量鍵，則會跳過標記。

====


== 刪除 LUN

您可以使用以下方法刪除特定的LUN。您需要提供 LUN 密鑰來刪除特定的 LUN。

[NOTE]
====
如果您在ONTAP中建立了一個磁碟區，然後透過 Unified Manager 在該磁碟區上設定了 LUN，則當您使用此 API 刪除所有 LUN 時，該磁碟區也會從ONTAP叢集中刪除。

====
[cols="3*"]
|===
| 類別 | HTTP 動詞 | 小路 


 a| 
儲存提供者
 a| 
刪除
 a| 
`/storage-provider/luns/\{key}`

|===


== 修改 LUN

您可以使用以下方法修改 LUN 並更新其屬性。您需要提供 LUN 密鑰來修改特定的 LUN。您還需要輸入要更新的 LUN 屬性及其值。若要使用此 API 更新 LUN 陣列，您應該查看「使用 API 的建議」中的建議。

[NOTE]
====
每次呼叫此 API 時只能更新一個屬性。對於多次更新，您需要多次執行此 API。

====
|===


| 類別 | HTTP 動詞 | 小路 


 a| 
儲存提供者
 a| 
修補
 a| 
`/storage-provider/luns/\{key}`

|===