---
permalink: api-automation/concept_metrics_apis.html 
sidebar: sidebar 
keywords: view, performance, metrics 
summary: Active IQ Unified Manager為您提供了 /datacenter 類別下的一組 API，使您能夠查看資料中心中叢集和儲存物件的效能資料。這些 API 會擷取不同儲存物件的效能數據，例如叢集、節點、LUN、磁碟區、聚合和儲存虛擬機器。 
---
= 使用 API 查看效能指標
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Active IQ Unified Manager為您提供了一組 API `/datacenter`類別，使您能夠查看資料中心中的叢集和儲存物件的效能資料。這些 API 會擷取不同儲存物件的效能數據，例如叢集、節點、LUN、磁碟區、聚合、儲存虛擬機器、FC 介面、FC 連接埠、乙太網路連接埠和 IP 介面。

這 `/metrics`和 `/analytics`API 提供了效能指標的不同視圖，使用這些視圖，您可以深入了解資料中心中以下儲存物件的不同層級的詳細資訊：

* 叢集
* 節點
* 儲存虛擬機
* 聚合體
* 卷
* LUN
* FC 介面
* FC 連接埠
* 乙太網路埠
* IP 介面


下表對 `/metrics`和 `/analytics`與檢索到的效能資料細節有關的 API。

[cols="2*"]
|===
| 指標 | 分析 


 a| 
單一物件的效能詳細資訊。例如， `/datacenter/cluster/clusters/\{key}/metrics` API 要求輸入叢集鍵作為路徑參數來檢索該特定叢集的指標。
 a| 
資料中心內同一類型的多個物件的效能詳細資訊。例如， `/datacenter/cluster/clusters/analytics` API 檢索資料中心中所有群集的集體指標。



 a| 
根據檢索的時間間隔參數對儲存物件的效能指標進行採樣。
 a| 
某一類型儲存物件在一定時期內（72 小時以上）的效能高階聚合值。



 a| 
檢索物件的基本詳細信息，例如節點或叢集的詳細資訊。
 a| 
未檢索到具體細節。



 a| 
檢索單一物件的累積計數器，例如最小值、最大值、第 95 個百分位數和一段時間內的平均效能值，例如讀取、寫入、總計和其他計數器。
 a| 
對於同一類型的所有對象，將顯示單一聚合值。



 a| 
時間範圍和樣本資料基於以下時間表：資料的時間範圍。例如 1h、12h、1d、2d、3d、15d、1w、1m、2m、3m、6m。如果範圍超過 3 天（72 小時），您將獲得 1 小時樣本，否則您將獲得 5 分鐘樣本。每個時間範圍的周期如下：

* 1 小時：最近 5 分鐘內採樣的一小時內的指標。
* 12h：最近 12 小時內每 5 分鐘採樣一次的指標。
* 1d：最近一天 5 分鐘內採樣的指標。
* 2d：最近 2 天的 5 分鐘採樣指標。
* 3d：最近 3 天的 5 分鐘採樣指標。
* 15d：最近 15 天的 1 小時內採樣的指標。
* 1w：最近一週內 1 小時內採樣的指標。
* 1m：最近一個月內 1 小時內採樣的指標。
* 2m：最近 2 個月內 1 小時內採樣的指標。
* 3m：最近 3 個月內 1 小時內採樣的指標。
* 6m：最近 6 個月內 1 小時內採樣的指標。
+
可用值：1h、12h、1d、2d、3d、15d、1w、1m、2m、3m、6m

+
預設值：1h


 a| 
超過72小時。計算此樣本的持續時間以 ISO-8601 標準格式表示。

|===


== 指標 API 的輸出範例

例如， `/datacenter/cluster/nodes/\{key}/metrics` API 檢索節點的以下詳細資訊（以及其他資訊）：


NOTE: 摘要值中的 95 分位數表示該期間收集的 95% 樣本的計數器值小於指定的 95 分位數。

[listing]
----
{
     "iops": {
       "local": {
         "other": 100.53,
         "read": 100.53,
         "total": 100.53,
         "write": 100.53
       },
       "other": 100.53,
       "read": 100.53,
       "total": 100.53,
       "write": 100.53
     },
     "latency": {
       "other": 100.53,
       "read": 100.53,
       "total": 100.53,
       "write": 100.53
     },
     "performance_capacity": {
       "available_iops_percent": 0,
       "free_percent": 0,
       "system_workload_percent": 0,
       "used_percent": 0,
       "user_workload_percent": 0
     },
     "throughput": {
       "other": 100.53,
       "read": 100.53,
       "total": 100.53,
       "write": 100.53
     },
     "timestamp": "2018-01-01T12:00:00-04:00",
     "utilization_percent": 0
   }
 ],
 "start_time": "2018-01-01T12:00:00-04:00",
 "summary": {
   "iops": {
     "local_iops": {
       "other": {
         "95th_percentile": 28,
         "avg": 28,
         "max": 28,
         "min": 5
       },
       "read": {
         "95th_percentile": 28,
         "avg": 28,
         "max": 28,
         "min": 5
       },
       "total": {
         "95th_percentile": 28,
         "avg": 28,
         "max": 28,
         "min": 5
       },
       "write": {
         "95th_percentile": 28,
         "avg": 28,
         "max": 28,
         "min": 5
       }
     },
----


== 分析 API 的輸出範例

例如， `/datacenter/cluster/nodes/analytics` API 會擷取所有節點的下列值（以及其他值）：

[listing]
----
{     "iops": 1.7471,
     "latency": 60.0933,
     "throughput": 5548.4678,
     "utilization_percent": 4.8569,
     "period": 72,
     "performance_capacity": {
       "used_percent": 5.475,
       "available_iops_percent": 168350
     },
     "node": {
       "key": "37387241-8b57-11e9-8974-00a098e0219a:type=cluster_node,uuid=95f94e8d-8b4e-11e9-8974-00a098e0219a",
       "uuid": "95f94e8d-8b4e-11e9-8974-00a098e0219a",
       "name": "ocum-infinity-01",
       "_links": {
         "self": {
           "href": "/api/datacenter/cluster/nodes/37387241-8b57-11e9-8974-00a098e0219a:type=cluster_node,uuid=95f94e8d-8b4e-11e9-8974-00a098e0219a"
         }
       }
     },
     "cluster": {
       "key": "37387241-8b57-11e9-8974-00a098e0219a:type=cluster,uuid=37387241-8b57-11e9-8974-00a098e0219a",
       "uuid": "37387241-8b57-11e9-8974-00a098e0219a",
       "name": "ocum-infinity",
       "_links": {
         "self": {
           "href": "/api/datacenter/cluster/clusters/37387241-8b57-11e9-8974-00a098e0219a:type=cluster,uuid=37387241-8b57-11e9-8974-00a098e0219a"
         },
     "_links": {
       "self": {
         "href": "/api/datacenter/cluster/nodes/analytics"
       }
     }
   },
----


== 可用 API 列表

下表描述了 `/metrics`和 `/analytics`詳細的 API。

[NOTE]
====
這些 API 傳回的 IOPS 和效能指標都是 double 值，例如 `100.53`。不支援使用管道符 (|) 和通配符 (*) 過濾這些浮點值。

====
[cols="3*"]
|===
| HTTP 動詞 | 小路 | 描述 


 a| 
`GET`
 a| 
`/datacenter/cluster/clusters/\{key}/metrics`
 a| 
檢索由群集鍵的輸入參數指定的群集的性能資料（樣本和摘要）。傳回群集鍵和 UUID、時間範圍、IOPS、吞吐量、樣本數等資訊。



 a| 
`GET`
 a| 
`/datacenter/cluster/clusters/analytics`
 a| 
檢索資料中心內所有群集的高階效能指標。您可以根據所需條件篩選結果。傳回諸如聚合 IOPS、吞吐量和收集週期（以小時為單位）等值。



 a| 
`GET`
 a| 
`/datacenter/cluster/nodes/\{key}/metrics`
 a| 
檢索節點鍵的輸入參數指定的節點的效能資料（樣本和摘要）。傳回節點 UUID、時間範圍、IOPS 摘要、吞吐量、延遲和效能、收集的樣本數和利用率百分比等資訊。



 a| 
`GET`
 a| 
`/datacenter/cluster/nodes/analytics`
 a| 
檢索資料中心中所有節點的高階效能指標。您可以根據所需條件篩選結果。返回節點和集群鍵等資訊以及聚合 IOPS、吞吐量和收集週期（以小時為單位）等值。



 a| 
`GET`
 a| 
`/datacenter/storage/aggregates/\{key}/metrics`
 a| 
檢索聚合鍵的輸入參數指定的聚合的效能資料（樣本和摘要）。傳回的資訊包括時間範圍、IOPS 摘要、延遲、吞吐量和效能容量、每個計數器收集的樣本數以及利用率百分比。



 a| 
`GET`
 a| 
`/datacenter/storage/aggregates/analytics`
 a| 
檢索資料中心內所有聚合的高階效能指標。您可以根據所需條件篩選結果。傳回諸如聚合和群集鍵之類的資訊以及諸如聚合 IOPS、吞吐量和收集週期（以小時為單位）之類的值。



 a| 
`GET`
 a| 
`/datacenter/storage/luns/\{key}/metrics`

`/datacenter/storage/volumes/\{key}/metrics`
 a| 
檢索 LUN 或卷鍵的輸入參數指定的 LUN 或檔案共用（磁碟區）的效能資料（樣本和摘要）。傳回讀取、寫入和總 IOPS、延遲和吞吐量的最小值、最大值和平均值的摘要以及每個計數器收集的樣本數等資訊。



 a| 
`GET`
 a| 
`/datacenter/storage/luns/analytics`

`/datacenter/storage/volumes/analytics`
 a| 
檢索資料中心內所有 LUN 或磁碟區的高階效能指標。您可以根據所需條件篩選結果。傳回儲存 VM 和叢集鍵等資訊以及聚合 IOPS、吞吐量和收集週期（以小時為單位）等值。



 a| 
`GET`
 a| 
`/datacenter/svm/svms/{key}/metrics`
 a| 
檢索儲存 VM 鍵的輸入參數指定的儲存 VM 的效能資料（樣本和摘要）。根據每個支援的協定匯總 IOPS，例如 `nvmf, fcp, iscsi,`和 `nfs`、吞吐量、延遲和收集的樣本數量。



 a| 
`GET`
 a| 
`/datacenter/svm/svms/analytics`
 a| 
檢索資料中心內所有儲存虛擬機器的進階效能指標。您可以根據所需條件篩選結果。傳回儲存 VM UUID、聚合 IOPS、延遲、吞吐量和收集週期（以小時為單位）等資訊。



 a| 
`GET`
 a| 
`/datacenter/network/ethernet/ports/{key}/metrics`
 a| 
檢索由連接埠鍵的輸入參數指定的特定乙太網路連接埠的效能指標。當提供支援範圍的間隔（時間範圍）時，API 將傳回累積的計數器，例如該時間段內的最小值、最大值和平均效能值。



 a| 
`GET`
 a| 
`/datacenter/network/ethernet/ports/analytics`
 a| 
檢索資料中心環境中所有乙太網路連接埠的進階效能指標。傳回叢集和節點金鑰和 UUID、吞吐量、收集週期和連接埠的使用率百分比等資訊。您可以根據可用參數（例如連接埠鍵、使用率百分比、叢集和節點名稱以及 UUID 等）過濾結果。



 a| 
`GET`
 a| 
`/datacenter/network/fc/interfaces/{key}/metrics`
 a| 
檢索由介面鍵的輸入參數指定的特定網路 FC 介面的效能指標。當提供支援範圍的間隔（時間範圍）時，API 將傳回累積的計數器，例如該時間段內的最小值、最大值和平均效能值。



 a| 
`GET`
 a| 
`/datacenter/network/fc/interfaces/analytics`
 a| 
檢索資料中心環境中所有乙太網路連接埠的進階效能指標。傳回叢集和 FC 介面金鑰和 UUID、吞吐量、IOPS、延遲和儲存 VM 等資訊。您可以根據可用參數過濾結果，例如叢集和 FC 介面名稱和 UUID、儲存 VM、吞吐量等。



 a| 
`GET`
 a| 
`/datacenter/network/fc/ports/{key}/metrics`
 a| 
檢索由連接埠鍵的輸入參數指定的特定 FC 連接埠的效能指標。當提供支援範圍的間隔（時間範圍）時，API 將傳回累積的計數器，例如該時間段內的最小值、最大值和平均效能值。



 a| 
`GET`
 a| 
`/datacenter/network/fc/ports/analytics`
 a| 
檢索資料中心環境中所有 FC 連接埠的進階效能指標。傳回叢集和節點金鑰和 UUID、吞吐量、收集週期和連接埠的使用率百分比等資訊。您可以根據可用參數（例如連接埠鍵、使用率百分比、叢集和節點名稱以及 UUID 等）過濾結果。



 a| 
`GET`
 a| 
`/datacenter/network/ip/interfaces/{key}/metrics`
 a| 
檢索介面鍵的輸入參數指定的網路 IP 介面的效能指標。當從支援的範圍中提供一個間隔（時間範圍）時，API 將傳回訊息，例如樣本數、累積計數器、吞吐量以及接收和傳輸的資料包數。



 a| 
`GET`
 a| 
`/datacenter/network/ip/interfaces/analytics`
 a| 
檢索資料中心環境中所有網路 IP 介面的進階效能指標。傳回叢集和 IP 介面金鑰和 UUID、吞吐量、IOPS 和延遲等資訊。您可以根據可用參數過濾結果，例如叢集和 IP 介面名稱和 UUID、IOPS、延遲、吞吐量等。

|===