---
permalink: performance-checker/concept_cluster_configuration_and_performance_data_collection_activity.html 
sidebar: sidebar 
keywords: cluster, configuration, performance, data, collection, activity 
summary: 群集配置資料的收集間隔為15分鐘。例如，新增叢集後，需要 15 分鐘才能在 Unified Manager UI 中顯示叢集詳細資訊。對集群進行變更時也適用此間隔。 
---
= 叢集配置和效能資料收集活動
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
_群集配置資料_的收集間隔為15分鐘。例如，新增叢集後，需要 15 分鐘才能在 Unified Manager UI 中顯示叢集詳細資訊。對集群進行變更時也適用此間隔。

例如，如果您在叢集中的 SVM 中新增兩個新磁碟區，您將在下一個輪詢間隔（最長可達 15 分鐘）後在 UI 中看到這些新物件。

Unified Manager 每五分鐘從所有受監控的叢集收集一次目前_效能統計資料_。它分析這些數據以識別效能事件和潛在問題。它保留30天的五分鐘歷史性能數據和180天的一小時歷史性能數據。這使您可以查看當前月份的非常詳細的性能詳情以及長達一年的整體性能趨勢。

收集輪詢會偏移幾分鐘，以便每個叢集的資料不會同時發送，這可能會影響效能。

下表描述了 Unified Manager 執行的收集活動：

|===
| 活動 | 時間間隔 | 描述 


 a| 
績效統計調查
 a| 
每5分鐘
 a| 
從每個集群收集即時性能數據。



 a| 
統計分析
 a| 
每5分鐘
 a| 
每次統計輪詢後，Unified Manager 都會將收集的資料與使用者定義、系統定義和動態閾值進行比較。

如果超出任何效能閾值，Unified Manager 會產生事件並向指定使用者發送電子郵件（如果已設定為這樣做）。



 a| 
配置輪詢
 a| 
每15分鐘
 a| 
從每個叢集收集詳細的清單信息，以識別所有儲存物件（節點、SVM、磁碟區等）。



 a| 
總結
 a| 
每小時
 a| 
將最近 12 個五分鐘效能資料集合匯總為每小時平均值。

部分UI頁面採用每小時平均值，並保留180天。



 a| 
預測分析和資料修剪
 a| 
每天午夜後
 a| 
分析群集資料以建立未來 24 小時的捲延遲和 IOPS 的動態閾值。

從資料庫中刪除任何超過 30 天的五分鐘效能資料。



 a| 
資料修剪
 a| 
每天凌晨 2 點後
 a| 
從資料庫中刪除任何超過 180 天的事件以及超過 180 天的動態閾值。



 a| 
資料修剪
 a| 
每天凌晨 3:30 後
 a| 
從資料庫中刪除任何超過 180 天的一小時效能資料。

|===