---
permalink: performance-checker/concept_understand_um_recommendations_to_tier_data_to_cloud.html 
sidebar: sidebar 
keywords: understand, unified manager, recommendations, tier, data, cloud 
summary: 效能：所有磁碟區視圖顯示與非活動（冷）磁碟區上儲存的使用者資料大小相關的資訊。在某些情況下，Unified Manager 會識別某些卷，這些卷可以透過將非活動資料分層到啟用FabricPool的聚合的雲層（雲端提供者或StorageGRID ）而受益。 
---
= 了解 Unified Manager 將資料分層到雲端的建議
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
效能：所有磁碟區視圖顯示與非活動（冷）磁碟區上儲存的使用者資料大小相關的資訊。在某些情況下，Unified Manager 會識別某些卷，這些卷可以透過將非活動資料分層到啟用FabricPool的聚合的雲層（雲端提供者或StorageGRID ）而受益。

[NOTE]
====
FabricPool是在ONTAP 9.2 中引入的，因此如果您使用的是 9.2 之前的ONTAP軟體版本，則 Unified Manager 對分層資料的建議需要升級您的ONTAP軟體。此外， `*auto*` ONTAP 9.4 中引入了分層策略，並且 `*all*`分層策略是在ONTAP 9.6 中引入的，因此如果建議使用自動分層策略，則必須升級到ONTAP 9.4 或更高版本。

====
效能：所有磁碟區視圖上的以下三個欄位提供有關是否可以透過將非活動資料移至雲層來提高儲存系統的磁碟使用率並節省效能層空間的資訊。

* *分層保單*
+
分層策略決定磁碟區上的資料是否保留在效能層，或是否將部分資料從效能層移至雲層。

+
此欄位中的值表示在磁碟區上設定的分層策略，即使該磁碟區目前不駐留在FabricPool聚合上。只有當磁碟區位於FabricPool聚合上時，分層策略才會生效。

* *冷數據*
+
冷資料顯示非活動（冷）磁碟區上儲存的使用者資料的大小。

+
只有在使用ONTAP 9.4 或更高版本的軟體時，此處才會顯示值，因為它要求部署磁碟區的聚合具有 `*inactive data reporting parameter*`設定為 `*enabled*`，並且已達到最低冷卻天數閾值（對於使用 `*snapshot-only*`或者 `*auto*`分層策略）。否則，該值將被列為“`N/A`”。

* *雲端推薦*
+
在擷取有關磁碟區上的資料活動的足夠資訊後，Unified Manager 可能會確定不需要採取任何行動，或者您可以透過將非活動資料分層到雲層來節省效能圖層上的空間。



[NOTE]
====
冷資料欄位每 15 分鐘更新一次，但對磁碟區執行冷資料分析時雲端建議欄位每 7 天更新一次。因此，不同領域的冷數據的具體數量可能有所不同。雲端推薦欄位顯示運行分析的日期。

====
啟用非活動資料報告後，冷資料欄位將顯示非活動資料的確切數量。如果沒有非活動資料報告功能，Unified Manager 將使用效能統計資料來確定磁碟區上的資料是否為非活動狀態。在這種情況下，非活動資料量不會顯示在「冷資料」欄位中，但當您將遊標停留在單字「*Tier*」上以查看雲建議時，它會顯示出來。

您將看到的雲端建議是：

* *學習*。尚未收集足夠的數據來提出建議。
* *等級*。分析已確定該磁碟區包含非活動（冷）數據，並且您應該配置該磁碟區以將該資料移至雲層。在某些情況下，這可能會要求您先將磁碟區移至啟用FabricPool的聚合。在其他情況下，如果磁碟區已經位於FabricPool聚合上，您只需變更分層策略。
* *無動作*。該磁碟區具有非常少的非活動數據，該磁碟區已設定為FabricPool聚合上的「自動」分層策略，或該磁碟區是資料保護磁碟區。當磁碟區處於離線狀態或在MetroCluster配置中使用時，也會顯示此值。


若要移動磁碟區、變更磁碟區分層策略或聚合非活動資料報告設置，請使用ONTAP System Manager、 ONTAP CLI 指令或這些工具的組合。

如果您以應用程式管理員或儲存管理員角色登入 Unified Manager，則將遊標停留在單字 *Tier* 上時，雲端推薦中會出現 *Configure Volume* 連結。按一下此按鈕可開啟系統管理員中的磁碟區頁面以進行建議的變更。
