---
permalink: performance-checker/concept_performance_threshold_policies_when_object_is_moved.html 
sidebar: sidebar 
keywords: happens, performance, threshold, policies, object, moved 
summary: 由於效能閾值策略被指派給儲存對象，因此如果您移動某個對象，則在移動完成後，所有指派的閾值策略仍會附加到該物件。例如，如果您將磁碟區或 LUN 移至不同的聚合，則閾值策略對於新聚合上的磁碟區或 LUN 仍然有效。 
---
= 當物件移動時效能閾值策略會發生什麼變化
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
由於效能閾值策略被指派給儲存對象，因此如果您移動某個對象，則在移動完成後，所有指派的閾值策略仍會附加到該物件。例如，如果您將磁碟區或 LUN 移至不同的聚合，則閾值策略對於新聚合上的磁碟區或 LUN 仍然有效。

如果閾值策略（組合策略）存在輔助計數器條件（例如，如果為聚合或節點指派了附加條件），則輔助計數器條件將套用於磁碟區或 LUN 已移至的新聚合或節點。

如果對於使用變更後的閾值策略的物件存在任何新的活動事件，則這些事件將被標記為過時，並且閾值策略將開始按照新定義的閾值策略監控計數器。

磁碟區移動操作會導致ONTAP傳送訊息變更事件。效能資源管理器頁面和工作負載分析頁面的事件時間軸中會出現一個變更事件圖標，指示移動操作完成的時間。

[NOTE]
====
如果將物件移至不同的集群，則會從該物件中刪除使用者定義的閾值策略。如果需要，您必須在移動操作完成後為物件指派閾值策略。然而，動態和系統定義的閾值策略會在物件移動到新叢集後自動套用於該物件。

====


== HA 接管和交還期間的閾值策略功能

當在高可用性 (HA) 配置中發生接管或交還操作時，從一個節點移動到另一個節點的物件將以與手動移動操作相同的方式保留其閾值策略。由於 Unified Manager 每 15 分鐘檢查一次叢集配置更改，因此直到下次輪詢叢集配置時才能確定切換到新節點的影響。

[NOTE]
====
如果接管和交還操作都發生在 15 分鐘的配置變更收集期內，您可能看不到效能統計資訊從一個節點移動到另一個節點。

====


== 聚合遷移期間的閾值策略功能

如果使用 `aggregate relocation start`命令，單一和組合閾值策略都會保留在所有物件上，並且閾值策略的節點部分會應用於新節點。



== MetroCluster切換期間的閾值策略功能

在MetroCluster配置中從一個叢集移動到另一個叢集的物件不會保留其使用者定義的閾值策略設定。如果需要，您可以對已移至夥伴叢集的磁碟區和 LUN 套用閾值策略。當物件移回其原始叢集後，將自動重新套用使用者定義的閾值策略。

有關信息，請參閱link:../storage-mgmt/concept_volume_behavior_during_switchover_and_switchback.html["切換和切回期間的捲行為"]。
