---
permalink: performance-checker/concept_how_storage_qos_can_control_workload_throughput.html 
sidebar: sidebar 
keywords: storage, qos, control, workload, throughput 
summary: '您可以建立服務品質 (QoS) 策略群組來控制其包含的工作負載的每秒 I/O (IOPS) 或吞吐量 (MB/s) 限制。如果工作負載位於沒有設定限制的策略群組（例如預設策略群組）中，或設定的限制無法滿足您的需求，您可以增加限製或將工作負載移至具有所需限制的新策略群組或現有策略群組。' 
---
= 儲存 QoS 如何控制工作負載吞吐量
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以建立服務品質 (QoS) 策略群組來控制其包含的工作負載的每秒 I/O (IOPS) 或吞吐量 (MB/s) 限制。如果工作負載位於沒有設定限制的策略群組（例如預設策略群組）中，或設定的限制無法滿足您的需求，您可以增加限製或將工作負載移至具有所需限制的新策略群組或現有策略群組。

「傳統」QoS 策略群組可以指派給單一工作負載；例如單一磁碟區或 LUN。在這種情況下，工作負載可以使用全部吞吐量限制。 QoS 策略群組也可以指派給多個工作負載；在這種情況下，吞吐量限制在工作負載之間「共用」。例如，分配給三個工作負載的 QoS 限制為 9,000 IOPS，這將限制合併後的 IOPS 不能超過 9,000 IOPS。

「自適應」QoS 策略群組也可以指派給單一工作負載或多個工作負載。但是，即使指派給多個工作負載，每個工作負載也會獲得完整的吞吐量限制，而不是與其他工作負載共用吞吐量值。此外，自適應 QoS 策略會根據每個工作負載的磁碟區大小自動調整吞吐量設置，從而隨著磁碟區大小的變化保持 IOPS 與 TB 的比率。例如，如果在自適應 QoS 策略中將峰值設定為 5,000 IOPS/TB，則 10 TB 卷的最大吞吐量將為 50,000 IOPS。如果稍後將磁碟區大小調整為 20 TB，自適應 QoS 會將最大值調整為 100,000 IOPS。

從ONTAP 9.5 開始，您可以在定義自適應 QoS 策略時包含區塊大小。當工作負載使用非常大的區塊大小並最終使用大量吞吐量時，這可以有效地將策略從 IOPS/TB 閾值轉換為 MB/s 閾值。

對於共享群組 QoS 策略，當策略群組中所有工作負載的 IOPS 或 MB/s 超過設定的限制時，策略群組會限制工作負載以限制其活動，這會降低策略群組中所有工作負載的效能。如果動態效能事件是由策略群組限制產生的，則事件描述會顯示所涉及的策略群組的名稱。

在「效能：所有磁碟區」檢視中，您可以按 IOPS 和 MB/s 對受影響的磁碟區進行排序，以查看哪些工作負載的使用率最高，可能導致該事件。在效能/磁碟區資源管理器頁面中，您可以選擇其他磁碟區或磁碟區上的 LUN，以與受影響的工作負載 IOPS 或 MBps 吞吐量使用情況進行比較。

透過將過度使用節點資源的工作負載分配給更嚴格的策略群組設置，策略群組可以限制工作負載以限制其活動，從而減少該節點上資源的使用。但是，如果您希望工作負載能夠使用更多的節點資源，則可以增加策略群組的值。

您可以使用 System Manager、 ONTAP指令或 Unified Manager 效能服務等級來管理原則群組，包含下列任務：

* 建立策略組
* 在策略群組中新增或刪除工作負載
* 在策略組之間移動工作負載
* 更改策略群組的吞吐量限制
* 將工作負載移動到不同的聚合和/或節點

