---
permalink: performance-checker/concept_roles_of_workloads_involved_in_performance_incident.html 
sidebar: sidebar 
keywords: roles, workloads, involved, performance, event 
summary: Unified Manager 使用角色來識別工作負載在效能事件中的參與情況。角色包括受害者、霸凌者和鯊魚。使用者定義的工作負載可以同時是受害者、霸凌者和鯊魚。 
---
= 效能事件中涉及的工作負載的角色
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Unified Manager 使用角色來識別工作負載在效能事件中的參與情況。角色包括受害者、霸凌者和鯊魚。使用者定義的工作負載可以同時是受害者、霸凌者和鯊魚。

|===
| 角色 | 描述 


 a| 
受害者
 a| 
一種使用者定義的工作負載，由於其他工作負載（稱為“bullies”）過度使用叢集元件，導致其效能下降。只有使用者定義的工作負載才會被識別為受害者。  Unified Manager 根據延遲偏差來識別受害工作負載，其中事件期間的實際延遲與其延遲預測（預期範圍）相比大大增加。



 a| 
霸凌
 a| 
使用者定義或系統定義的工作負載，其過度使用叢集元件導致其他工作負載（稱為受害者）的效能下降。  Unified Manager 根據群集元件使用情況的偏差來識別霸凌工作負載，其中事件期間的實際使用情況大大超出了其預期的使用範圍。



 a| 
鯊魚
 a| 
與事件中涉及的所有工作負載相比，叢集元件使用率最高的使用者定義工作負載。  Unified Manager 根據事件期間叢集元件的使用情況來識別 shark 工作負載。

|===
叢集上的工作負載可以共用許多叢集元件，例如聚合以及用於網路和資料處理的 CPU。當工作負載（例如磁碟區）對叢集元件的使用率增加到該元件無法有效滿足工作負載需求的程度時，該元件就會處於爭用狀態。過度使用叢集組件的工作負載是一個惡霸。共享這些組件的其他工作負載，其表現受到霸凌的影響，是受害者。系統定義的工作負載（例如重複資料刪除或 Snapshot 副本）的活動也可能升級為「霸凌」。

當 Unified Manager 偵測到事件時，它會識別所涉及的所有工作負載和叢集元件，包括導致事件的霸凌工作負載、處於爭用的叢集元件以及由於霸凌工作負載活動增加而導致效能下降的受害工作負載。

[NOTE]
====
如果 Unified Manager 無法辨識霸凌工作負載，它只會對受害工作負載和所涉及的叢集元件發出警報。

====
Unified Manager 可以辨識受霸凌工作負荷影響的工作負載，也能辨識這些工作負載何時成為霸凌工作負載。工作量本身就可能是一種負擔。例如，受到策略群組限制限制的高效能工作負載會導致策略群組中的所有工作負載（包括其本身）受到限制。在正在進行的績效事件中作為霸凌者或受害者的工作負荷可能會改變其角色或不再是該事件的參與者。
