---
permalink: performance-checker/concept_components_of_performance_explorer_page.html 
sidebar: sidebar 
keywords: components, performance, explorer, page 
summary: 透過「效能資源管理器」頁面，您可以比較叢集中類似物件的效能 - 例如，叢集中的所有磁碟區。這在排除效能事件故障和微調物件效能時非常有用。您也可以將物件與根物件進行比較，根物件是進行其他物件比較的基線。 
---
= 效能資源管理器頁面的元件
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
透過「效能資源管理器」頁面，您可以比較叢集中類似物件的效能 - 例如，叢集中的所有磁碟區。這在排除效能事件故障和微調物件效能時非常有用。您也可以將物件與根物件進行比較，根物件是進行其他物件比較的基線。

您可以按一下「切換到健康視圖」按鈕來顯示此物件的健康詳細資料頁面。在某些情況下，您可以了解有關此物件的儲存配置設定的重要信息，這可能有助於解決問題。

效能資源管理器頁面顯示叢集物件及其效能資料的清單。此頁面以表格形式顯示相同類型的所有群集物件（例如，磁碟區及其特定於物件的效能統計資料）。此視圖提供了叢集物件效能的有效概覽。

[NOTE]
====
如果表格中的任何儲存格中出現“N/A”，則表示該計數器的值不可用，因為此時該物件上沒有 I/O。

====
效能資源管理器頁麵包含以下元件：

* *時間範圍*
+
使您能夠選擇物件資料的時間範圍。

+
您可以選擇預先定義的範圍，或指定您自己的自訂時間範圍。

* *查看並比較*
+
使您能夠選擇在網格中顯示哪種類型的相關物件。

+
可用的選項取決於根物件類型及其可用資料。您可以按一下「檢視和比較」下拉清單來選擇物件類型。您選擇的物件類型將顯示在清單中。

* *過濾*
+
使您能夠根據自己的喜好縮小接收的資料量。

+
您可以建立適用於物件資料的篩選器 - 例如，IOPS 大於 4。您最多可以同時新增四個濾鏡。

* *比較*
+
顯示您選擇與根物件進行比較的物件清單。

+
比較窗格中物件的資料顯示在計數器圖表中。

* *查看統計數據*
+
對於捲和 LUN，您可以選擇是否在每個收集週期（預設 5 分鐘）後顯示統計信息，或者是否以每小時平均值的形式顯示統計信息。此功能可讓您查看支援NetApp 「效能保證」計畫的延遲圖表。

* *反圖表*
+
顯示每個物件效能類別的圖形資料。

+
通常，預設僅顯示三到四個圖表。選擇圖表組件可讓您顯示其他圖表或隱藏特定圖表。您也可以選擇顯示或隱藏事件時間軸。

* *事件時間表*
+
顯示您在時間範圍元件中選擇的時間線上發生的效能和健康事件。


