---
permalink: performance-checker/concept_cluster_components_and_why_they_can_be_in_contention.html 
sidebar: sidebar 
keywords: cluster, components, why, contention 
summary: 當叢集元件發生爭用時，您可以識別叢集效能問題。使用該元件的工作負載的效能會變慢，且其對用戶端請求的回應時間（延遲）會增加，從而觸發 Unified Manager 中的事件。 
---
= 集群組件及其爭用的原因
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
當叢集元件發生爭用時，您可以識別叢集效能問題。使用該元件的工作負載的效能會變慢，且其對用戶端請求的回應時間（延遲）會增加，從而觸發 Unified Manager 中的事件。

存在爭用的組件無法達到最佳效能。它的性能已經下降，並且其他群集組件和工作負載（稱為“受害者”）的性能可能會增加延遲。要使組件擺脫爭用，必須減少其工作負載或提高其處理更多工作的能力，以便效能恢復到正常水準。由於 Unified Manager 以五分鐘為間隔收集和分析工作負載效能，因此它僅偵測叢集元件何時持續過度使用。未偵測到在五分鐘間隔內僅持續很短時間的過度使用瞬態峰值。

例如，儲存聚合可能處於爭用狀態，因為其上的一個或多個工作負載正在競爭滿足其 I/O 請求。聚合上的其他工作負載可能會受到影響，導致其效能下降。為了減少聚合上的活動量，您可以採取不同的步驟，例如將一個或多個工作負載移至較不繁忙的聚合或節點，以減少目前聚合上的整體工作負載需求。對於 QoS 策略群組，您可以調整吞吐量限制，或將工作負載移至其他策略群組，這樣工作負載就不會再受到限制。

Unified Manager 監控以下叢集元件，並在它們發生爭用時提醒您：

* *網路*
+
表示叢集上外部網路協定的 I/O 請求的等待時間。等待時間是指叢集回應 I/O 請求之前等待「傳輸就緒」事務完成所花費的時間。如果網路元件處於爭用狀態，則表示協定層的高等待時間會影響一個或多個工作負載的延遲。

* *網路處理*
+
表示集群中涉及協定層和集群之間的 I/O 處理的軟體元件。自從偵測到該事件以來，處理網路處理的節點可能已經發生變化。如果網路處理元件存在爭用，則表示網路處理節點的高利用率正在影響一個或多個工作負載的延遲。

+
在主動-主動配置中使用全 SAN 陣列群集時，將顯示兩個節點的網路處理延遲值，以便您可以驗證節點是否平等地共享負載。

* *QoS 限制最大值*
+
表示指派給工作負載的儲存服務品質 (QoS) 策略群組的最大吞吐量（峰值）設定。如果策略群組元件存在爭用，則表示策略群組中的所有工作負載都受到設定的吞吐量限制的限制，這會影響其中一個或多個工作負載的延遲。

* *QoS 限制最小值*
+
表示由分配給其他工作負載的 QoS 吞吐量最小（預期）設定導致的工作負載延遲。如果某些工作負載上設定的 QoS 最小值使用大部分頻寬來保證承諾的吞吐量，則其他工作負載將受到限制並出現更多延遲。

* *集群互連*
+
表示叢集節點實體連接的電纜和適配器。如果叢集互連元件處於爭用狀態，則表示叢集互連處 I/O 請求的等待時間過長會影響一個或多個工作負載的延遲。

* *Data Processing*
+
表示叢集中涉及叢集與包含工作負載的儲存聚合之間的 I/O 處理的軟體元件。自從偵測到事件以來，處理資料處理的節點可能已經發生變化。如果資料處理元件存在爭用，則表示資料處理節點的高利用率正在影響一個或多個工作負載的延遲。

* *音量啟動*
+
表示追蹤所有活動卷使用情況的進程。在有超過 1000 個磁碟區處於活動狀態的大型環境中，此流程會追蹤有多少個關鍵磁碟區需要同時透過節點存取資源。當並發活動卷的數量超過建議的最大閾值時，一些非關鍵卷將會出現此處標識的延遲。

* * MetroCluster資源*
+
表示MetroCluster資源，包括NVRAM和交換器間連結 (ISL)，用於在MetroCluster配置中的叢集之間鏡像資料。如果MetroCluster元件存在爭用，則表示本地叢集上的工作負載的高寫入吞吐量或連結健康問題正在影響本地叢集上一個或多個工作負載的延遲。如果叢集不在MetroCluster配置中，則不會顯示此圖示。

* *聚合或 SSD 聚合操作*
+
表示運行工作負載的儲存聚合。如果聚合元件存在爭用，則表示聚合的高利用率正在影響一個或多個工作負載的延遲。聚合由所有 HDD 組成，或由 HDD 和 SSD 的混合（Flash Pool 聚合）組成，或由 HDD 和雲層的混合（ FabricPool聚合）組成。  「SSD 聚合」由所有 SSD（全快閃聚合）或 SSD 和雲層（ FabricPool聚合）的混合組成。

* *雲延遲*
+
表示叢集中涉及叢集和儲存使用者資料的雲層之間的 I/O 處理的軟體元件。如果雲端延遲元件存在爭用，則表示託管在雲層上的磁碟區的大量讀取會影響一個或多個工作負載的延遲。

* *同步SnapMirror*
+
表示叢集中涉及在SnapMirror同步關係中將使用者資料從主磁碟區複製到輔助磁碟區的軟體元件。如果同步SnapMirror元件存在爭用，則表示SnapMirror同步操作的活動正在影響一個或多個工作負載的延遲。


