---
permalink: performance-checker/concept_what_expected_range_of_performance_is.html 
sidebar: sidebar 
keywords: expected, range, performance, latency, forecast, formed 
summary: 延遲預測是對特定時間的上限和下限性能值的預測。對於工作負載延遲，上限值構成效能閾值。當實際值超過效能閾值時，Unified Manager 會觸發動態效能事件。 
---
= 預期的表現範圍是多少
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
延遲預測是對特定時間的上限和下限性能值的預測。對於工作負載延遲，上限值構成效能閾值。當實際值超過效能閾值時，Unified Manager 會觸發動態效能事件。

例如，在上午 9:00 至下午 5:00 的正常工作時間內，大多數員工可能會在上午 9:00 至上午 10:30 之間查看電子郵件。電子郵件伺服器需求的增加意味著此時間段內後端儲存的工作負載活動也會增加。員工可能會注意到他們的電子郵件用戶端的回應時間很慢。

在中午 12 點到下午 1 點之間的午餐時間以及下午 5 點之後的工作時間結束時，大多數員工可能不會使用電腦。對電子郵件伺服器的需求通常會減少，對後端儲存的需求也會減少。或者，可以有預定的工作負載操作，例如儲存備份或病毒掃描，這些操作在下午 5:00 之後開始，並增加後端儲存的活動。

幾天內，工作負載活動的增加和減少決定了活動的預期範圍（延遲預測），並確定了工作負載的上限和下限。當物件的實際工作負載活動超出上限或下限，並在一段時間內保持超出邊界時，這可能表示該物件被過度使用或未充分使用。



== 延遲預測是如何形成的

Unified Manager 必須收集至少 3 天的工作負載活動，然後才能開始分析，並且 I/O 回應時間的延遲預測才能顯示在 GUI 中。所需的最低限度的資料收集並未考慮到工作負載活動發生的所有變化。在收集前 3 天的活動後，Unified Manager 會在每 24 小時的凌晨 12:00 調整延遲預測，以反映工作負載活動的變化並建立更準確的動態效能閾值。

[NOTE]
====
夏令時 (DST) 會改變系統時間，從而改變受監控工作負載的效能統計資料的延遲預測。 Unified Manager 立即開始更正延遲預測，大約需要 15 天才能完成。在此期間，您可以繼續使用 Unified Manager，但是，由於 Unified Manager 使用延遲預測來偵測動態事件，因此某些事件可能不準確。時間變化之前偵測到的事件不受影響。

====