---
permalink: performance-checker/reference_types_of_system_defined_performance_threshold_policies.html 
sidebar: sidebar 
keywords: system-defined, performance, threshold, policies, cluster, node. aggregate, qos 
summary: Unified Manager 提供了一些標準閾值策略，用於監控叢集效能並自動產生事件。這些策略預設為啟用，當監控的效能閾值被突破時，它們會產生警告或資訊事件。 
---
= 系統定義的效能閾值策略的類型
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Unified Manager 提供了一些標準閾值策略，用於監控叢集效能並自動產生事件。這些策略預設為啟用，當監控的效能閾值被突破時，它們會產生警告或資訊事件。

[NOTE]
====
Cloud Volumes ONTAP、 ONTAP Edge 或ONTAP Select系統上未啟用系統定義的效能閾值策略。

====
如果您從任何系統定義的效能閾值策略收到不必要的事件，您可以從事件設定頁面停用單一策略的事件。



== 集群閾值策略

預設情況下，系統定義的叢集效能閾值策略會指派給 Unified Manager 監控的每個叢集：

* 叢集負載不平衡
+
識別一個節點的負載比叢集中其他節點高得多的情況，因此可能會影響工作負載延遲。

+
它透過比較叢集中所有節點的效能容量使用值來查看是否有任何節點超過 30% 的閾值超過 24 小時。這是一個警告事件。

* 叢集容量不平衡
+
識別一個聚合的已使用容量比叢集中的其他聚合高得多的情況，因此可能會影響操作所需的空間。

+
它透過比較叢集中所有聚合的已使用容量值來查看聚合之間是否存在 70% 的差異。這是一個警告事件。





== 節點閾值策略

預設情況下，系統定義的節點效能閾值策略會指派給 Unified Manager 監控的叢集中的每個節點：

* *已突破性能容量使用門檻*
+
識別單一節點的運作效率超出其界限並因此可能影響工作負載延遲的情況。

+
它透過尋找使用效能容量超過 100% 且持續時間超過 12 小時的節點來實現這一點。這是一個警告事件。

* *節點 HA 對過度使用*
+
識別 HA 對中的節點運行超出 HA 對運行效率界限的情況。

+
它透過查看 HA 對中兩個節點的效能容量使用值來實現這一點。如果兩個節點使用的效能容量總和超過 200% 且持續時間超過 12 小時，則控制器故障轉移將影響工作負載延遲。這是一個資訊事件。

* *節點磁碟碎片*
+
識別聚合中的一個或多個磁碟碎片化的情況，從而降低關鍵系統服務的速度並可能影響節點上的工作負載延遲。

+
它透過查看節點上所有聚合的某些讀寫操作比率來實現這一點。在SyncMirror重新同步期間或在磁碟清理操作期間發現錯誤時也可能會觸發此策略。這是一個警告事件。

+
[NOTE]
====
「節點磁碟碎片」策略僅分析 HDD 聚合；不分析 Flash Pool、SSD 和FabricPool聚合。

====




== 聚合閾值策略

系統定義的聚合效能閾值策略預設指派給 Unified Manager 監控的叢集中的每個聚合：

* *聚合磁碟過度利用*
+
識別聚合運作超出其運作效率極限的情況，從而可能影響工作負載延遲。它透過尋找聚合中磁碟利用率超過 95% 且持續時間超過 30 分鐘的聚合來識別這些情況。然後，此多條件策略執行以下分析以幫助確定問題的原因：

+
** 聚合中的磁碟目前是否正在進行後台維護活動？
+
磁碟可能正在進行的一些後台維護活動包括磁碟重建、磁碟清理、 SyncMirror重新同步和重新奇偶校驗。

** 磁碟架光纖通道互連是否存在通訊瓶頸？
** 整體而言，可用空間是否太少？只有當三項下屬政策中的一項（或多項）也被視為違反時，才會針對該政策發出警告事件。如果僅聚合中的磁碟利用率超過 95%，則不會觸發效能事件。




[NOTE]
====
「聚合磁碟過度利用」策略分析僅 HDD 聚合和 Flash Pool（混合）聚合；不分析 SSD 和FabricPool聚合。

====


== 工作負載延遲閾值策略

系統定義的工作負載延遲閾值策略指派給任何具有已配置效能服務等級策略且具有已定義「預期延遲」值的工作負載：

* *工作負載磁碟區/LUN 延遲閾值超出效能服務等級定義*
+
識別超出其「預期延遲」限制並影響工作負載效能的磁碟區（檔案共用）和 LUN。這是一個警告事件。

+
它透過尋找前一小時內 30% 的時間內超過預期延遲值的工作負載來實現這一點。





== QoS 閾值策略

系統定義的 QoS 效能閾值策略指派給任何具有配置的ONTAP QoS 最大吞吐量策略（IOPS、IOPS/TB 或 MB/s）的工作負載。當工作負載吞吐量值比配置的 QoS 值低 15% 時，Unified Manager 會觸發一個事件：

* *QoS 最大 IOPS 或 MB/s 閾值*
+
識別已超出其 QoS 最大 IOPS 或 MB/s 吞吐量限制並影響工作負載延遲的捲和 LUN。這是一個警告事件。

+
當將單一工作負載指派給策略群組時，它會透過尋找前一小時每個收集期間內超過指派的 QoS 策略群組中定義的最大吞吐量閾值的工作負載來實現此目的。

+
當多個工作負載共用單一 QoS 策略時，它會透過將策略中所有工作負載的 IOPS 或 MB/s 相加並根據閾值檢查總數來實現此目的。

* *QoS 峰值 IOPS/TB 或具有區塊大小閾值的 IOPS/TB*
+
識別已超出其自適應 QoS 峰值 IOPS/TB 吞吐量限制（或具有區塊大小限制的 IOPS/TB）且影響工作負載延遲的磁碟區。這是一個警告事件。

+
它透過將自適應 QoS 策略中定義的峰值 IOPS/TB 閾值轉換為基於每個磁碟區大小的 QoS 最大 IOPS 值來實現此目的，然後尋找在前一小時的每個效能收集期間超過 QoS 最大 IOPS 的捲。

+
[NOTE]
====
只有當叢集安裝了ONTAP 9.3 及更高版本的軟體時，此策略才適用於磁碟區。

====
+
當自適應 QoS 策略中定義了「區塊大小」元素時，閾值將根據每個磁碟區的大小轉換為 QoS 最大 MB/s 值。然後，它會查找前一小時每個效能收集期間內超過 QoS 最大 MB/s 的捲。

+
[NOTE]
====
只有當叢集安裝了ONTAP 9.5 及更高版本的軟體時，此策略才適用於磁碟區。

====

