---
permalink: performance-checker/reference_what_performance_metrics_can_be_monitored_using_thresholds.html 
sidebar: sidebar 
keywords: performance, counters, tracked, thresholds 
summary: 一些常見的效能計數器，例如 IOPS 和 MB/s，可以為所有儲存物件設定閾值。還有其他計數器可以僅為某些儲存物件設定閾值。 
---
= 可以使用閾值追蹤哪些效能計數器
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
一些常見的效能計數器，例如 IOPS 和 MB/s，可以為所有儲存物件設定閾值。還有其他計數器可以僅為某些儲存物件設定閾值。



== 可用的性能計數器

|===
| 儲存對象 | 性能計數器 | 描述 


 a| 
簇
 a| 
每秒輸入/輸出次數
 a| 
集群每秒處理的平均輸入/輸出操作數。



 a| 
MB/秒
 a| 
每秒傳輸到該集群和從該集群傳輸的平均資料兆位元組數。



 a| 
節點
 a| 
每秒輸入/輸出次數
 a| 
節點每秒處理的平均輸入/輸出運算元。



 a| 
MB/秒
 a| 
每秒傳輸到該節點和從該節點傳輸的平均資料兆位元組數。



 a| 
延遲
 a| 
節點響應應用程式請求所需的平均毫秒數。



 a| 
使用率
 a| 
節點的 CPU 和 RAM 的平均使用百分比。



 a| 
已使用的性能容量
 a| 
節點消耗的效能容量的平均百分比。



 a| 
已使用的效能容量 - 接管
 a| 
節點所消耗的效能容量的平均百分比，加上其夥伴節點的效能容量。



 a| 
總計的
 a| 
每秒輸入/輸出次數
 a| 
聚合每秒處理的平均輸入/輸出運算元。



 a| 
MB/秒
 a| 
每秒傳輸到該聚合體和從該聚合體傳輸的平均資料兆位元組數。



 a| 
延遲
 a| 
聚合響應應用程式請求所需的平均毫秒數。



 a| 
使用率
 a| 
正在使用的聚合磁碟的平均百分比。



 a| 
已使用的性能容量
 a| 
聚合所消耗的性能容量的平均百分比。



 a| 
儲存虛擬機
 a| 
每秒輸入/輸出次數
 a| 
SVM 每秒處理的平均輸入/輸出運算元。



 a| 
MB/秒
 a| 
每秒傳輸到和從此 SVM 的資料的平均兆位元組數。



 a| 
延遲
 a| 
SVM 回應應用程式請求所需的平均毫秒數。



 a| 
體積
 a| 
每秒輸入/輸出次數
 a| 
此卷每秒處理的平均輸入/輸出操作數。



 a| 
MB/秒
 a| 
每秒傳輸到該磁碟區和從該磁碟區傳輸的平均資料兆位元組數。



 a| 
延遲
 a| 
卷響應應用程式請求所需的平均毫秒數。



 a| 
快取未命中率
 a| 
來自客戶端應用程式的讀取請求中，從磁碟區返回而不是從快取返回的平均百分比。



 a| 
邏輯單元號
 a| 
每秒輸入/輸出次數
 a| 
LUN 每秒處理的平均輸入/輸出運算元。



 a| 
MB/秒
 a| 
每秒傳輸到該 LUN 和從該 LUN 傳輸的平均資料兆位元組數。



 a| 
延遲
 a| 
LUN 回應應用程式請求所需的平均毫秒數。



 a| 
命名空間
 a| 
每秒輸入/輸出次數
 a| 
命名空間每秒處理的輸入/輸出操作的平均數。



 a| 
MB/秒
 a| 
每秒傳輸到該命名空間和從該命名空間傳輸的平均資料兆位元組數。



 a| 
延遲
 a| 
命名空間響應應用程式請求所需的平均毫秒數。



 a| 
港口
 a| 
頻寬利用率
 a| 
正在使用的連接埠可用頻寬的平均百分比。



 a| 
MB/秒
 a| 
每秒傳輸到該連接埠和從該連接埠傳輸的平均資料兆位元組數。



 a| 
網路介面 (LIF)
 a| 
MB/秒
 a| 
每秒傳輸到此 LIF 和從此 LIF 傳輸的平均資料兆位元組數。

|===