---
permalink: performance-checker/reference_types_of_performance_counter_charts.html 
sidebar: sidebar 
keywords: types, performance, counter, charts 
summary: 有標準效能圖表顯示所選儲存物件的計數器值。每個細分計數器圖表顯示分為讀取、寫入和其他類別的總值。此外，當圖表以縮放視圖顯示時，一些細分計數器圖表會顯示更多詳細資訊。 
---
= 效能計數器圖表的類型
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
有標準效能圖表顯示所選儲存物件的計數器值。每個細分計數器圖表顯示分為讀取、寫入和其他類別的總值。此外，當圖表以縮放視圖顯示時，一些細分計數器圖表會顯示更多詳細資訊。

下表顯示了可用的效能計數器圖表。

|===
| 可用圖表 | 圖表描述 


 a| 
活動
 a| 
顯示與根物件的統計圖表相關的嚴重、錯誤、警告和資訊事件。除了性能事件之外，還顯示健康事件，以提供性能可能受到影響的原因的完整情況。



 a| 
延遲 - 總計
 a| 
響應應用程式請求所需的毫秒數。請注意，平均延遲值是 I/O 加權的。



 a| 
延遲 - 細分
 a| 
「延遲總計」中顯示相同的訊息，但效能資料分為讀取、寫入和其他延遲。只有當選取的物件是 SVM、節點、聚合、磁碟區、LUN 或命名空間時，此圖表選項才適用。



 a| 
延遲 - 集群組​​件
 a| 
「延遲總計」中顯示相同的訊息，但效能數據依群集組件分為延遲。此圖表選項僅當選取物件為體積時才適用。



 a| 
IOPS - 總計
 a| 
每秒處理的輸入/輸出運算元。當顯示某個節點時，選擇「總計」將顯示透過此節點移動的資料的 IOPS，這些資料可能駐留在本地或遠端節點上，而選擇「總計（本地）」將顯示僅駐留在目前節點上的資料的 IOPS。



 a| 
IOPS - 細分
 a| 
IOPS Total 顯示相同的訊息，但效能資料分為讀取、寫入和其他 IOPS。只有當選取的物件是 SVM、節點、聚合、磁碟區、LUN 或命名空間時，此圖表選項才適用。

當在縮放檢視中顯示時，磁碟區圖表會顯示 QoS 最小和最大吞吐量值（如果在ONTAP中配置）。

當顯示某個節點時，選擇「細分」將顯示透過此節點移動的資料的 IOPS 細分，這些資料可能會駐留在本地或遠端節點上，而選擇「細分（本地）」將顯示僅駐留在目前節點上的資料的 IOPS 細分。



 a| 
IOPS - 協議
 a| 
IOPS Total 顯示相同的訊息，但效能資料分為 CIFS、NFS、FCP、NVMe 和 iSCSI 協定流量的單獨圖表。此圖表選項僅當選取的物件是 SVM 時才適用。



 a| 
IOPS/TB - 總計
 a| 
根據工作負載所佔用的總空間，每秒處理的輸入/輸出操作數（以 TB 為單位）。此計數器也稱為 I/O 密度，用於衡量給定儲存容量可以提供多少效能。如果在ONTAP中配置，則在縮放檢視中顯示磁碟區圖表會顯示 QoS 預期值和峰值吞吐量值。

此圖表選項僅當選取物件為體積時才適用。



 a| 
MB/s - 總計
 a| 
每秒傳輸到物件和從物件傳輸的資料（兆位元組數）。



 a| 
MB/s - 細分
 a| 
MB/s 圖表中顯示相同的訊息，但吞吐量資料分為磁碟讀取、快閃記憶體讀取、寫入和其他。當在縮放檢視中顯示時，磁碟區圖表會顯示 QoS 最大吞吐量值（如果在ONTAP中配置）。

只有當選取的物件是 SVM、節點、聚合、磁碟區、LUN 或命名空間時，此圖表選項才適用。

[NOTE]
====
只有在節點中安裝了 Flash Cache 模組時，才會顯示 Flash Cache 資料。

====


 a| 
已使用的效能容量 - 總計
 a| 
節點或聚合所消耗的效能容量百分比。



 a| 
已使用性能容量 - 明細
 a| 
效能容量所使用的資料分為使用者協定和系統後台進程。此外，還顯示了可用的效能容量。



 a| 
可用 IOPS - 總計
 a| 
此物件上目前可用（免費）的每秒輸入/輸出操作數。此數字是從 Unified Manager 計算的物件可以執行的總 IOPS 中減去目前使用的 IOPS 的結果。僅當選取的物件是節點或聚合時，此圖表選項才適用。



 a| 
利用率 - 總計
 a| 
正在使用的物件的可用資源百分比。利用率表示節點的節點利用率、聚合的磁碟利用率和連接埠的頻寬利用率。此圖表選項僅當選定的物件是節點、聚合或連接埠時才適用。



 a| 
快取未命中率 - 總計
 a| 
來自客戶端應用程式的讀取請求中從磁碟返回而不是從快取返回的百分比。此圖表選項僅當選取物件為體積時才適用。

|===