---
permalink: performance-checker/reference_what_data_does_workload_analyzer_display.html 
sidebar: sidebar 
keywords: workload analyzer, charts, display, data 
summary: 工作負載分析器頁面顯示有關可能影響工作負載的任何當前事件的資訊、可能修復導致事件的問題的建議以及用於分析效能和容量歷史記錄的圖表。 
---
= 工作負載分析器顯示哪些數據
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
工作負載分析器頁面顯示有關可能影響工作負載的任何當前事件的資訊、可能修復導致事件的問題的建議以及用於分析效能和容量歷史記錄的圖表。

在頁面頂部，您可以指定要分析的工作負載（磁碟區或 LUN）的名稱以及要查看統計資料的時間範圍。如果您想查看更短或更長的時間段，您可以隨時變更時間範圍。

頁面的其他區域顯示分析結果以及效能和容量圖表。

[NOTE]
====
LUN 的工作負載圖表不提供與卷圖表相同級別的統計信息，因此在分析這兩種類型的工作負載時您會注意到差異。

====
* *活動摘要區*
+
顯示一段時間內發生的事件的數量和類型的簡要概述。當有來自不同影響領域（例如效能和容量）的事件時，會顯示此訊息，以便您可以選擇感興趣的事件類型的詳細資訊。按一下事件類型以查看事件名稱清單。

+
如果該時間範圍內只有一個事件，則會針對某些事件列出修復該問題的建議清單。

* *事件時間表*
+
顯示指定時間範圍內發生的所有事件。將遊標停留在每個事件上即可查看事件名稱。

+
如果您透過點擊事件詳細資料頁面上的「分析工作負載」按鈕到達此頁面，則所選事件的圖示將會變得更大，以便您識別該事件。

* *性能圖表區域*
+
根據您選擇的時間範圍顯示延遲、吞吐量（IOPS 和 MB/s）和利用率（節點和聚合）的圖表。如果您想進行進一步的分析，可以按一下「查看效能詳細資料」連結來顯示工作負載的效能資源管理器頁面。

+
** *延遲*顯示所選時間範圍內工作負載的延遲。此圖表有三種視圖，您可以查看：
+
*** *總*延遲
*** *細分*延遲（按讀取、寫入和其他流程細分）
*** *集群組件*延遲（按集群組件細分）






看link:concept_cluster_components_and_why_they_can_be_in_contention.html["集群組件及其爭用的原因"]有關此處顯示的集群組件的說明。 ** *吞吐量*顯示所選時間範圍內工作負載的 IOPS 和 MB/s 吞吐量。此圖表有四個視圖，可讓您查看：*** *總*吞吐量*** *細分*吞吐量（按讀取、寫入和其他流程細分）*** *雲端吞吐量*（用於將資料寫入雲端和從雲端讀取資料的 MB/s；適用於將容量分層到雲端的工作負載）*** *帶預測的 IOPS*（預測在時間範圍內預期的上限和下限值圖表 IOPS 輸出值 (QoS)最大和最小吞吐量閾值設定（如果已配置），因此您可以看到系統可能在何處使用 QoS 策略有意限制吞吐量。 ** *利用率*顯示在選定時間範圍內運行工作負載的聚合和節點的利用率。從這裡您可以看到您的聚合或節點是否被過度利用，這可能導致高延遲。分析FlexGroup磁碟區時，利用率圖表上列出了多個節點和多個聚合。

* *容量圖表區域*
+
顯示過去一個月工作負載的資料容量和快照容量圖表。

+
對於卷，您可以按一下查看容量詳細資料連結以顯示工作負載的運行狀況詳細資訊頁面，以便進行進一步的分析。  LUN 不提供此鏈接，因為沒有 LUN 的“健康詳情”頁面。

+
** *容量視圖*顯示分配給工作負載的總可用空間和邏輯使用空間（經過所有NetApp優化後）。
** *Snapshot View* 顯示為 Snapshot 副本保留的總空間以及目前正在使用的空間量。請注意，LUN 不提供快照視圖。
** *雲層視圖*顯示本機效能層中正在使用的容量以及雲層中正在使用的容量。這些圖表包括容量滿載之前剩餘時間的估計值。此資訊基於歷史使用情況，需要至少 10 天的資料。當剩餘容量少於 30 天時，Unified Manager 會將儲存空間標識為「幾乎已滿」。



