---
permalink: performance-checker/reference_components_of_node_failover_planning_page.html 
sidebar: sidebar 
keywords: components, node, failover, planning page, performance, statistics, grid 
summary: 效能/節點故障轉移計畫頁面的元件顯示在網格和比較窗格中。這些部分可讓您評估節點故障轉移對接管節點效能的影響。 
---
= 節點故障轉移計劃頁面的元件
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
效能/節點故障轉移計畫頁面的元件顯示在網格和比較窗格中。這些部分可讓您評估節點故障轉移對接管節點效能的影響。



== 績效統計網格

效能/節點故障轉移規劃頁面顯示一個網格，其中包含延遲、IOPS、利用率和使用的效能容量的統計資料。

[NOTE]
====
此頁面和效能/節點效能資源管理器頁面中顯示的延遲和 IOPS 值可能不匹配，因為使用不同的效能計數器來計算預測節點故障轉移的值。

====
在網格中，每個節點被指派以下角色之一：

* 基本的
+
當 HA 合作夥伴發生故障時接管該合作夥伴的節點。根物件始終是主節點。

* 夥伴
+
故障轉移場景中發生故障的節點。

* 預計收購
+
與主節點相同。此節點顯示的效能統計資料顯示了接管節點接管故障夥伴節點後的效能。



[NOTE]
====
儘管故障轉移後接管節點的工作負載相當於兩個節點工作負載的總和，但估計接管節點的統計資料並不是主節點和合作夥伴節點統計資料的總和。例如，如果主節點的延遲為 2 ms/op，則合作夥伴節點的延遲為 3 ms/op，則估計接管節點的延遲可能為 4 ms/op。此值是 Unified Manager 執行的計算。

====
如果您希望合作夥伴節點成為根對象，可以按一下其名稱。顯示「效能/節點效能資源管理器」頁面後，您可以按一下「故障轉移計畫」標籤來查看此節點故障場景下效能如何變化。例如，如果 Node1 是主節點，Node2 是合作夥伴節點，則可以按一下 Node2 使其成為主節點。透過這種方式，您可以看到估計的效能如何根據哪個節點發生故障而變化。



== 比較窗格

以下清單描述了比較窗格中預設顯示的元件：

* *事件圖表*
+
它們以與效能/節點效能資源管理器頁面中相同的格式顯示。它們僅屬於主節點。

* *反圖表*
+
它們顯示網格中顯示的效能計數器的歷史統計資料。在每個圖表中，估計接管節點的圖形顯示了在任何給定時間發生故障轉移時的估計效能。

+
例如，假設利用率圖表顯示 2 月 8 日上午 11 點預計接管節點的利用率為 73%。如果當時發生故障轉移，接管節點的利用率將達到 73%。

+
歷史統計資料可以幫助您找到啟動故障轉移的最佳時間，以最大限度地減少接管節點過載的可能性。您僅可以在接管節點的預測效能可接受時安排故障轉移。



預設情況下，根物件和夥伴節點的統計資料都會顯示在比較窗格中。與效能/節點效能資源管理器頁面不同，此頁面不顯示*新增*按鈕供您新增物件進行統計比較。

您可以按照與在效能/節點效能資源管理器頁面中相同的方式自訂比較窗格。以下列表顯示了自訂圖表的範例：

* 按一下節點名稱可在計數器圖表中顯示或隱藏該節點的統計資料。
* 按一下「縮放檢視」可在新視窗中顯示特定計數器的詳細圖表。

