---
permalink: performance-checker/task_move_workloads_to_node_in_different_ha_pair.html 
sidebar: sidebar 
keywords: move, workloads, node, different, ha pair 
summary: '您可以使用 Unified Manager 來協助識別不同高可用性 (HA) 對中節點上的聚合，該聚合比您的工作負載目前運行的 HA 對具有更多的可用性能容量。然後，您可以將選定的磁碟區移至新 HA 對上的聚合。' 
---
= 將工作負載移至不同 HA 對中的節點
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以使用 Unified Manager 來協助識別不同高可用性 (HA) 對中節點上的聚合，該聚合比您的工作負載目前運行的 HA 對具有更多的可用性能容量。然後，您可以將選定的磁碟區移至新 HA 對上的聚合。

.開始之前
* 您必須具有操作員、應用程式管理員或儲存管理員角色。
* 您的集群必須至少包含兩個 HA 對
+
如果您的叢集中只有一個 HA 對，則無法使用此修復程序。

* 您必須記錄 HA 對中目前存在效能問題的兩個節點的名稱。
* 您必須記錄節點接收效能事件的日期和時間。
* Unified Manager 必須收集並分析一個月或更長時間的效能資料。


將高效能工作負載移至具有更多可用性能容量的節點上的聚合體，可使兩個節點上的工作負載更有效率地執行。此流程可協助您識別下列資源，以便您可以將高效能工作負載移至不同 HA 對上具有更多可用性能容量的節點：

* 在同一叢集上不同 HA 對中具有最大可用性能容量的節點
* 新節點上具有最大可用性能容量的聚合
* 當前節點上效能最高的捲


.步驟
. 辨識屬於同一叢集上不同 HA 對的節點：
+
.. 在「事件詳情」頁面上，按一下節點所在叢集的名稱。
+
集群詳細資訊顯示在效能/集群登陸頁面中。

.. 在「*摘要*」頁面上，按一下「*管理物件*」窗格中的「*節點*」。
+
此叢集上的節點清單顯示在「效能：所有節點」視圖中。

.. 記下與目前存在效能問題的 HA 對不同的 HA 對中的節點的名稱。


. 確定新 HA 對中具有最大可用性能容量的節點：
+
.. 在「效能：所有節點」檢視中，按一下「已使用效能容量」列，依使用率最低的百分比對節點進行排序。
+
這提供了您可能想要將工作負載移動到的潛在節點的清單。

.. 記下您想要將工作負載移到的不同 HA 對上的節點的名稱。


. 確定新節點上具有最大可用性能容量的聚合：
+
.. 在「效能：所有節點」視圖中，按一下該節點。
+
節點詳細資訊顯示在效能/節點資源管理器頁面中。

.. 在*檢視和比較*選單中，選擇*此節點上的聚合*。
+
此節點上的聚合顯示在網格中。

.. 按一下「已使用的效能容量」列，以最少使用對聚合進行排序。
+
這提供了您可能想要移動工作負載的潛在聚合清單。

.. 寫下要將工作負載移到的聚合的名稱。


. 從接收事件的節點中辨識高效能工作負載：
+
.. 返回活動的「活動」詳細資訊頁面。
.. 在「受影響的磁碟區」欄位中，按一下第一個節點的捲數連結。
+
效能：所有磁碟區視圖顯示該節點上磁碟區的篩選清單。

.. 按一下「*總容量*」列，依已指派的最大空間對磁碟區進行排序。
+
這提供了您可能想要移動的潛在磁碟區的清單。

.. 記下要移動的磁碟區的名稱以及它們所在的目前聚合的名稱。
.. 針對此事件的第二個節點執行步驟 4c 和 4d，以確定您想要從該節點移動的可能的磁碟區。


. 將磁碟區移至您確定為在新節點上具有最大可用性能容量的聚合。
+
您可以使用ONTAP System Manager、 OnCommand Workflow Automation、 ONTAP指令或這些工具的組合來執行行動操作。



幾天后，您可以檢查是否從該節點或聚合接收到相同類型的事件。
