---
permalink: performance-checker/task_respond_to_system_defined_node_resources_overutilized.html 
sidebar: sidebar 
keywords: node, resources, overutilized, performance, events 
summary: 當單一節點的運作超出其運作效率界限時，Unified Manager 會產生節點資源過度利用警告事件，因此可能會影響工作負載延遲。這些系統定義的事件提供了在許多工作負載受到延遲影響之前糾正潛在效能問題的機會。 
---
= 響應節點資源過度利用的效能事件
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
當單一節點的運作超出其運作效率界限時，Unified Manager 會產生節點資源過度利用警告事件，因此可能會影響工作負載延遲。這些系統定義的事件提供了在許多工作負載受到延遲影響之前糾正潛在效能問題的機會。

.開始之前
* 您必須具有操作員、應用程式管理員或儲存管理員角色。
* 必須有新的或過時的表演事件。


Unified Manager 透過尋找效能容量使用率超過 100% 且持續超過 30 分鐘的節點，產生違反節點資源過度利用策略的警告事件。

您可以使用 System Manager 或ONTAP指令來修正此類效能問題，包括下列任務：

* 建立並應用 QoS 策略到任何過度使用系統資源的磁碟區或 LUN
* 降低已套用工作負載的策略群組的 QoS 最大吞吐量限制
* 將工作負載移動到不同的聚合或節點
* 透過向節點添加磁碟或升級到具有更快 CPU 和更多 RAM 的節點來增加容量


.步驟
. 顯示*活動詳情*頁面以查看活動的資訊。
. 查看*描述*，其中描述了導致該事件的閾值違規。
+
例如，訊息「`Perf.  simple-02 上的容量使用值為 139%，已觸發警告事件，以識別資料處理單元中的潛在效能問題。 「」表示節點 simple-02 上的效能容量已過度使用，並影響節點效能。

. 在「系統診斷」部分下，查看三個圖表：一個用於節點上使用的效能容量，一個用於頂級工作負載使用的平均儲存 IOPS，一個用於頂級工作負載的延遲。以這種方式排列，您可以看到哪些工作負載是導致節點延遲的原因。
+
您可以將遊標移到 IOPS 圖表上來查看哪些工作負載應用了 QoS 策略，哪些工作負載沒有應用。

. 在「建議的操作」部分下，查看建議並確定應執行哪些操作以避免工作負載延遲增加。
+
如果需要，請按一下「幫助」按鈕以查看有關您可以執行的建議操作的更多詳細信息，以嘗試解決效能事件。


