---
permalink: performance-checker/task_create_user_defined_performance_threshold_policies.html 
sidebar: sidebar 
keywords: create, user-defined, performance, threshold, policies 
summary: 您可以為儲存物件建立效能閾值策略，以便在效能計數器超過特定值時發送通知。事件通知表明叢集正在經歷效能問題。 
---
= 建立使用者定義的效能閾值策略
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以為儲存物件建立效能閾值策略，以便在效能計數器超過特定值時發送通知。事件通知表明叢集正在經歷效能問題。

.開始之前
您必須具有應用程式管理員角色。

您可以透過在「建立效能閾值策略」頁面上輸入閾值來建立效能閾值策略。您可以透過定義此頁面中的所有策略值來建立新策略，也可以複製現有策略並變更副本中的值（稱為_複製_）。

有效閾值為數字 0.001 到 10,000,000、百分比 0.001-100 和效能容量使用百分比 0.001-200。

[NOTE]
====
當前版本提供了閾值，當計數器值超過閾值設定時會發送事件。您無法設定在計數器值低於閾值設定時發送事件的閾值。

====
.步驟
. 在左側導覽窗格中，選擇「*事件閾值*」>「*效能*」。
+
將顯示“效能閾值”頁面。

. 根據您是想建立新策略還是想克隆類似策略並修改克隆版本來點擊相應的按鈕。
+
|===
| 到... | 點擊... 


 a| 
建立新策略
 a| 
*創造*



 a| 
克隆現有策略
 a| 
選擇現有策略並點擊*克隆*

|===
+
進入「建立效能閾值策略」或「複製效能閾值策略」頁面。

. 透過指定要為特定儲存物件設定的效能計數器閾值來定義閾值策略：
+
.. 選擇儲存物件類型並為策略指定名稱和描述。
.. 選擇要追蹤的效能計數器並指定定義警告和嚴重事件的限制值。
+
您必須定義至少一個警告限值或一個臨界值。您不需要定義兩種類型的限制。

.. 如果需要，請選擇一個輔助效能計數器，並指定警告和嚴重事件的限制值。
+
包括輔助計數器要求兩個計數器都超過限制值，然後才會突破閾值並報告事件。只能使用組合策略來配置某些物件和計數器。

.. 選擇必須突破限制值才會發送事件的持續時間。


+
複製現有策略時，必須為該策略輸入新名稱。

. 按一下“*儲存*”以儲存該策略。
+
您將返回到“效能閾值”頁面。頁面頂部的成功訊息確認閾值策略已創建，並提供該物件類型的庫存頁面鏈接，以便您可以立即將新策略應用於儲存物件。



如果此時您想將新的閾值策略套用至儲存對象，您可以按一下「立即前往 object_type」連結前往「庫存」頁面。
