---
permalink: performance-checker/task_respond_to_cluster_imbalance_performance_events.html 
sidebar: sidebar 
keywords: cluster, imbalance, performance, events 
summary: 當叢集中某個節點的負載遠高於其他節點時，Unified Manager 會產生叢集不平衡警告事件，因此可能會影響工作負載延遲。這些系統定義的事件提供了在許多工作負載受到延遲影響之前糾正潛在效能問題的機會。 
---
= 響應集群不平衡效能事件
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
當叢集中某個節點的負載遠高於其他節點時，Unified Manager 會產生叢集不平衡警告事件，因此可能會影響工作負載延遲。這些系統定義的事件提供了在許多工作負載受到延遲影響之前糾正潛在效能問題的機會。

.開始之前
您必須具有操作員、應用程式管理員或儲存管理員角色。

Unified Manager 透過比較叢集中所有節點的效能容量使用值來查看任何節點之間是否存在 30% 的負載差異，從而為叢集不平衡閾值策略違規產生警告事件。

這些步驟可協助您識別以下資源，以便您可以將高效能工作負載移至使用率較低的節點：

* 同一叢集中利用率較低的節點
* 新節點上利用率最低的聚合
* 當前節點上效能最高的捲


.步驟
. 顯示*事件*詳細資訊頁面以查看有關該事件的資訊。
. 查看*描述*，其中描述了導致該事件的閾值違規。
+
例如，訊息「`效能容量使用計數器指示叢集 Dallas-1-8 上的節點之間的負載差異為 62%，並根據系統閾值 30% 觸發了警告事件`」表示其中一個節點上的效能容量被過度使用並影響節點效能。

. 查看「*建議的操作*」中的文本，將高效能磁碟區從具有高效能容量使用值的節點移至具有最低效能容量使用值的節點。
. 確定效能容量使用值最高和最低的節點：
+
.. 在「事件資訊」部分中，按一下來源叢集的名稱。
.. 在「叢集/效能摘要」頁面中，按一下「管理物件」區域中的「節點」。
.. 在「*節點*」庫存頁面中，按「已使用效能容量*」欄位對節點進行排序。
.. 確定效能容量使用值最高和最低的節點並記下這些名稱。


. 在確定具有最高效能容量使用值的節點上使用最多 IOPS 的磁碟區：
+
.. 點選效能容量使用值最高的節點。
.. 在*節點/效能資源管理器*頁面中，從*檢視和比較*選單中選擇*此節點上的聚合*。
.. 按一下具有最高效能容量使用值的聚合。
.. 在*聚合/效能資源管理器*頁面中，從*檢視和比較*選單中選擇*此聚合上的磁碟區*。
.. 將磁碟區依 *IOPS* 欄位排序，並記下使用最多 IOPS 的磁碟區的名稱以及該磁碟區所在聚合的名稱。


. 確定具有最低效能容量使用值的節點上利用率最低的聚合：
+
.. 按一下「*儲存*」>「*聚合*」以顯示「*聚合*」庫存頁面。
.. 選擇*效能：所有聚合*視圖。
.. 點擊「*過濾器*」按鈕並新增一個過濾器，其中「`Node`」等於您在步驟 4 中記下的具有最低效能容量使用值的節點的名稱。
.. 記下具有最低效能容量使用值的聚合的名稱。


. 將磁碟區從過載節點移至您確定為在新節點上利用率較低的聚合。
+
您可以使用ONTAP System Manager、 OnCommand Workflow Automation、 ONTAP指令或這些工具的組合來執行行動操作。



幾天后，檢查您是否從該叢集收到相同的叢集不平衡事件。
