---
permalink: performance-checker/task_move_workloads_to_another_node_in_different_ha_pair.html 
sidebar: sidebar 
keywords: move, workloads, another, node, different, ha pair 
summary: 您可以使用 Unified Manager 來協助識別不同 HA 對中節點上的聚合，該聚合的繁忙程度低於您的工作負載目前正在執行的 HA 對。然後，您可以將選定的磁碟區移至新 HA 對上的聚合。將高效能工作負載移至較不繁忙的節點上的聚合體，可使兩個節點上的工作負載更有效率地執行。 
---
= 將工作負載移至不同 HA 對中的另一個節點
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以使用 Unified Manager 來協助識別不同 HA 對中節點上的聚合，該聚合的繁忙程度低於您的工作負載目前正在執行的 HA 對。然後，您可以將選定的磁碟區移至新 HA 對上的聚合。將高效能工作負載移至較不繁忙的節點上的聚合體，可使兩個節點上的工作負載更有效率地執行。

.開始之前
* 您必須具有操作員、應用程式管理員或儲存管理員角色。
* 您的叢集必須至少包含兩個 HA 對；如果您的叢集中只有一個 HA 對，則無法使用此修復程序。
* 您必須記錄 HA 對中目前存在效能問題的兩個節點的名稱。
* 您必須記錄節點接收效能事件的日期和時間。
* Unified Manager 必須收集並分析一個月或更長時間的效能資料。


這些步驟可協助您識別以下資源，以便您可以將高效能工作負載移至不同 HA 對上使用率較低的節點：

* 在同一集群上不同 HA 對中利用率較低的節點
* 新節點上利用率最低的聚合
* 當前節點上效能最高的捲


.步驟
. 辨識屬於同一叢集上不同 HA 對的節點：
+
.. 在左側導覽窗格中，按一下“*儲存*”>“*叢集*”，然後從“檢視”功能表中選擇“*效能*”>“*所有叢集*”。
+
效能：顯示所有叢集視圖。

.. 按一下目前叢集的「*節點數*」欄位中的數字。
+
將顯示“效能：所有節點”視圖。

.. 記下與目前存在效能問題的 HA 對不同的 HA 對中的節點的名稱。


. 確定新 HA 對中使用率最低的節點：
+
.. 點選「*利用率*」欄位依利用率最低的順序對節點進行排序。
+
您還可以識別具有最大*可用容量*的節點。這提供了您可能想要將工作負載移動到的潛在節點的清單。

.. 寫下您想要將工作負載移動到的節點的名稱。


. 確定新節點上利用率最低的聚合：
+
.. 在左側導覽窗格中，按一下“*儲存*”>“*聚合*”，然後從“檢視”功能表中選擇“*效能*”>“*所有聚合*”。
+
將顯示“效能：所有聚合”視圖。

.. 點擊“*過濾*”，從左側下拉選單中選擇“*節點*”，在文字欄位中輸入節點的名稱，然後點擊“*套用篩選器*”。
+
效能：所有聚合視圖將重新顯示此節點上可用的聚合清單。

.. 按一下「*使用率*」列，依利用率最低的順序對聚合進行排序。
+
您還可以識別那些具有最大*可用容量*的聚合。這提供了您可能想要移動工作負載的潛在聚合清單。

.. 寫下要將工作負載移到的聚合的名稱。


. 從接收事件的節點中辨識高效能工作負載：
+
.. 返回活動的「活動」詳細資訊頁面。
.. 在「受影響的磁碟區」欄位中，按一下第一個節點的捲數連結。
+
效能：所有磁碟區視圖顯示該節點上磁碟區的篩選清單。

.. 按一下「*總容量*」列，依已指派的最大空間對磁碟區進行排序。
+
這提供了您可能想要移動的潛在磁碟區的清單。

.. 記下要移動的磁碟區的名稱以及它們所在的目前聚合的名稱。
.. 針對此事件的第二個節點執行步驟 4c 和 4d，以確定您想要從該節點移動的可能的磁碟區。


. 將磁碟區移至您確定為新節點上利用率較低的聚合。
+
您可以使用ONTAP System Manager、 OnCommand Workflow Automation、 ONTAP指令或這些工具的組合來執行行動操作。



幾天后，檢查您是否從該節點或聚合接收到相同類型的事件。
