---
permalink: performance-checker/task_configure_connection_between_um_server_and_external_data_provider.html 
sidebar: sidebar 
keywords: configuring, connection, unified manager, server, external, data, provider 
summary: Unified Manager 可以將叢集效能資料傳送到外部伺服器。您可以指定傳送的統計資料的類型以及傳送資料的間隔。 
---
= 設定從 Unified Manager 伺服器到外部資料提供者的連接
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Unified Manager 可以將叢集效能資料傳送到外部伺服器。您可以指定傳送的統計資料的類型以及傳送資料的間隔。

.開始之前
* 您必須擁有授權登入 Unified Manager 伺服器維護控制台的使用者 ID。
* 您必須具有有關外部資料提供者的以下資訊：
+
** 伺服器名稱或 IP 位址（IPv4 或 IPv6）
** 伺服器預設連接埠（如果不使用預設連接埠2003）


* 您必須設定遠端伺服器和第三方軟體，以便它可以從 Unified Manager 伺服器接收統計資料。
* 您必須知道要傳送哪一組統計資料：
+
** PERFORMANCE_INDICATOR：效能監視器統計資訊
** RESOURCE_UTILIZATION：資源利用率和效能監視器統計資料
** DRILL_DOWN：所有統計數據


* 您必須知道傳輸統計資料的時間間隔：5、10 或 15 分鐘
+
預設情況下，Unified Manager 每隔 5 分鐘收集一次統計資料。如果將傳輸間隔設定為 10（或 15）分鐘，則每次傳輸期間發送的資料量是使用預設 5 分鐘間隔時的兩倍（或三倍）。

+
[NOTE]
====
如果將 Unified Manager 效能收集間隔變更為 10 或 15 分鐘，則必須變更傳輸間隔，使其等於或大於 Unified Manager 收集間隔。

====


您可以設定一台 Unified Manager 伺服器和一台外部資料提供者伺服器之間的連線。

.步驟
. 以維護使用者身分登入 Unified Manager 伺服器的維護控制台。
+
顯示 Unified Manager 維護控制台提示。

. 在維護控制台中，輸入*外部資料提供者*選單選項的編號。
+
顯示外部伺服器連線選單。

. 鍵入「*新增/修改伺服器連線*」選單選項的編號。
+
顯示目前伺服器連線資訊。

. 出現提示時，輸入 `*y*`繼續。
. 出現提示時，輸入目標伺服器的 IP 位址或名稱以及伺服器連接埠資訊（如果與預設連接埠 2003 不同）。
. 出現提示時，輸入 `*y*`驗證您輸入的資訊是否正確。
. 按任意鍵返回外部伺服器連線選單。
. 鍵入「修改伺服器設定」選單選項的編號。
+
顯示目前伺服器設定資訊。

. 出現提示時，輸入 `*y*`繼續。
. 出現提示時，輸入要傳送的統計資料類型、傳送統計資料的時間間隔以及是否要立即啟用統計資料的傳輸：
+
|===
| 為了.. | 進入... 


 a| 
統計組ID
 a| 
`*0*`- PERFORMANCE_INDICATOR（預設）

`*1*`- 資源利用率

`*2*`- DRILL_DOWN



 a| 
供應商標籤
 a| 
外部伺服器上儲存統計資訊的資料夾的描述性名稱。  “`netapp-performance`” 是預設名稱，但您可以輸入其他值。

透過使用點分符號，您可以定義分層資料夾結構。例如，透過輸入 `*stats.performance.netapp*`統計資料位於 *stats* > *performance* > *netapp*。



 a| 
傳輸間隔
 a| 
`*5*`(預設), `*10*` ， 或者 `*15*`分分鐘



 a| 
啟用/停用
 a| 
`*0*`- 停用

`*1*`- 啟用（預設）

|===
. 出現提示時，輸入 `*y*`驗證您輸入的資訊是否正確。
. 按任意鍵返回外部伺服器連線選單。
. 類型 `*x*`退出維護控制台。


設定連線後，選定的效能資料將依照您指定的時間間隔傳送到目標伺服器。指標需要幾分鐘才會開始出現在外部工具中。您可能需要刷新瀏覽器才能看到指標層次結構中的新指標。
