---
permalink: performance-checker/task_move_workloads_to_different_aggregate.html 
sidebar: sidebar 
keywords: move, workloads, different, aggregate 
summary: 您可以使用 Unified Manager 來協助識別比工作負載目前所在聚合繁忙程度較低的聚合，然後您可以將選定的磁碟區或 LUN 移至該聚合。將高效能工作負載移至較不繁忙的聚合體或啟用了快閃記憶體的聚合體，可使工作負載更有效率地運作。 
---
= 將工作負載移至不同的聚合
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以使用 Unified Manager 來協助識別比工作負載目前所在聚合繁忙程度較低的聚合，然後您可以將選定的磁碟區或 LUN 移至該聚合。將高效能工作負載移至較不繁忙的聚合體或啟用了快閃記憶體的聚合體，可使工作負載更有效率地運作。

.開始之前
* 您必須具有操作員、應用程式管理員或儲存管理員角色。
* 您必須記錄目前存在效能問題的聚合的名稱。
* 您必須記錄聚合接收事件的日期和時間。
* Unified Manager 必須收集並分析一個月或更長時間的效能資料。


這些步驟可協助您識別以下資源，以便您可以將高效能工作負載移至使用率較低的聚合：

* 同一集群中利用率較低的聚合
* 目前聚合中性能最高的捲


.步驟
. 確定集群中利用率最低的聚合：
+
.. 在「*事件*詳細資料」頁面上，按一下聚合所在叢集的名稱。
+
集群詳細資訊顯示在效能/集群登陸頁面中。

.. 在「*摘要*」頁面上，按一下「*管理物件*」窗格中的「*聚合*」。
+
顯示此叢集上的聚合清單。

.. 按一下「*使用率*」列，依利用率最低的順序對聚合進行排序。
+
您還可以識別那些具有最大*可用容量*的聚合。這提供了您可能想要移動工作負載的潛在聚合清單。

.. 寫下要將工作負載移到的聚合的名稱。


. 從接收事件的聚合中辨識高效能磁碟區：
+
.. 點選存在效能問題的聚合。
+
聚合詳細資訊顯示在效能/聚合資源管理器頁面中。

.. 從*時間範圍*選擇器中，選擇*過去 30 天*，然後按一下*套用範圍*。
+
這使您能夠查看比預設 72 小時更長的效能歷史記錄週期。您想要移動持續使用大量資源的捲，而不僅僅是在過去 72 小時內。

.. 從*檢視和比較*控制項中，選擇*此聚合上的磁碟區*。
+
顯示此聚合上的FlexVol磁碟區和FlexGroup組成磁碟區的清單。

.. 按最高 MB/s 對磁碟區進行排序，然後按最高 IOPS 對磁碟區進行排序，以查看效能最高的磁碟區。
.. 寫下要移動到不同聚合的磁碟區的名稱。


. 將高效能磁碟區移至您確定為利用率較低的聚合。
+
您可以使用ONTAP System Manager、 OnCommand Workflow Automation、 ONTAP指令或這些工具的組合來執行行動操作。



幾天后，檢查您是否從該節點或聚合接收到相同類型的事件。
