---
permalink: performance-checker/task_respond_to_system_defined_qos_policy_group_performance_event.html 
sidebar: sidebar 
keywords: qos, policy, group, performance, events 
summary: 當工作負載吞吐量（IOPS、IOPS/TB 或 MBps）超過定義的ONTAP QoS 策略設定且工作負載延遲受到影響時，Unified Manager 會產生 QoS 策略警告事件。這些系統定義的事件提供了在許多工作負載受到延遲影響之前糾正潛在效能問題的機會。 
---
= 回應 QoS 策略群組效能事件
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
當工作負載吞吐量（IOPS、IOPS/TB 或 MBps）超過定義的ONTAP QoS 策略設定且工作負載延遲受到影響時，Unified Manager 會產生 QoS 策略警告事件。這些系統定義的事件提供了在許多工作負載受到延遲影響之前糾正潛在效能問題的機會。

.開始之前
* 您必須具有操作員、應用程式管理員或儲存管理員角色。
* 必須有新的、公認的或過時的績效事件。


當工作負載吞吐量在前一小時的每個效能收集期間超過定義的 QoS 策略設定時，Unified Manager 會產生違反 QoS 策略的警告事件。在每個收集期間，工作負載吞吐量可能僅在短時間內超過 QoS 閾值，但 Unified Manager 在圖表上僅顯示收集期間的「平均」吞吐量。因此，您可能會收到 QoS 事件，而工作負載的吞吐量可能尚未超過圖表​​中顯示的策略閾值。

您可以使用 System Manager 或ONTAP指令來管理原則群組，包括下列任務：

* 為工作負載建立新的策略群組
* 在策略群組中新增或刪除工作負載
* 在策略組之間移動工作負載
* 更改策略群組的吞吐量限制
* 將工作負載移動到不同的聚合或節點


.步驟
. 顯示*活動詳情*頁面以查看活動的資訊。
. 查看*描述*，其中描述了導致該事件的閾值違規。
+
例如，訊息「`vol1_NFS1 上的 IOPS 值為 1,352 IOPS 已觸發警告事件以識別工作負載的潛在效能問題`」表示在磁碟區 vol1_NFS1 上發生了 QoS 最大 IOPS 事件。

. 請查看「事件資訊」部分，以了解有關事件發生時間和事件持續時間的更多詳細資訊。
+
此外，對於共用 QoS 策略吞吐量的磁碟區或 LUN，您可以看到消耗最多 IOPS 或 MBps 的前三個工作負載的名稱。

. 在「系統診斷」部分下，查看兩個圖表：一個用於總平均 IOPS 或 MBps（取決於事件），另一個用於延遲。透過這種方式安排，您可以看到當工作負載接近 QoS 最大限制時哪些叢集元件對延遲的影響最大。
+
對於共用 QoS 策略事件，吞吐量圖表中顯示前三個工作負載。如果有三個以上的工作負載共享 QoS 策略，則其他工作負載將被加入到「其他工作負載」類別中。此外，延遲圖表顯示 QoS 策略中所有工作負載的平均延遲。

+
請注意，對於自適應 QoS 策略事件，IOPS 和 MBps 圖表顯示ONTAP根據磁碟區大小從指派的 IOPS/TB 閾值策略轉換的 IOPS 或 MBps 值。

. 在「建議的操作」部分下，查看建議並確定應執行哪些操作以避免工作負載延遲增加。
+
如果需要，請按一下「幫助」按鈕以查看有關您可以執行的建議操作的更多詳細信息，以嘗試解決效能事件。


