---
permalink: performance-checker/task_move_workloads_to_different_node.html 
sidebar: sidebar 
keywords: move, workloads, different, node 
summary: 您可以使用 Unified Manager 來協助識別比目前執行工作負載的節點繁忙程度較低的其他節點上的聚合，然後您可以將選定的磁碟區移至該聚合。將高效能工作負載移至較不繁忙的節點上的聚合體，可使兩個節點上的工作負載更有效率地執行。 
---
= 將工作負載移至其他節點
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以使用 Unified Manager 來協助識別比目前執行工作負載的節點繁忙程度較低的其他節點上的聚合，然後您可以將選定的磁碟區移至該聚合。將高效能工作負載移至較不繁忙的節點上的聚合體，可使兩個節點上的工作負載更有效率地執行。

.開始之前
* 您必須具有操作員、應用程式管理員或儲存管理員角色。
* 您必須記錄目前存在效能問題的節點的名稱。
* 您必須記錄節點接收效能事件的日期和時間。
* Unified Manager 必須收集並分析一個月或更長時間的效能資料。


此流程可協助您識別以下資源，以便您可以將高效能工作負載移至使用率較低的節點：

* 在同一叢集中具有最大可用性能容量的節點
* 新節點上具有最大可用性能容量的聚合
* 當前節點上效能最高的捲


.步驟
. 確定叢集中具有最大可用性能容量的節點：
+
.. 在「事件詳情」頁面，按一下該節點所在叢集的名稱。
+
集群詳細資訊顯示在效能/集群登陸頁面中。

.. 在「*摘要*」標籤上，按一下「*管理物件*」窗格中的「*節點*」。
+
顯示該叢集上的節點清單。

.. 按一下「已使用的效能容量」列，以使用率最低的百分比對節點進行排序。
+
這提供了您可能想要將工作負載移動到的潛在節點的清單。

.. 寫下您想要將工作負載移動到的節點的名稱。


. 確定新節點上利用率最低的聚合：
+
.. 在左側導覽窗格中，按一下“*儲存*”>“*聚合*”，然後從“檢視”功能表中選擇“*效能*”>“*所有聚合*”。
+
將顯示“效能：所有聚合”視圖。

.. 點擊“*過濾*”，從左側下拉選單中選擇“*節點*”，在文字欄位中輸入節點的名稱，然後點擊“*套用篩選器*”。
+
效能：所有聚合視圖將重新顯示此節點上可用的聚合清單。

.. 按一下「已使用的效能容量」列，以最少使用對聚合進行排序。
+
這提供了您可能想要移動工作負載的潛在聚合清單。

.. 寫下要將工作負載移到的聚合的名稱。


. 從接收事件的節點識別高效能工作負載：
+
.. 返回活動的「活動詳情」頁面。
.. 在「受影響的磁碟區」欄位中，按一下卷數的連結。
+
效能：所有磁碟區視圖顯示該節點上磁碟區的篩選清單。

.. 按一下「*總容量*」列，依已指派的最大空間對磁碟區進行排序。
+
這提供了您可能想要移動的潛在磁碟區的清單。

.. 記下要移動的磁碟區的名稱以及它們所在的目前聚合的名稱。


. 將磁碟區移至您確定為在新節點上具有最大可用性能容量的聚合。
+
您可以使用ONTAP System Manager、 OnCommand Workflow Automation、 ONTAP指令或這些工具的組合來執行行動操作。



幾天后，您可以檢查是否從該節點或聚合接收到相同類型的事件。
