---
permalink: storage-mgmt/concept_what_options_do_i_have_in_fix_it_button.html 
sidebar: sidebar 
keywords: fix it,fix all 
summary: 「管理操作」頁面為您提供了「修復」或「修復全部」按鈕，用於修復 Unified Manager 透過事件通知的問題。 
---
= 當我看到“修復”或“修復全部”按鈕時，我有哪些選項
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
管理操作頁面為您提供了「修復」或「修復全部」按鈕，用於修復 Unified Manager 透過事件通知的問題。

我們建議您根據需要點擊按鈕來解決問題。但是，如果您不確定是否要按照 Unified Manager 的建議解決問題，則可以執行下列操作：

|===
| 你想讓我做什麼？ | *行動* 


 a| 
讓 Unified Manager 修復所有已識別物件上的問題。
 a| 
點選“修復全部”按鈕。



 a| 
此時不要修復任何已識別物件的問題，並隱藏此管理操作，直到再次引發該事件。
 a| 
按一下向下箭頭，然後按一下「全部關閉」。



 a| 
僅修復部分已識別物件的問題。
 a| 
按一下管理操作的名稱以展開清單並顯示所有單獨的*修復*操作。然後按照修復或解除單一管理操作的步驟進行操作。

|===
|===
| 你想讓我做什麼？ | 行動 


 a| 
讓 Unified Manager 修復該問題。
 a| 
點選“修復”按鈕。



 a| 
此時請勿修復該問題並隱藏此管理操作，直到事件再次發生。
 a| 
按一下向下箭頭，然後按一下“*關閉*”。



 a| 
顯示此事件的詳細信息，以便您更好地了解問題。
 a| 
* 點擊“修復”按鈕並查看將在出現的對話方塊中套用的修復。
* 按一下向下箭頭，然後按一下「檢視事件詳情」以顯示事件詳情頁面。


如果您想修復該問題，請在任一結果頁面中按一下「修復它」。



 a| 
顯示此存儲對象的詳細信息，以便您更好地了解問題。
 a| 
按一下儲存物件的名稱可在「效能資源管理器」或「運作狀況詳細資料」頁面中顯示詳細資料。

|===
在某些情況下，修復會反映在接下來的 15 分鐘配置輪詢中。在其他情況下，可能需要花費數小時來驗證配置變更並讓事件過時。

若要查看已完成或正在進行的管理操作列表，請按一下篩選器圖示並選擇*已完成*或*進行中*。

修復所有操作都以串行方式運行，因此當您查看*進行中*面板時，某些物件的狀態為*進行中*，而其他物件的狀態為*已安排*；這表示它們仍在等待實施。
