---
permalink: storage-mgmt/concept_monitor_vms.html 
sidebar: sidebar 
keywords: monitor, virtual, machines, view, summary, topology, expand 
summary: '對於虛擬機器 (VM) 應用程式上的任何延遲問題，您可能需要監控虛擬機器以分析和排除原因。當虛擬機器的 vCenter Server 和託管虛擬機器儲存的ONTAP叢集新增至 Unified Manager 時，虛擬機器可用。' 
---
= 監控虛擬機
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
對於虛擬機器 (VM) 應用程式上的任何延遲問題，您可能需要監控虛擬機器以分析和排除原因。當虛擬機器的 vCenter Server 和託管虛擬機器儲存的ONTAP叢集新增至 Unified Manager 時，虛擬機器可用。

您可以在 *VMWARE* > > *虛擬機器* 頁面上看到虛擬機器的詳細資訊。顯示可用性、狀態、已使用和已分配容量、網路延遲以及虛擬機器、資料儲存區和主機的 IOPS 和延遲等資訊。對於支援多個資料儲存區的虛擬機，網格顯示延遲最嚴重的資料儲存區的指標，星號圖示 (*) 表示其他資料儲存區。如果按一下該圖標，則會顯示附加資料儲存的指標。其中一些列不可用於排序和過濾。

[NOTE]
====
要查看虛擬機器及其詳細信息，必須完成ONTAP叢集的發現（輪詢或指標收集）。如果從 Unified Manager 中刪除集群，則在下一個發現週期之後，虛擬機器將不再可用。

====
從此頁面，您還可以查看虛擬機器的詳細拓撲，顯示與虛擬機器相關的元件，例如連接到它的主機、虛擬磁碟和資料儲存。拓樸視圖會依照下列順序顯示特定層中的底層元件：*虛擬磁碟* > *VM* > *主機* > *網路* > *資料儲存* > *VMDK*。

您可以從拓撲角度確定 I/O 路徑和元件級延遲，並確定儲存是否是導致效能問題的原因。拓撲的摘要視圖顯示 I/O 路徑，並反白顯示具有 IOPS 和延遲問題的元件，以便您決定故障排除步驟。您還可以獲得拓撲的擴展視圖，該視圖分別描述每個組件以及該組件的延遲。您可以選擇一個元件來決定透過各層突出顯示的 I/O 路徑。



== 查看摘要拓撲

若要透過查看摘要拓撲中的虛擬機器來確定效能問題：

. 前往 *VMWARE* > *虛擬機器*。
. 在搜尋框中輸入虛擬機器名稱來搜尋虛擬機器。您也可以透過點擊“*過濾器*”按鈕根據特定條件過濾搜尋結果。但是，如果您找不到您的虛擬機，請確保已新增並發現對應的 vCenter Server。
+
[NOTE]
====
vCenter Server 允許在 vSphere 實體（例如 VM、群集、資料儲存區、資料夾或檔案）的名稱中使用特殊字元（例如 %, &、*、$、#、@、!、\、/、:、*、?、"`、<、>、|、;、'）。 VMware vCenter Server 和 ESX/ESXi Server 不會轉義顯示名稱中使用的特殊字元。但是，在 Unified Manager 中處理該名稱時，顯示方式會有所不同。例如，名為 `%$VC_AIQUM_clone_191124%`在 vCenter Server 中顯示為 `%25$VC_AIQUM_clone_191124%25`在統一管理器中。當您查詢名稱中包含特殊字元的虛擬機器時，必須記下此問題。

====
. 檢查虛擬機器的狀態。 VM 狀態從 vCenter Server 檢索。有以下狀態可用。有關這些狀態的更多信息，請參閱 VMware 文件。
+
** 普通的
** 警告
** 警報
** 未受監控
** 未知


. 按一下虛擬機器旁的向下箭頭以查看運算、網路和儲存層元件的拓樸摘要檢視。存在延遲問題的節點被突出顯示。摘要視圖顯示組件的最差延遲。例如，如果虛擬機器有多個虛擬磁碟，則此視圖顯示所有虛擬磁碟中延遲最差的虛擬磁碟。
. 若要分析資料儲存在一段時間內的延遲和吞吐量，請按一下資料儲存物件圖示頂部的「*工作負載分析器*」按鈕。您轉到工作負載分析頁面，您可以在其中選擇時間範圍並查看資料儲存的效能圖表。有關工作負載分析器的更多信息，請參閱_使用工作負載分析器排除工作負載故障_。




== 查看擴充拓撲

您可以透過查看虛擬機器的擴展拓撲來深入了解每個組件。

.步驟
. 從摘要拓撲視圖中，按一下*展開拓撲*。您可以分別查看每個組件的詳細拓撲以及每個物件的延遲數。如果某個類別中有多個節點（例如資料儲存或 VMDK 中的多個節點），則延遲最差的節點將以紅色突出顯示。
. 若要檢查特定物件的 IO 路徑，請按一下該物件以查看 IO 路徑和對應的對應。例如，要查看虛擬磁碟的映射，請按一下虛擬磁碟以查看其與相應 VMDK 的突出顯示的映射。如果這些組件的效能出現滯後，您可以從ONTAP收集更多資料並解決問題。
+
[NOTE]
====
未報告 VMDK 的指標。在拓樸中，僅顯示 VMDK 名稱，而不顯示指標。

====


*相關資訊*

link:../performance-checker/concept_troubleshooting_workloads_using_workload_analyzer.html["使用工作負載分析器排除工作負載故障"]
