---
permalink: storage-mgmt/concept_manage_storage_efficiency_policies.html 
sidebar: sidebar 
keywords: manage, storage, efficiency, policies, guidelines, create, custom 
summary: '儲存效率策略 (SEP) 可讓您定義工作負載的儲存效率特性。您可以在最初建立工作負載時將 SEP 指派給工作負載，也可以在之後透過編輯工作負載來指派 SEP。' 
---
= 管理儲存效率策略
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
儲存效率策略 (SEP) 可讓您定義工作負載的儲存效率特性。您可以在最初建立工作負載時將 SEP 指派給工作負載，也可以在之後透過編輯工作負載來指派 SEP。

儲存效率包括使用精簡配置、重複資料刪除和資料壓縮等技術來提高儲存利用率並降低儲存成本。在創建 SEP 時，您可以單獨或一起使用這些節省空間的技術來實現最大的儲存效率。當您將策略與儲存工作負載關聯時，指定的策略設定就會指派給它們。  Unified Manager 讓您能夠指派系統定義和使用者定義的 SEP，以最佳化資料中心的儲存資源。

Unified Manager 提供兩個系​​統定義的 SEP：高和低。這些 SEP 適用於資料中心中的大多數儲存工作負載，但是，如果系統定義的 SEP 無法滿足您的要求，您可以建立自己的策略。

您無法修改系統定義或目前指派給工作負載的 SEP。您無法刪除已指派給工作負載的 SEP，或它是唯一可用的 SEP。

儲存效率策略頁面列出了可用的 SEP，並允許您新增、編輯和刪除自訂 SEP。此頁面顯示以下資訊：

|===
| 場地 | 描述 


 a| 
Name
 a| 
SEP 的名稱。



 a| 
類型
 a| 
該策略是系統定義的還是使用者定義的。



 a| 
太空儲備
 a| 
該卷是精簡配置的還是厚配置的。



 a| 
重複資料刪除
 a| 
工作負載上是否啟用了重複資料刪除：

* 內嵌：重複資料刪除在工作負載寫入時發生
* 背景：重複資料刪除發生在工作負載中
* 停用：工作負載上停用重複資料刪除




 a| 
壓縮
 a| 
工作負載是否啟用資料壓縮：

* 內嵌：資料壓縮在工作負載寫入時進行
* 背景：資料壓縮發生在工作負載中
* 停用：工作負載上停用資料壓縮




 a| 
工作負載
 a| 
已分配 SEP 的儲存工作負載數量

|===


== 建立自訂儲存效率策略的指南

如果現有的 SEP 不符合您的儲存工作負載的策略要求，您可以建立自訂 SEP。但是，建議您嘗試將系統定義的 SEP 用於儲存工作負載，並且僅在必要時建立自訂 SEP。

您可以在「所有工作負載」頁面和「磁碟區/運行狀況詳細資料」頁面中查看指派給工作負載的 SEP。您可以在儀表板上的容量面板和容量：所有叢集視圖中查看基於這些儲存效率的叢集級資料縮減率（不含 Snapshot 副本）。
