---
permalink: storage-mgmt/concept_monitor_and_manage_clusters_from_dashboard.html 
sidebar: sidebar 
keywords: monitor, manage, clusters, dashboard 
summary: 儀表板提供受監控ONTAP系統目前運作狀況的累積概覽資訊。儀表板提供“面板”，使您能夠評估正在監控的叢集的整體容量、效能和安全健康狀況。 
---
= 從儀表板監控和管理集群
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
儀表板提供受監控ONTAP系統目前運作狀況的累積概覽資訊。儀表板提供“面板”，使您能夠評估正在監控的叢集的整體容量、效能和安全健康狀況。

此外，您可以直接從 Unified Manager 使用者介面修復某些ONTAP問題，而不必使用ONTAP System Manager 或ONTAP CLI。

在儀表板頂部，您可以選擇面板是否顯示所有受監控叢集的資訊或單一叢集的資訊。您可以先查看所有叢集的狀態，然後在想要查看詳細資訊時深入到單一叢集。

[NOTE]
====
根據您的配置，下面列出的某些面板可能不會出現在頁面上。

====
|===
| 面板 | 描述 


 a| 
管理措施
 a| 
當 Unified Manager 可以診斷並確定問題的單一解決方案時，這些解決方案將顯示在此面板中，並帶有 *修復* 按鈕。



 a| 
容量
 a| 
顯示本地層和雲層的總容量和已使用容量，以及本地容量達到上限的天數。



 a| 
性能容量
 a| 
顯示每個群集的效能容量值以及達到效能容量上限的天數。



 a| 
工作負載 IOPS
 a| 
顯示目前在特定 IOPS 範圍內運作的工作負載總數。



 a| 
工作負載效能
 a| 
顯示分配給每個定義的效能服務等級的符合和不符合的工作負載總數。



 a| 
安全
 a| 
顯示合規或不合規的群集數量、合規或不合規的 SVM 數量以及加密或未加密的磁碟區數量。



 a| 
保護
 a| 
顯示受 SVM-DR 關係保護的儲存虛擬機器的數量、受SnapMirror關係保護的磁碟區的數量、受 Snapshot 保護的磁碟區的數量以及受MetroCluster保護的叢集的數量。



 a| 
使用概述
 a| 
顯示依最高 IOPS、最高吞吐量（MBps）或最高已以實體容量排序的叢集。

|===