---
permalink: storage-mgmt/concept_workloads_dashboard.html 
sidebar: sidebar 
keywords: workloads, overview, data center, sections 
summary: '工作負載表示儲存物件（例如磁碟區或 LUN）的輸入/輸出 (I/O) 操作。儲存的配置方式取決於預期的工作負載要求。只有當有流量往返於儲存物件後， Active IQ Unified Manager才會追蹤工作負載統計資料。例如，使用者開始使用資料庫或電子郵件應用程式後，即可獲得工作負載 IOPS 和延遲值。' 
---
= 工作負載概述
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
工作負載表示儲存物件（例如磁碟區或 LUN）的輸入/輸出 (I/O) 操作。儲存的配置方式取決於預期的工作負載要求。只有當有流量往返於儲存物件後， Active IQ Unified Manager才會追蹤工作負載統計資料。例如，使用者開始使用資料庫或電子郵件應用程式後，即可獲得工作負載 IOPS 和延遲值。

「工作負載」頁面顯示由 Unified Manager 管理的ONTAP叢集的儲存工作負載摘要。它提供了符合效能服務水準的儲存工作負載以及不符合效能服務水準的儲存工作負載的累積概覽資訊。它還使您能夠評估整個資料中心叢集的總容量、可用容量和已使用容量和效能（IOPS）。

[NOTE]
====
建議您評估不符合要求、不可用或不受任何效能服務等級管理的儲存工作負載的數量，並採取必要的措施來確保其一致性、容量使用率和 IOPS。

====
工作負載頁麵包含以下兩個部分：

* 工作負載概覽：提供 Unified Manager 管理的ONTAP叢集上的儲存工作負載數量的概覽。
* 資料中心概覽：提供資料中心內儲存工作負載的容量和 IOPS 概覽。相關數據顯示在資料中心層級和個人層級。




== 工作負載概述​​部分

工作負載概覽部分提供了儲存工作負載的累積概覽資訊。儲存工作負載的狀態會根據已指派和未指派的效能服務等級顯示。

* *已指派*：針對已指派效能服務等級的儲存工作負載報告下列狀態：
+
** *符合*：儲存工作負載的效能取決於指派給它們的效能服務等級。如果儲存工作負載在相關效能服務等級中定義的閾值延遲範圍內，則將其標記為「符合」。符合要求的工作負載以藍色標示。
** *不符合*：在效能監控期間，如果儲存工作負載延遲超過相關效能服務等級中定義的閾值延遲，則儲存工作負載將被標記為「不符合」。不符合要求的工作負載以橘色標示。
** *不可用*：如果儲存工作負載處於離線狀態，或者相應的叢集無法訪問，則會被標記為「不可用」。不可用的工作負載以紅色標示。


* *未分配*：未分配效能服務等級的儲存工作負載被報告為「未分配」。該數字由資訊圖示傳達。


總工作負載數是已分配工作負載和未分配工作負載的總和。

您可以按一下此部分顯示的工作負載總數，然後在工作負載頁面查看它們。

依效能服務等級符合性子部分顯示可用儲存工作負載的總數：

* 符合各類績效服務水平
* 指派的效能服務等級與建議的效能服務等級不匹配




== 資料中心概述部分

資料中心概覽部分以圖形方式表示資料中心中所有叢集的可用和已使用容量以及 IOPS。透過使用這些數據，您應該管理儲存工作負載的容量和 IOPS。該部分還顯示所有叢集的儲存工作負載的以下資訊：

* 資料中心內所有叢集的總容量、可用容量和已使用容量
* 資料中心內所有群集的總 IOPS、可用 IOPS 和已使用 IOPS
* 基於每個效能服務等級的可用容量和已使用容量
* 基於每個效能服務等級的可用和已使用 IOPS
* 未分配效能服務等級的工作負載所使用的總空間和 IOPS


*如何根據效能服務等級計算資料中心容量和效能*

已使用容量和 IOPS 是根據叢集中所有儲存工作負載的總已使用容量和效能來檢索的。

可用的 IOPS 是根據節點上的預期延遲和建議的效能服務等級計算的。它包括預期延遲小於或等於其自身預期延遲的所有效能服務等級的可用 IOPS。

可用容量是根據預期延遲和聚合體的建議性能服務等級計算的。它包括所有效能服務等級的可用容量，這些等級的預期延遲小於或等於其自身的預期延遲。
