---
permalink: storage-mgmt/concept_all_workloads.html 
sidebar: sidebar 
keywords: view, workloads, add, provision, storage, filter, analyze, performance, capacity, criteria 
summary: 所有工作負載視圖顯示資料中心叢集上所有可用工作負載的清單。 
---
= 查看工作負載
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
當您將叢集新增至 Unified Manager 時，每個叢集上的儲存工作負載都會自動被發現並顯示在「工作負載」頁面上。

只有在儲存工作負載上開始 I/O 操作後，Unified Manager 才會開始分析工作負載以供建議（建議的 PSL）。

FlexGroup卷及其組成部分被排除在外。



== 工作負載概述

工作負載概覽頁面顯示資料中心內工作負載的概覽以及資料中心的空間和效能概覽。

* *工作負載概覽*面板：顯示工作負載總數以及分配了或未分配 PSL 的工作負載數量。也顯示了每個 PSL 的工作量計數的細分。點擊計數將帶您進入包含已過濾工作負載的「所有工作負載」視圖。您也可以查看不符合系統建議的工作負載數量，並透過點擊「指派系統建議的 PSL」按鈕為其指派系統建議的 PSL。
* *資料中心概覽*面板：顯示資料中心的可用和已使用空間（TiB）和效能（IOPS）。也顯示每個 PSL 下所有工作負載的可用和已使用空間（TiB）和效能（IOPS）的細分。




== 所有工作負載視圖

*儲存 > 工作負載 > 所有工作負載* 頁面列出了與 Unified Manager 管理的ONTAP叢集相關的儲存工作負載。

對於新發現的尚未進行 I/O 操作的儲存工作負載，狀態為「等待 I/O」。在儲存工作負載上開始 I/O 作業後，Unified Manager 開始分析，工作負載狀態變成「學習中…」。分析完成後（從 I/O 操作開始後的 24 小時內），將顯示針對儲存工作負載的建議 PSL。

此頁面還可讓您為儲存工作負載指派儲存效率策略 (SEP) 和效能服務等級 (PSL)。您可以執行多項任務：

* 新增或配置儲存工作負載
* 查看和過濾工作負載列表
* 將 PSL 分配給儲存工作負載
* 評估系統建議的 PSL 並將其分配給工作負載
* 將 SEP 分配給儲存工作負載




=== 新增或配置儲存工作負載

您可以將儲存工作負載新增或設定到支援的 LUN（支援 iSCSI 和 FCP 協定）、NFS 檔案共用和 SMB 共用。

.步驟
. 按一下「儲存」>「工作負載」>「所有工作負載」>「建立」。
. 建立工作負載。有關信息，請參閱link:../storage-mgmt/concept_provision_and_manage_workloads.html["預配和管理工作負載"]。




=== 查看和過濾工作負載

在「所有工作負載」畫面上，您可以查看資料中心中的所有工作負載，或根據 PSL 或名稱搜尋特定的儲存工作負載。您可以使用篩選器圖示輸入特定的搜尋條件。您可以根據不同的篩選條件進行搜索，例如按主機叢集或儲存虛擬機器。 *Capacity Total* 選項允許按工作負載的總容量（以 MB 為單位）進行過濾。但是，在這種情況下，傳回的工作負載數量可能會有所不同，因為總容量是在位元組層級進行比較的。

對於每個工作負載，都會顯示主機叢集和儲存虛擬機器等信息，以及分配的 PSL 和 SEP。

該頁面還允許您查看工作負載的效能詳細資訊。您可以透過點擊「選擇/排序列」按鈕並選擇要查看的特定欄位來查看有關工作負載的 IOPS、容量和延遲的詳細資訊。效能視圖列顯示工作負載的平均 IOPS 和峰值 IOPS，您可以按一下工作負載分析器圖示以查看詳細的 IOPS 分析。



=== 分析工作負載的效能和容量標準

*IOPS 分析*彈出視窗中的*分析工作負載*按鈕將帶您進入工作負載分析頁面，您可以在其中選擇時間範圍並查看所選工作負載的延遲、吞吐量和容量趨勢。有關工作負載分析器的更多信息，請參閱link:..//performance-checker/concept_troubleshooting_workloads_using_workload_analyzer.html["使用工作負載分析器排除工作負載故障"]。

您可以透過點擊「效能視圖」列中的長條圖圖示來查看有關工作負載的效能信息，以協助進行故障排除。若要查看「工作負載分析」頁面上的效能和容量圖表來分析對象，請按一下「分析工作負載」按鈕。

有關詳細信息，請參閱 link:../performance-checker/reference_what_data_does_workload_analyzer_display.html["工作負載分析器顯示哪些數據"]。
