---
permalink: storage-mgmt/reference_what_ontap_issues_can_unified_manager_fix.html 
sidebar: sidebar 
keywords: ontap issues, fix it action, automatic remediation feature, remediation events, fix-it messages, fix-it events 
summary: 下表介紹了 Unified Manager 可以透過點擊「修復」或「修復全部」按鈕直接從 Unified Manager 使用者介面解決的ONTAP問題。 
---
= Unified Manager 可以修復哪些問題
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
透過使用Active IQ Unified Manager的自動修復功能，您可以選擇透過 Unified Manager 有效地解決某些ONTAP問題或管理某些ONTAP功能（例如反勒索軟體監控）。

下表介紹了這些ONTAP問題或功能，您可以透過 Unified Manager Web UI 上的 *修復它* 或 *修復全部* 按鈕直接管理這些問題或功能。

|===
| 事件名稱和描述 | 管理行動 | “修復”操作 


 a| 
捲空間已滿

該卷的空間幾乎用盡，並且已突破容量滿閾值。此閾值預設為磁碟區大小的 90%。
 a| 
啟用卷自動增長
 a| 
Unified Manager 確定此磁碟區未設定磁碟區自動成長，因此啟用此功能，以便磁碟區在需要時容量會增加。



 a| 
Inode 已滿

此磁碟區的 inode 已用完，無法接受任何新檔案。
 a| 
增加磁碟區上的 inode 數量
 a| 
將磁碟區上的 inode 數量增加 2%。



 a| 
偵測到儲存層策略不匹配

該磁碟區具有大量非活動數據，且目前分層策略設定為「僅快照」或「無」。
 a| 
啟用自動雲端分層
 a| 
由於磁碟區已經駐留在FabricPool上，它將分層策略變更為“自動”，以便將非活動資料移至成本較低的雲層。



 a| 
偵測到儲存層不匹配

該磁碟區具有大量非活動數據，但它不駐留在支援雲端的儲存層（FabricPool）上。
 a| 
更改磁碟區的儲存層
 a| 
將磁碟區移至支援雲端的儲存層，並將分層策略設為「自動」將非活動資料移至雲端。



 a| 
已禁用審計日誌

儲存虛擬機器未啟用稽核日誌
 a| 
為儲存虛擬機器啟用審核日誌記錄
 a| 
在儲存虛擬機器上啟用稽核日誌記錄。

請注意，儲存虛擬機器必須已經配置了本機或遠端稽核日誌位置。



 a| 
登入橫幅已停用

應啟用叢集的登入橫幅，透過明確存取限制來提高安全性。
 a| 
設定集群的登入橫幅
 a| 
將叢集登入橫幅設定為「`存取限制為授權使用者`」。



 a| 
登入橫幅已停用

應啟用儲存虛擬機器的登入橫幅，透過明確存取限制來提高安全性。
 a| 
為儲存虛擬機器設定登入橫幅
 a| 
將儲存虛擬機器登入橫幅設定為「僅限授權使用者存取」。



 a| 
SSH 使用不安全的密碼

帶有後綴“-cbc”的密碼被認為是不安全的。
 a| 
從叢集中刪除不安全的密碼
 a| 
從叢集中刪除不安全的密碼 - 例如 aes192-cbc 和 aes128-cbc。



 a| 
SSH 使用不安全的密碼

帶有後綴“-cbc”的密碼被認為是不安全的。
 a| 
從儲存虛擬機器中刪除不安全的密碼
 a| 
從儲存虛擬機器中刪除不安全的密碼 - 例如 aes192-cbc 和 aes128-cbc。



 a| 
AutoSupport HTTPS 傳輸已停用

用於向技術支援發送AutoSupport訊息的傳輸協定應該加密。
 a| 
將 HTTPS 設定為AutoSupport訊息的傳輸協定
 a| 
將 HTTPS 設定為叢集上AutoSupport訊息的傳輸協定。



 a| 
叢集負載不平衡閾值已突破

表示叢集中節點之間的負載不平衡。當節點間效能容量使用差異超過 30% 時，產生此事件。
 a| 
平衡叢集工作負載
 a| 
Unified Manager 確定從一個節點移動到另一個節點的最佳磁碟區以減少不平衡，然後移動該磁碟區。



 a| 
集群容量不平衡閾值被突破

表示叢集中聚合之間的容量不平衡。當聚合之間的已使用容量差異超過 70% 時，會產生此事件。
 a| 
平衡叢集容量
 a| 
Unified Manager 確定從一個聚合移動到另一個聚合的最佳磁碟區以減少不平衡，然後移動該磁碟區。



 a| 
已使用效能容量閾值已突破

表示如果不透過一個或多個高度活躍的工作負載來降低利用率，則節點上的負載可能會被過度利用。當節點效能容量使用值超過100%且持續12小時以上時，產生此事件。
 a| 
限制節點的高負載
 a| 
Unified Manager 識別具有最高 IOPS 的捲，並使用歷史預期和峰值 IOPS 等級應用 QoS 策略來減少節點上的負載。



 a| 
動態事件警告閾值已突破

表示由於某些工作負載的負載異常高，該節點已經處於過載狀態。
 a| 
減少節點過載
 a| 
Unified Manager 識別具有最高 IOPS 的捲，並使用歷史預期和峰值 IOPS 等級應用 QoS 策略來減少節點上的負載。



 a| 
無法進行收購

故障轉移目前已停用，因此在中斷或重新啟動期間對節點資源的存取將會遺失，直到節點再次可用為止。
 a| 
啟用節點故障轉移
 a| 
Unified Manager 會傳送適當的命令以在叢集中的所有節點上啟用故障轉移。



 a| 
選項 Cf.takeover.on_panic 配置為關閉

nodeshell 選項「cf.takeover.on_panic」設定為*off*，這可能會導致 HA 配置的系統出現問題。
 a| 
啟用恐慌接管
 a| 
Unified Manager 向叢集發送適當的命令以將此設定變更為 *on*。



 a| 
停用 nodeshell 選項 snapmirror.enable

舊的 nodeshell 選項「snapmirror.enable」設定為 *on*，這可能會在升級到ONTAP 9.3 或更高版本後在啟動期間導致問題。
 a| 
將 snapmirror.enable 選項設定為關閉
 a| 
Unified Manager 向叢集發送適當的命令以將此設定變更為 *off*。



 a| 
已啟用 Telnet

表示存在潛在的安全問題，因為 Telnet 不安全並且以未加密的方式傳遞資料。
 a| 
禁用 Telnet
 a| 
Unified Manager 向叢集發送適當的命令以停用 Telnet。



 a| 
配置儲存 VM 反勒索軟體學習

定期檢查具有反勒索軟體監控許可證的群集。驗證儲存虛擬機器在這樣的叢集中是否僅支援 NFS 或 SMB 磁碟區。
 a| 
將儲存虛擬機器放入 `learning`反勒索軟體監控模式
 a| 
Unified Manager 將反勒索軟體監控設定為 `learning`透過叢集管理控制台查看儲存虛擬機器的狀態。儲存虛擬機器上建立的所有新磁碟區上的反勒索軟體監控都會自動轉入學習模式。透過此功能， ONTAP可以了解磁碟區上的活動模式並偵測因潛在惡意攻擊而導致的異常。



 a| 
配置批量反勒索軟體學習

定期檢查具有反勒索軟體監控許可證的群集。驗證磁碟區在這樣的叢集中是否僅支援 NFS 或 SMB 服務。
 a| 
將捲放入 `learning`反勒索軟體監控模式
 a| 
Unified Manager 將反勒索軟體監控設定為 `learning`透過叢集管理控制台查看磁碟區的狀態。透過此功能， ONTAP可以了解磁碟區上的活動模式並偵測因潛在惡意攻擊而導致的異常。



 a| 
啟用批量反勒索軟體

定期檢查具有反勒索軟體監控許可證的群集。檢測卷是否在 `learning`反勒索軟體監控模式超過 45 天，並確定將其置於主動模式的前景。
 a| 
將捲放入 `active`反勒索軟體監控模式
 a| 
Unified Manager 將反勒索軟體監控設定為 `active`透過叢集管理控制台在磁碟區上。透過此功能， ONTAP可以了解磁碟區上的活動模式並偵測因潛在惡意攻擊而導致的異常，並為資料保護措施建立警報。



 a| 
禁用批量反勒索軟體

定期檢查具有反勒索軟體監控許可證的群集。在磁碟區進行主動反勒索軟體監控期間偵測重複通知（例如，30 天內多次返回潛在勒索軟體攻擊的警告）。
 a| 
禁用磁碟區上的反勒索軟體監控
 a| 
Unified Manager 透過叢集管理控制台停用磁碟區上的反勒索軟體監控。

|===