---
permalink: storage-mgmt/reference_email_notification_format_page.html 
sidebar: sidebar 
keywords: email, notification, format, page 
summary: 電子郵件通知格式頁面顯示當出現與配額相關的問題（超出軟限製或達到硬限制）時發送給使用者或使用者群組的電子郵件的規則。 
---
= 電子郵件通知格式頁面
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
電子郵件通知格式頁面顯示當出現與配額相關的問題（超出軟限製或達到硬限制）時發送給使用者或使用者群組的電子郵件的規則。

只有在產生以下使用者或使用者群組配額事件時才會發送電子郵件通知：超出使用者或群組配額磁碟空間軟限制、超出使用者或群組配額檔案計數軟限制、達到使用者或群組配額磁碟空間硬限製或達到使用者或群組配額檔案計數硬限制。

* *從*
+
顯示發送電子郵件的電子郵件地址，您可以修改該地址。預設情況下，這是通知頁面指定的電子郵件地址。

* *主題*
+
顯示通知電子郵件的主題。

* *電子郵件詳細資訊*
+
顯示通知電子郵件的文字。您可以根據您的要求修改文字。例如，您可以提供與配額屬性相關的資訊並減少關鍵字的數量。但是，您不應該修改關鍵字。

+
有效關鍵字如下：

+
** $事件名稱
+
指定導致電子郵件通知的事件名稱。

** $QUOTA_TARGET
+
指定配額適用的 qtree 或卷。

** $QUOTA_USED_PERCENT
+
指定使用者或使用者群組使用的磁碟硬限制、磁碟軟限制、檔案硬限製或檔案軟限制的百分比。

** $QUOTA_LIMIT
+
指定使用者或使用者群組達到的磁碟硬限製或檔案硬限制，並產生以下事件之一：

+
*** 已達到使用者或群組配額磁碟空間硬限制
*** 已達到使用者或群組配額磁碟空間軟限制
*** 已達到使用者或群組配額檔案數硬限制
*** 已達到使用者或群組配額檔案計數軟限制


** $QUOTA_USED
+
指定使用者或使用者群組使用的磁碟空間或建立的檔案數。

** $QUOTA_USER
+
指定使用者或使用者群組的名稱。







== 命令按鈕

命令按鈕可讓您預覽、儲存或取消電子郵件通知格式所做的變更：

* *預覽*
+
顯示通知電子郵件的預覽。

* *恢復出廠預設值*
+
使您能夠將通知格式恢復為原廠預設值。

* *節省*
+
儲存通知格式所做的變更。


