---
permalink: storage-mgmt/reference_rules_to_generate_user_and_group_quota.html 
sidebar: sidebar 
keywords: rules, generate, user, group, quota, email, address, page, area, define, add comments, syntax, command buttons 
summary: 透過「產生使用者和群組配額電子郵件地址的規則」頁面，您可以建立規則，以根據與叢集、SVM、磁碟區、qtree、使用者或使用者群組關聯的使用者配額指定電子郵件地址。當超出配額時，會向指定的電子郵件地址發送通知。 
---
= 產生使用者和群組配額電子郵件地址的規則頁面
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
透過「產生使用者和群組配額電子郵件地址的規則」頁面，您可以建立規則，以根據與叢集、SVM、磁碟區、qtree、使用者或使用者群組關聯的使用者配額指定電子郵件地址。當超出配額時，會向指定的電子郵件地址發送通知。



== 規則區域

您必須定義配額電子郵件地址的規則。您也可以新增評論來解釋規則。



== 如何定義規則

您必須按照要執行的順序輸入規則。如果符合第一條規則的標準，則根據該規則產生電子郵件地址。如果不符合該標準，則考慮下一個規則的標準，依此類推。每行列出一條單獨的規則。預設規則是清單中的最後一條規則。您可以更改規則的優先順序。但是，您不能更改預設規則的順序。

例如，如果您要使用電子郵件地址 qtree1@xyz.com 接收有關 qtree1 配額違規的通知，並使用電子郵件地址 admin@xyz.com 接收所有其他 qtree 的配額違規通知，則必須按以下順序列出規則：

* 如果（$QTREE =='qtree1'）則qtree1@xyz.com
* 如果（$QTREE == *）則 admin@xyz.com


如果您指定的規則均不符合任何條件，則使用預設規則：

如果（$USER_OR_GROUP == *）則$USER_OR_GROUP@$DOMAIN

如果多個使用者俱有相同的配額，則使用者的名稱將顯示為逗號分隔的值，且規則不適用於該配額。



== 如何添加評論

您可以新增評論來解釋規則。您應該在每個註解的開頭使用#，並且每行列出一個單獨的註解。



== 規則語法

規則的語法必須是下列之一：

* 如果 （ `valid variableoperator *` ） 然後 `email ID@domain name`
+
if 是關鍵字且是小寫的。運算符是 ==。電子郵件 ID 可以包含任意字元、有效變數 $USER_OR_GROUP、$USER 或 $GROUP，或任意字元和有效變數 $USER_OR_GROUP、$USER 或 $GROUP 的組合。網域可以包含任意字元、有效變數 $DOMAIN 或任意字元和有效變數 $DOMAIN 的組合。有效變數可以是大寫或小寫，但不能是兩者的組合。例如，$domain 和 $DOMAIN 是有效的，但 $Domain 不是有效變數。

* 如果 （ `valid variableoperator `string`` ） 然後 `email ID@domain name`
+
if 是關鍵字且是小寫的。運算子可以是 contains 或 ==。電子郵件 ID 可以包含任意字元、有效變數 $USER_OR_GROUP、$USER 或 $GROUP，或任意字元和有效變數 $USER_OR_GROUP、$USER 或 $GROUP 的組合。網域可以包含任意字元、有效變數 $DOMAIN 或任意字元和有效變數 $DOMAIN 的組合。有效變數可以是大寫或小寫，但不能是兩者的組合。例如，$domain 和 $DOMAIN 是有效的，但 $Domain 不是有效變數。





== 命令按鈕

命令按鈕可讓您儲存、驗證或取消已建立的規則：

* *證實*
+
驗證所建立規則的語法。如果驗證期間出現錯誤，則會顯示產生錯誤的規則以及錯誤訊息。

* *恢復出廠預設值*
+
使您能夠將位址規則恢復為出廠預設值。

* *節省*
+
驗證規則的語法，如果沒有錯誤則儲存規則。如果驗證期間出現錯誤，則會顯示產生錯誤的規則以及錯誤訊息。


