---
permalink: storage-mgmt/task_change_performance_statistics_collection_interval.html 
sidebar: sidebar 
keywords: change, performance, statistics, collection, interval 
summary: 效能統計資訊的預設收集間隔為5分鐘。如果您發現大型叢集的收集未在預設時間內完成，則可以將此間隔變更為 10 或 15 分鐘。此設定會影響此 Unified Manager 實例所監控的所有叢集的統計資訊收集。 
---
= 修改效能統計收集間隔
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
效能統計資訊的預設收集間隔為5分鐘。如果您發現大型叢集的收集未在預設時間內完成，則可以將此間隔變更為 10 或 15 分鐘。此設定會影響此 Unified Manager 實例所監控的所有叢集的統計資訊收集。

.開始之前
您必須擁有授權登入 Unified Manager 伺服器維護控制台的使用者 ID 和密碼。

橫幅訊息指出了效能統計資料收集未按時完成的問題 `Unable to consistently collect from cluster <cluster_name> or Data collection is taking too long on cluster <cluster_name>.`

僅當因統計資訊收集問題而需要時才應變更收集間隔。請勿因任何其他原因更改此設定。

[NOTE]
====
將此值從預設設定 5 分鐘變更為其他值可能會影響 Unified Manager 報告的效能事件的數量和頻率。例如，當超過策略 30 分鐘時，系統定義的效能閾值會觸發事件。當使用 5 分鐘收集時，必須超過該政策連續六次收集。對於 15 分鐘的收集，政策必須僅超出兩個收集期。

====
叢集設定頁面底部的訊息指示目前統計資料收集間隔。

.步驟
. 使用 SSH 以維護使用者身分登入 Unified Manager 主機。
+
將顯示 Unified Manager 維護控制台提示。

. 鍵入標示為「*效能輪詢間隔配置*」的選單選項的編號，然後按 Enter。
. 如果出現提示，請再次輸入維護使用者密碼。
. 鍵入要設定的新輪詢間隔的數字，然後按 Enter。


如果您將 Unified Manager 收集間隔變更為 10 或 15 分鐘，且您目前已連線至外部資料提供者（例如 Graphite），則必須變更資料提供者傳輸間隔，使其等於或大於 Unified Manager 收集間隔。
