---
permalink: storage-mgmt/task_provision_fileshares.html 
sidebar: sidebar 
keywords: provision, file, share, volumes 
summary: 您可以從「設定工作負載」頁面在現有叢集和儲存虛擬機器（儲存 VM）上建立支援 CIFS/SMB 和 NFS 協定的檔案共用磁碟區。 
---
= 設定檔共享卷
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以從「設定工作負載」頁面在現有叢集和儲存虛擬機器（儲存 VM）上建立支援 CIFS/SMB 和 NFS 協定的檔案共用磁碟區。

.開始之前
* 儲存虛擬機器必須具有用於設定檔共用磁碟區的空間。
* 您的儲存虛擬機器上應啟用 SMB 和/或 NFS 服務。
* 為了在工作負載上選擇和分配效能服務等級 (PSL) 和儲存效率策略 (SEP)，必須在開始建立工作負載之前建立這些策略。


.步驟
. 在「Provision Workload」頁面上，新增要建立的工作負載的名稱，然後從可用清單中選擇叢集。
. 根據您選擇的集群，*STORAGE VM* 欄位會過濾該集群可用的儲存 VM。從清單中選擇所需的儲存虛擬機器。
+
根據儲存虛擬機器上支援的 SMB 和 NFS 服務，在主機資訊部分啟用 NAS 選項。

. 在儲存和最佳化部分，分配儲存容量和 PSL，也可以選擇為工作負載分配 SEP。
+
在建立工作負載時，SEP 的規格會指派給 LUN，而 PSL 的定義則會套用於工作負載。

. 如果您想要強制執行已指派給工作負載的 PSL，請勾選「*強制執行效能限制*」複選框。
+
將 PSL 指派給工作負載可確保建立工作負載的聚合體能夠支援對應策略中定義的效能和容量目標。例如，如果為工作負載分配了「極限效能」PSL，則要配置工作負載的聚合體應該具有支援「極限效能」策略的效能和容量目標的能力，例如 SSD 儲存。

+
[NOTE]
====
除非您選取此複選框，否則 PSL 不會套用於工作負載，且儀表板上的工作負載狀態將顯示為未指派。

====
. 選擇 *NAS* 選項。
+
如果您看不到啟用的 *NAS* 選項，請驗證您選擇的儲存虛擬機器是否支援 SMB 或 NFS，或兩者。

+
[NOTE]
====
如果您的儲存虛擬機器同時啟用了 SMB 和 NFS 服務，您可以選取 *透過 NFS 共用* 和 *透過 SMB 共用* 複選框，並建立同時支援 NFS 和 SMB 協定的檔案共用。如果要建立 SMB 或 CIFS 共享，請僅選取相應的核取方塊。

====
. 對於 NFS 檔案共用卷，指定用於存取檔案共用磁碟區的主機或網路的 IP 位址。您可以為多個主機輸入逗號分隔的值。
+
新增主機 IP 位址時，將執行內部檢查以將主機詳細資訊與儲存 VM 匹配，並建立該主機的匯出策略，或者如果存在現有策略，則重新使用該策略。如果為相同主機建立了多個 NFS 共用，則具有符合規則的相同主機的可用匯出策略將對所有檔案共用重複使用​​。當您使用 API 設定 NFS 共用時，可以使用指定單一原則的規則或透過提供特定的策略金鑰來重複使用策略的功能。

. 對於 SMB 共享，指定哪些使用者或使用者群組可以存取 SMB 共享並分配所需的權限。對於每個使用者群組，在檔案共用建立期間都會產生新的存取控制清單 (ACL)。
. 點選“儲存”。
+
此工作負載已新增至儲存工作負載清單中。


