---
permalink: storage-mgmt/task_provision_luns.html 
sidebar: sidebar 
keywords: provision, luns 
summary: 您可以從「設定工作負載」頁面在現有叢集和儲存虛擬機器（儲存 VM）上建立支援 CIFS/SMB 和 NFS 協定的 LUN。 
---
= 配置 LUN
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以從「設定工作負載」頁面在現有叢集和儲存虛擬機器（儲存 VM）上建立支援 CIFS/SMB 和 NFS 協定的 LUN。

.開始之前
* 儲存虛擬機器必須具有用於設定 LUN 的空間。
* 在建立 LUN 的儲存 VM 上必須同時啟用 iSCSI 和 FCP。
* 為了在工作負載上選擇和分配效能服務等級 (PSL) 和儲存效率策略 (SEP)，必須在開始建立工作負載之前建立這些策略。


.步驟
. 在「Provision Workload」頁面上，新增要建立的工作負載的名稱，然後從可用清單中選擇叢集。
+
根據您選擇的集群，*STORAGE VM* 欄位會過濾該集群可用的儲存 VM。

. 從清單中選擇支援 iSCSI 和 FCP 服務的儲存虛擬機器。
+
根據您的選擇，SAN 選項在主機資訊部分中啟用。

. 在「儲存和最佳化」部分中，分配儲存容量和 PSL，以及可選的工作負載的 SEP。
+
在建立工作負載時，SEP 的規格會指派給 LUN，而 PSL 的定義則會套用於工作負載。

. 如果您想要在工作負載上強制執行指派的 PSL，請勾選「*強制執行效能限制*」複選框。
+
將 PSL 指派給工作負載可確保建立工作負載的聚合體能夠支援對應策略中定義的效能和容量目標。例如，如果為工作負載分配了「極限效能」PSL，則要配置工作負載的聚合體應該具有支援「極限效能」策略的效能和容量目標的能力，例如 SSD 儲存。

+
[NOTE]
====
除非您選取此複選框，否則 PSL 不會套用於工作負載，且工作負載的狀態在儀表板上顯示為 `unassigned`。

====
. 選擇 *SAN* 選項。如果您看不到啟用的 *SAN* 選項，請驗證您選擇的儲存虛擬機器是否支援 iSCSI 和 FCP。
. 選擇主機作業系統。
. 指定主機對映以控制啟動器對 LUN 的存取。您可以指派現有的啟動器群組 (igroup)，或定義和對應新的 igroup。
+
[NOTE]
====
如果在設定 LUN 時建立新的 igroup，則需要等到下一個發現週期（最多 15 分鐘）才能使用它。因此，建議您使用可用 igroup 清單中的現有 igroup。

====
+
如果要建立新的 igroup，請選擇「建立新的啟動器群組」按鈕，然後輸入該 igroup 的資訊。

. 點選“儲存”。
+
LUN 已新增至儲存工作負載清單中。


