---
permalink: health-checker/concept_how_annotation_rules_work_in_unified_manager.html 
sidebar: sidebar 
keywords: annotation rules, work, unified manager 
summary: '註釋規則是您定義的用於註釋儲存物件（磁碟區、叢集或儲存虛擬機器 (SVM)）的標準。您可以使用條件群組或條件來定義註解規則。' 
---
= Unified Manager 中的註解規則如何運作
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
註釋規則是您定義的用於註釋儲存物件（磁碟區、叢集或儲存虛擬機器 (SVM)）的標準。您可以使用條件群組或條件來定義註解規則。

* 您必須將註釋規則與註釋關聯起來。
* 您必須為註解規則關聯一個物件類型；一個註解規則只能關聯一種物件類型。
* Unified Manager 在每個監控週期之後或在建立、編輯、刪除或重新排序規則時從儲存物件中新增或刪除註解。
* 一個註解規則可以有一個或多個條件組，每個條件組可以有一個或多個條件。
* 儲存物件可以有多個註釋。針對特定註釋的註釋規則也可以使用規則條件中的不同註釋來為已註釋的物件新增另一個註釋。




== 狀況

您可以建立多個條件組，每個條件組可以有一個或多個條件。您可以在註釋的註釋規則中套用所有定義的條件群組，以便註釋儲存物件。

條件組內的條件使用邏輯「與」來執行。條件組中的所有條件必須滿足。當您建立或修改註解規則時，會建立一個條件，該條件僅套用、選取和註解那些符合條件群組中所有條件的儲存物件。當您想要縮小要註解的儲存物件的範圍時，您可以在條件群組中使用多個條件。

您可以使用下列運算元和運算子並指定所需的值來建立具有儲存物件的條件。

[cols="2*"]
|===
| 儲存物件類型 | 適用操作數 


 a| 
體積
 a| 
* 物件名稱
* 所屬群集名稱
* 所屬 SVM 名稱
* 註解




 a| 
支援向量機
 a| 
* 物件名稱
* 所屬群集名稱
* 註解




 a| 
簇
 a| 
* 物件名稱
* 註解


|===
當您選擇註解作為任何儲存物件的運算元時，「Is」運算子可用。對於所有其他運算元，您可以選擇“Is”或“Contains”作為運算符。當您選擇「Is」運算子時，將評估條件是否為操作數值與所選運算元提供的值完全相符。當您選擇「包含」運算子時，將評估條件是否符合下列條件之一：

* 操作數值與所選操作數的值完全相符。
* 操作數值包含為所選操作數提供的值。




== 帶有條件的註解規則範例

考慮具有一個條件組的註釋規則，該規則針對具有以下兩個條件的捲：

* 名稱包含“`vol`”
* SVM 名稱稱為“`data_svm`”


此註解規則使用選定的註解和註解類型對名稱中包含「vol」且託管在名為「data_svm」的 SVM 上的所有磁碟區進行註解。



== 條件組

條件組使用邏輯或執行，然後套用於儲存物件。儲存物件必須滿足要註釋的其中一個條件群組的要求。對滿足所有條件組條件的儲存物件進行註釋。您可以使用條件群組來增加要註解的儲存物件的範圍。



== 帶有條件組的註釋規則範例

考慮一個具有兩個卷條件組的註釋規則；每個組包含以下兩個條件：

* 條件組 1
+
** 名稱包含“`vol`”
** SVM 名稱稱為「`data_svm`」 此條件群組註解名稱中包含「`vol`」且託管在名為「`data_svm`」的 SVM 上的所有磁碟區。


* 條件組 2
+
** 名稱包含“`vol`”
** 資料優先權的註解值為「`critical`」 此條件群組將名稱中包含「vol」且資料優先權註解值為「critical」的所有磁碟區進行註解。




當包含這兩個條件組的註解規則套用至儲存物件時，則會註解以下儲存物件：

* 名稱中包含「vol」且託管在 SVM 上且名稱為「data_svm」的所有磁碟區。
* 所有名稱中包含「vol」且資料優先註解值為「critical」的磁碟區。

