---
permalink: health-checker/concept_introduction_to_unified_manager_health_monitoring.html 
sidebar: sidebar 
keywords: introduction, active iq, unified manager, health, monitor 
summary: Active IQ Unified Manager （以前稱為OnCommand Unified Manager）可協助您透過集中式使用者介面監控執行ONTAP軟體的大量系統。  Unified Manager 伺服器基礎架構提供可擴充性、可支援性以及增強的監控和通知功能。 
---
= Active IQ Unified Manager健康監控簡介
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Active IQ Unified Manager （以前稱為OnCommand Unified Manager）可協助您透過集中式使用者介面監控執行ONTAP軟體的大量系統。  Unified Manager 伺服器基礎架構提供可擴充性、可支援性以及增強的監控和通知功能。

Unified Manager 的主要功能包括監控、警報、管理叢集的可用性和容量、管理保護功能以及捆綁診斷資料並將其傳送給技術支援。

您可以使用 Unified Manager 來監控您的叢集。當叢集中出現問題時，Unified Manager 會透過事件通知您此類問題的詳細資訊。有些事件還會為您提供可以採取的補救措施來糾正問題。您可以設定事件警報，以便在出現問題時透過電子郵件和 SNMP 陷阱通知您。

您可以使用 Unified Manager 透過將儲存物件與註解關聯來管理環境中的儲存物件。您可以建立自訂註釋，並透過規則將叢集、儲存虛擬機器 (SVM) 和磁碟區與註釋動態關聯。

您也可以使用容量和運行狀況圖表中提供的資訊來為各個叢集物件規劃叢集物件的儲存需求。



== 物理和邏輯容量

Unified Manager 利用用於ONTAP儲存物件的實體和邏輯空間的概念。

* 物理容量：物理空間是指磁碟區中使用的實體儲存區塊。由於儲存效率功能（例如重複資料刪除和壓縮）減少了數據，因此「物理已使用容量」通常小於邏輯已使用容量。
* 邏輯容量：邏輯空間是指磁碟區中的可用空間（邏輯區塊）。邏輯空間是指理論上如何使用空間，不考慮重複資料刪除或壓縮的結果。 「使用的邏輯空間」是使用的實體空間加上已配置的儲存效率功能（例如重複資料刪除和壓縮）所節省的空間。這個測量值通常看起來大於物理使用容量，因為這沒有反映資料壓縮和物理空間的其他減少。因此，總邏輯容量可能高於配置的空間。




== 容量測量單位

Unified Manager 根據 1024（2^10^）位元組的二進位單位計算儲存容量。在ONTAP 9.10.0 及更早版本中，這些單位顯示為 KB、MB、GB、TB 和 PB。從ONTAP 9.10.1 開始，它們在 Unified Manager 中顯示為 KiB、MiB、GiB、TiB 和 PiB。


NOTE: 對於ONTAP的所有版本，吞吐量使用的單位仍然是每秒千位元組 (Kbps)、每秒兆位元組 (Mbps)、每秒千兆位元組 (Gbps) 或每秒太字節 (Tbps) 等等。

[cols="4*"]
|===
| Unified Manager for ONTAP 9.10.0 及更早版本中顯示的容量單位 | Unified Manager for ONTAP 9.10.1 中顯示的容量單位 | 計算 | 以位元組為單位的值 


 a| 
知識庫
 a| 
基布
 a| 
1024
 a| 
1024 位元組



 a| 
MB
 a| 
資訊局
 a| 
1024 * 1024
 a| 
1,048,576 字節



 a| 
英國
 a| 
吉布
 a| 
1024 * 1024 * 1024
 a| 
1,073,741,824 字節



 a| 
結核病
 a| 
硼化鈦
 a| 
1024 * 1024 * 1024 * 1024
 a| 
1,099,511,627,776 字節

|===