---
permalink: health-checker/concept_what_database_restore_is.html 
sidebar: sidebar 
keywords: unified manager, database, restore 
summary: MySQL 資料庫還原是將現有的 Unified Manager 備份檔案還原到相同或不同的 Unified Manager 伺服器的過程。您可以從 Unified Manager 維護控制台執行復原操作。 
---
= 什麼是資料庫還原
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
MySQL 資料庫還原是將現有的 Unified Manager 備份檔案還原到相同或不同的 Unified Manager 伺服器的過程。您可以從 Unified Manager 維護控制台執行復原操作。

如果您在相同（本機）系統上執行還原操作，且備份檔案都儲存在本機，則可以使用預設位置執行還原選項。如果您在不同的 Unified Manager 系統（遠端系統）上執行還原操作，則必須在執行還原選項之前將備份檔案從輔助儲存複製到本機磁碟。

在復原過程中，您將退出 Unified Manager。恢復過程完成後，您可以登入系統。

如果要將備份映像還原到新伺服器，則還原作業完成後，您需要產生新的 HTTPS 安全性憑證並重新啟動 Unified Manager 伺服器。將備份映像還原到新伺服器時，您還需要重新設定 SAML 驗證設定（如果需要）。

[NOTE]
====
Unified Manager 升級到較新版本的軟體後，舊備份檔案無法用於復原映像。為了節省空間，升級 Unified Manager 時會自動刪除除最新檔案之外的所有舊備份檔案。

====
*相關資訊*

link:../config/task_generate_an_https_security_certificate_ocf.html["產生 HTTPS 安全性憑證"]

link:../config/task_enable_saml_authentication_um.html["啟用 SAML 身份驗證"]

link:../config/concept_authentication_with_active_directory_or_openldap.html["使用 Active Directory 或 OpenLDAP 進行驗證"]
