---
permalink: health-checker/concept_configure_destination_and_schedule_for_database_dump_backups.html 
sidebar: sidebar 
keywords: configure, destination, schedule, database dump, backups, snapshot copy, copies 
summary: 您可以設定 Unified Manager 資料庫轉儲備份設定來設定資料庫備份路徑、保留計數和備份計畫。您可以啟用每日或每週的計畫備份。預設情況下，計劃備份是禁用的，但您應該設定備份計劃。 
---
= 配置資料庫轉儲備份的目標和計劃
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以設定 Unified Manager 資料庫轉儲備份設定來設定資料庫備份路徑、保留計數和備份計畫。您可以啟用每日或每週的計畫備份。預設情況下，計劃備份是禁用的，但您應該設定備份計劃。

.開始之前
* 您必須具有操作員、應用程式管理員或儲存管理員角色。
* 您定義為備份路徑的位置必須至少有 150 GB 的可用空間。
+
建議您使用 Unified Manager 主機系統外部的遠端位置。

* 當 Unified Manager 安裝在 Linux 系統上並使用 MySQL 備份時，請確保在備份目錄上設定下列權限和所有權。
+
權限：0750，所有權：jboss：maintenance

* 當 Unified Manager 安裝在 Windows 系統上並使用 MySQL 備份時，請確保只有管理員才能存取備份目錄。


由於第一次備份是完整備份，因此第一次備份所需的時間比後續備份要多。完整備份可能超過 1 GB，並且可能需要三到四個小時。後續備份是增量的，需要的時間更少。

[NOTE]
====
* 如果您發現增量備份檔案的數量對於您為備份分配的空間來說太大，您可以定期進行完整備份以替換舊備份及其增量檔案。另一種選擇是，您可以使用 Snapshot 副本進行備份。
* 在新叢集新增後的最初 15 天內進行的備份可能不夠準確，無法取得歷史效能資料。


====
.步驟
. 在左側導覽窗格中，按一下「*常規*」>「*資料庫備份*」。
. 在*資料庫備份*頁面中，按一下*備份設定*。
. 為備份路徑、保留計數和計畫配置適當的值。
+
保留計數的預設值為 10；您可以使用 0 來建立無限備份。

. 選擇*每日計劃*或*每週計劃*按鈕，然後指定計劃詳細資訊。
. 按一下“*應用*”。


資料庫轉儲備份文件是根據計劃建立的。您可以在資料庫備份頁面中看到可用的備份檔案。
