---
permalink: health-checker/concept_common_unified_manager_administrative_workflows_and_tasks.html 
sidebar: sidebar 
keywords: Common, unified, manager, health, workflows, tasks 
summary: 與 Unified Manager 相關的一些常見管理工作流程和任務包括選擇要監控的儲存叢集；診斷對資料可用性、容量和保護產生不利影響的狀況；恢復遺失的資料；配置和管理磁碟區；以及捆綁並傳送診斷資料給技術支援（必要時）。 
---
= 常見的 Unified Manager 運作狀況工作流程與任務
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
與 Unified Manager 相關的一些常見管理工作流程和任務包括選擇要監控的儲存叢集；診斷對資料可用性、容量和保護產生不利影響的狀況；恢復遺失的資料；配置和管理磁碟區；以及捆綁並傳送診斷資料給技術支援（必要時）。

Unified Manager 讓儲存管理員能夠查看儀表板，評估託管儲存叢集的整體容量、可用性和保護健康狀況，然後快速識別、定位、診斷和分配可能出現的任何特定問題的解決方案。

與叢集、儲存虛擬機器 (SVM)、磁碟區或FlexGroup磁碟區相關的最重要的問題會影響託管儲存物件的儲存容量或資料可用性，這些問題顯示在「儀表板」頁面上的系統運作狀況圖表和事件中。當發現嚴重問題時，此頁面會提供連結來支援適當的故障排除工作流程。

Unified Manager 也可以包含在包含相關可管理性工具（例如OnCommand Workflow Automation (WFA)）的工作流程中，以支援儲存資源的直接設定。

本文檔介紹了與以下管理任務相關的常見工作流程：

* 診斷和管理可用性問題
+
如果硬體故障或儲存資源配置問題導致儀表板頁面中顯示資料可用性事件，儲存管理員可以按照嵌入的連結查看受影響儲存資源的連線資訊、查看故障排除建議並將問題解決方案指派給其他管理員。

* 配置和監控效能事件
+
管理員可以監視和管理被監視的儲存系統資源的效能。查看link:../performance-checker/concept_introduction_to_unified_manager_performance_monitoring.html["Active IQ Unified Manager效能監控簡介"]了解更多。

* 診斷與管理磁碟區容量問題
+
如果儀表板頁面中顯示卷宗儲存容量問題，儲存管理員可以按照嵌入的連結查看受影響卷的儲存容量相關的當前和歷史趨勢、查看故障排除建議並將問題解決方案指派給其他管理員。

* 配置、監控和診斷保護關係問題
+
建立和配置保護關係後，儲存管理員可以查看與保護關係相關的潛在問題、保護關係的當前狀態、受影響關係的當前和歷史保護作業成功資訊以及故障排除建議。查看link:../data-protection/concept_create_and_monitor_protection_relationships.html["建立、監控和排除保護關係故障"]了解更多。

* 建立備份檔案並從備份檔案還原資料。
* 將儲存物件與註釋關聯
+
透過將儲存物件與註釋關聯，儲存管理員可以過濾和查看與儲存物件相關的事件，從而使儲存管理員能夠確定與事件相關的問題的優先順序並解決這些問題。

* 使用 REST API 查看 Unified Manager 擷取的運作狀況、容量和效能資訊，從而協助管理叢集。看link:../api-automation/concept_get_started_with_um_apis.html["Active IQ Unified Manager REST API 入門"]了解更多。
* 向技術支援發送支援包
+
儲存管理員可以使用維護控制台檢索支援包並將其傳送給技術支援。當問題需要比AutoSupport訊息提供的更詳細的診斷和故障排除時，必須將支援包傳送給技術支援。


