---
permalink: health-checker/concept_how_group_rules_work_for_groups.html 
sidebar: sidebar 
keywords: group rules, work, groups 
summary: 群組規則是您定義的標準，用於將儲存物件（磁碟區、叢集或 SVM）納入特定群組。您可以使用條件群組或條件來定義群組的群組規則。 
---
= 群組規則如何適用於群組
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
群組規則是您定義的標準，用於將儲存物件（磁碟區、叢集或 SVM）納入特定群組。您可以使用條件群組或條件來定義群組的群組規則。

* 您必須將群組規則與群組關聯。
* 您必須為群組規則關聯一個物件類型；一個群組規則只能關聯一種物件類型。
* 在每個監控週期之後或建立、編輯或刪除規則時，都會在群組中新增或刪除儲存物件。
* 一個組規則可以有一個或多個條件組，每個條件組可以有一個或多個條件。
* 根據您建立的群組規則，儲存物件可以屬於多個群組。




== 狀況

您可以建立多個條件組，每個條件組可以有一個或多個條件。您可以在群組的群組規則中套用所有定義的條件群組，以指定哪些儲存物件包含在群組中。

條件組內的條件使用邏輯「與」來執行。條件組中的所有條件必須滿足。建立或修改群組規則時，將建立一個條件，該條件僅套用、選取和分組符合條件群組中所有條件的儲存物件。當您想要縮小群組中包含的儲存物件的範圍時，您可以在條件群組中使用多個條件。

您可以使用下列運算元和運算子並指定所需的值來建立具有儲存物件的條件。

[cols="2*"]
|===
| 儲存物件類型 | 適用操作數 


 a| 
體積
 a| 
* 物件名稱
* 所屬群集名稱
* 所屬 SVM 名稱
* 註解




 a| 
支援向量機
 a| 
* 物件名稱
* 所屬群集名稱
* 註解




 a| 
簇
 a| 
* 物件名稱
* 註解


|===
當您選擇註解作為任何儲存物件的運算元時，「Is」運算子可用。對於所有其他運算元，您可以選擇“Is”或“Contains”作為運算符。

* 操作數
+
Unified Manager 中的操作數清單會根據所選的物件類型而變更。此清單包括物件名稱、所屬叢集名稱、所屬 SVM 名稱以及您在 Unified Manager 中定義的註解。

* 操作員
+
運算子清單會根據條件所選的操作數而變化。  Unified Manager 中支援的運算元是「Is」和「Contains」。

+
當您選擇「Is」運算子時，將評估條件是否為操作數值與所選運算元提供的值完全相符。

+
當您選擇「包含」運算子時，將評估條件是否符合下列條件之一：

+
** 操作數值與所選操作數提供的值完全匹配
** 操作數值包含為所選操作數提供的值


* 價值
+
值欄位會根據所選的操作數而變化。





== 帶有條件的群組規則範例

考慮具有以下兩個條件的捲的條件組：

* 名稱包含“`vol`”
* SVM 名稱稱為“`data_svm`”


此條件群組選擇名稱中包含「vol」且託管在名為「data_svm」的 SVM 上的所有磁碟區。



== 條件組

條件組使用邏輯或執行，然後套用於儲存物件。儲存物件必須滿足其中一個條件群組才能被納入某個群組。所有條件組的儲存物件合併在一起。您可以使用條件群組來增加群組中儲存物件的範圍。



== 具有條件組的組規則範例

考慮一個卷的兩個條件組，每個組包含以下兩個條件：

* 條件組 1
+
** 名稱包含“`vol`”
** SVM 名稱稱為「`data_svm`」 條件群組 1 選擇名稱中包含「`vol`」且託管在名為「`data_svm`」的 SVM 上的所有磁碟區。


* 條件組 2
+
** 名稱包含“`vol`”
** 資料優先權的註解值為「`critical`」 條件群組 2 選擇名稱中包含「vol`」且資料優先權註解值為「critical」的所有磁碟區。




當包含這兩個條件群組的群組規則套用至儲存物件時，下列儲存物件將會新增至選取的群組：

* 名稱中包含「vol」且託管在名為「data_svm」的 SVM 上的所有磁碟區。
* 所有名稱中包含「vol」且資料優先註解值為「critical」的磁碟區。

