---
permalink: health-checker/reference_setup_autosupport_page.html 
sidebar: sidebar 
keywords: autosupport, messages, support bundles, technical support 
summary: AutoSupport頁面可讓您向技術支援團隊發送預先定義和按需的AutoSupport訊息，以確保您的環境正常運行，並協助您維護環境的完整性。  AutoSupport預設處於啟用狀態，您不應停用它，以便您獲得 NetAppActive IQ 的優勢。 
---
= 將AutoSupport訊息和支援包發送給技術支持
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
AutoSupport頁面可讓您向技術支援團隊發送預先定義和按需的AutoSupport訊息，以確保您的環境正常運行，並協助您維護環境的完整性。  AutoSupport預設處於啟用狀態，您不應停用它，以便您獲得 NetAppActive IQ 的優勢。

您可以根據需要在訊息中傳送有關 Unified Manager 伺服器的診斷系統資訊和詳細數據，安排定期傳送訊息，甚至產生並傳送支援包給技術支援團隊。

[NOTE]
====
具有儲存管理員角色的使用者可以產生並發送按需AutoSupport訊息和支援包給技術支援。但是，只有管理員或維護使用者可以啟用或停用定期AutoSupport並配置 HTTP 設置，如設定 HTTP 代理伺服器部分中所述。在需要使用 HTTP 代理伺服器的環境中，應先完成配置，然後儲存管理員才能向技術支援發送按需AutoSupport訊息和支援包。

====


== 發送按需AutoSupport訊息

您可以產生並發送按需訊息給技術支援人員，或發送給指定的電子郵件收件人，或同時發送給兩者。

.步驟
. 導覽至 *常規* > *AutoSupport*，然後執行以下操作之一或全部兩個：
. 如果您想將AutoSupport訊息傳送給技術支持，請選取 *傳送至技術支援* 複選框。
. 如果要將AutoSupport訊息傳送給特定的電子郵件收件人，請選取「*傳送給電子郵件收件人*」複選框，然後輸入收件人的電子郵件地址。
. 點選“儲存”。
. 點擊“生成並發送AutoSupport”。




== 啟用定期AutoSupport

您可以定期向技術支援發送特定的預定義訊息，以進行問題診斷和解決。此功能預設為啟用。如果停用，管理員或維護使用者可以啟用該設定。

.步驟
. 導覽至 *常規* > *AutoSupport*。
. 在定期AutoSupport部分中，選取*啟用定期向Active IQ發送AutoSupport資料*複選框。
. 如果需要，請依照設定 HTTP 代理伺服器部分中的說明定義 HTTP 代理伺服器的名稱、連接埠和驗證資訊。
. 點選“儲存”。




== 上傳按需支援包

您可以根據故障排除要求產生支援包並將其發送給技術支援。 Unified Manager 僅儲存最近產生的兩個支援包。較舊的支援包已從系統中刪除。

由於某些類型的支援資料可能會使用大量叢集資源或需要很長時間才能完成，因此當您選擇完整支援包時，您可以包含或排除特定資料類型以減少支援包的大小。您也可以選擇建立一個輕量級支援包，其中僅包含 30 天的日誌和設定資料庫記錄 - 它不包括效能資料、擷取記錄檔和伺服器堆轉儲。

.步驟
. 導覽至 *常規* > *AutoSupport*。
. 在按需支援包部分，按一下*產生並傳送支援包*。
. 若要向技術支援發送輕量支援包，請在產生並傳送支援包彈出視窗中選取**產生輕量支援包**複選框。
. 或者，要傳送完整的支援包，請選取「產生完整的支援包」複選框。選擇要在支援包中包含或排除的特定資料類型。
+
[NOTE]
====
即使您未選擇任何資料類型，支援包仍會與其他 Unified Manager 資料一起產生。

====
. 選取*將捆綁包傳送給技術支援*複選框以產生捆綁包並將其傳送給技術支援。如果您未選取此複選框，則會在 Unified Manager 伺服器本機產生並儲存捆綁包。產生的支援包可供日後在 VMware 系統的 /support 目錄中使用， `/opt/netapp/data/support/`在 Linux 系統上， `ProgramData\NetApp\OnCommandAppData\ocum\support`在 Windows 系統上。
. 按一下“*發送*”。




== 設定 HTTP 代理伺服器

如果您的環境不提供從 Unified Manager 伺服器的直接訪問，您可以指定代理來提供互聯網訪問，以便將AutoSupport內容傳送給支援人員。此部分僅供管理員和維護使用者使用。

* *使用 HTTP 代理*
+
勾選此方塊可識別用作 HTTP 代理的伺服器。

+
輸入代理伺服器的主機名稱或 IP 位址，以及用於連接伺服器的連接埠號碼。

* *使用身份驗證*
+
如果需要提供身份驗證資訊來存取用作 HTTP 代理的伺服器，請選取此方塊。

+
輸入透過 HTTP 代理進行身份驗證所需的使用者名稱和密碼。



[NOTE]
====
不支援僅提供基本驗證的 HTTP 代理。

====