---
permalink: health-checker/reference_health_aggregate_details_page.html 
sidebar: sidebar 
keywords: unified manager, aggregate, health details page 
summary: 您可以使用聚合/健康詳細資訊頁面查看有關所選聚合的詳細信息，例如容量、磁碟資訊、配置詳細資訊和生成的事件。您也可以查看有關該聚合的相關物件和相關警報的資訊。 
---
= 聚合/健康詳情頁面
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以使用聚合/健康詳細資訊頁面查看有關所選聚合的詳細信息，例如容量、磁碟資訊、配置詳細資訊和生成的事件。您也可以查看有關該聚合的相關物件和相關警報的資訊。



== 命令按鈕

[NOTE]
====
監控啟用FabricPool的聚合時，此頁面上的已提交值和過量提交值僅與本地或效能層容量相關。雲層中可用的空間量未反映在超額承諾的值中。類似地，聚合閾值僅與本地效能層相關。

====
命令按鈕可讓您對選取的聚合執行下列任務：

* *切換到效能視圖*
+
使您能夠導航至聚合/效能詳細資訊頁面。

* *行動*
+
** 添加警報
+
使您能夠在選定的聚合中添加警報。

** 編輯閾值
+
使您能夠修改選定聚合的閾值設定。



* *查看聚合*
+
使您能夠導航至“健康狀況：所有聚合”視圖。





== 容量選項卡

「容量」標籤顯示有關所選聚合的詳細信息，例如其容量、閾值和每日成長率。

預設情況下，不會為根聚合產生容量事件。此外，Unified Manager 使用的閾值不適用於節點根聚合。只有技術支援代表可以修改產生這些事件的設定。當技術支援代表修改設定時，閾值將應用於節點根聚合。

* *容量*
+
顯示資料容量圖和 Snapshot 副本圖，其中顯示有關聚合的容量詳細資訊：

+
** 已用邏輯空間
+
未應用ONTAP儲存效率技術節省的成本，聚合上儲存的資料的實際大小。

** 用過的
+
聚合中資料使用的物理容量。

** 過度承諾
+
當聚合中的空間被過度使用時，圖表會顯示一個有過度使用量的標誌。

** 警告
+
在設定警告閾值的位置顯示一條虛線；表示聚合中的空間已快滿。如果超過此閾值，則會產生空間幾乎已滿事件。

** 錯誤
+
在設定錯誤閾值的位置顯示一條實線；表示聚合中的空間已滿。如果超出此閾值，則會產生空間已滿事件。

** Snapshot 副本圖
+
僅當已用快照容量或快照預留不為零時才會顯示此圖。



+
如果已使用的快照容量超過快照預留，則兩個圖表都會顯示快照容量超過快照預留的容量。

* *雲層*
+
顯示啟用FabricPool的聚合的雲層中資料所使用的空間。  FabricPool可以是已授權的，也可以是未經授權的。

+
當雲層鏡像到另一個雲端提供者（「鏡像層」）時，兩個雲層都會顯示在這裡。

* *細節*
+
顯示有​​關容量的詳細資訊。

+
** 總容量
+
顯示聚合中的總容量。

** 數據容量
+
顯示聚合使用的空間量（已使用容量）和聚合中的可用空間量（可用容量）。

** 快照儲備
+
顯示聚合的已使用和可用快照容量。

** 超額承諾的產能
+
顯示總過量承諾。聚合過量使用使您能夠提供比給定聚合實際可用的更多的儲存空間，只要目前並非所有儲存空間都正在使用。使用精簡配置時，聚合中磁碟區的總大小可能會超過聚合的總容量。

+
[NOTE]
====
如果您過度使用了聚合，則必須仔細監控其可用空間並根據需要添加存儲，以避免因空間不足而導致寫入錯誤。

====
** 雲層
+
顯示啟用FabricPool的聚合的雲層中資料所使用的空間。 FabricPool可以是已授權的，也可以是未經授權的。當雲層鏡像到另一個雲端供應商（鏡像層）時，兩個雲層都會顯示在這裡

** 總緩存空間
+
顯示新增至 Flash Pool 聚合的固態硬碟 (SSD) 或分配單元的總空間。如果您已為聚合啟用 Flash Pool 但尚未新增任何 SSD，則快取空間將顯示為 0 KB。

+
[NOTE]
====
如果為聚合停用了 Flash Pool，則此欄位將被隱藏。

====
** 聚合閾值
+
顯示以下聚合容量閾值：

+
*** 接近滿閾值
+
指定聚合接近滿的百分比。

*** 完整閾值
+
指定聚合已滿的百分比。

*** 接近過度承諾的閾值
+
指定聚合接近過度承諾的百分比。

*** 過度承諾閾值
+
指定聚合過度承諾的百分比。



** 其他詳情：每日成長率
+
如果最後兩個樣本之間的變化率持續 24 小時，則顯示聚合中使用的磁碟空間。

+
例如，如果某個聚合在下午 2 點使用 10 GB 磁碟空間，在下午 6 點使用 12 GB 磁碟空間，則該聚合的每日成長率 (GB) 為 2 GB。

** 音量移動
+
顯示目前正在進行的捲移動操作的數量：

+
*** 輸出量
+
顯示正在移出聚合的磁碟區的數量和容量。

+
您可以單擊該連結以查看更多詳細信息，例如磁碟區名稱、磁碟區移動到的聚合、磁碟區移動操作的狀態以及預計結束時間。

*** 收貨量
+
顯示正在移動到聚合中的磁碟區的數量和剩餘容量。

+
您可以單擊該連結以查看更多詳細信息，例如磁碟區名稱、移動磁碟區的聚合、磁碟區移動操作的狀態以及預計結束時間。

*** 卷移動後的估計已用容量
+
顯示磁碟區移動作業完成後估計的已使用空間總量（以百分比表示，單位為 KB、MB、GB 等）。





* *容量概覽 - 卷*
+
顯示提供有關聚合中包含的磁碟區容量的資訊的圖表。顯示磁碟區已使用的空間量（已使用容量）和磁碟區中可用空間量（可用容量）。當為精簡配置磁碟區產生「精簡配置磁碟區空間處於風險」事件時，將顯示磁碟區已使用的空間量（已使用容量）以及磁碟區中可用但因聚合容量問題而無法使用的空間量（不可用容量）。

+
您可以從下拉清單中選擇要查看的圖表。您可以對圖表中顯示的資料進行排序，以顯示已使用大小、已配置大小、可用容量、每日最快成長率和最慢成長率等詳細資訊。您可以根據包含聚合中的磁碟區的儲存虛擬機器 (SVM) 來篩選資料。您也可以查看精簡配置卷的詳細資訊。您可以將遊標放在感興趣的區域上來查看圖表上特定點的詳細資訊。預設情況下，圖表顯示總體排名前 30 的過濾卷。





== 磁碟資訊選項卡

顯示有​​關選定聚合中磁碟的詳細信息，包括 RAID 類型和大小以及聚合中使用的磁碟類型。此標籤也以圖形方式顯示 RAID 群組以及所使用的磁碟類型（例如 SAS、ATA、FCAL、SSD 或 VMDISK）。您可以將遊標放在奇偶校驗磁碟和資料磁碟上以查看更多信息，例如磁碟的托架、架子和旋轉速度。

* *數據*
+
以圖形方式顯示有關專用資料磁碟、共用資料磁碟或兩者的詳細資訊。當資料磁碟包含共享磁碟時，顯示共享磁碟的圖形詳細資訊。當資料碟包含專用磁碟和共用磁碟時，會同時顯示專用磁碟和共用磁碟的圖形詳情。

+
** *RAID 詳細資料*
+
僅顯示專用磁碟的 RAID 詳細資訊。

+
*** 類型
+
顯示 RAID 類型（RAID0、RAID4、RAID-DP 或RAID-TEC）。

*** 團體規模
+
顯示 RAID 群組中允許的最大磁碟數。

*** 團體
+
顯示聚合中的 RAID 群組的數量。



** *使用的磁碟*
+
*** 有效類型
+
顯示聚合中的資料磁碟類型（例如，ATA、SATA、FCAL、SSD 或 VMDISK）。

*** 資料磁碟
+
顯示指派給聚合的資料磁碟的數量和容量。當聚合僅包含共享磁碟時，不會顯示資料磁碟詳細資訊。

*** 奇偶校驗磁碟
+
顯示指派給聚合的奇偶校驗磁碟的數量和容量。當聚合僅包含共用磁碟時，不會顯示奇偶校驗磁碟詳細資料。

*** 共享磁碟
+
顯示指派給聚合的共享資料磁碟的數量和容量。僅當聚合包含共享磁碟時才會顯示共享磁碟詳細資訊。



** *備用磁碟*
+
顯示選定聚合中節點可用的備用資料磁碟的有效類型、數量和容量。

+
[NOTE]
====
當聚合故障轉移到配對節點時，Unified Manager 不會顯示與聚合相容的所有備用磁碟。

====


* SSD 快取
+
提供有關專用快取 SSD 磁碟和共享快取 SSD 磁碟的詳細資訊。

+
顯示專用快取 SSD 磁碟的以下詳細資訊：

+
** *RAID 詳細資料*
+
*** 類型
+
顯示 RAID 類型（RAID0、RAID4、RAID-DP 或RAID-TEC）。

*** 團體規模
+
顯示 RAID 群組中允許的最大磁碟數。

*** 團體
+
顯示聚合中的 RAID 群組的數量。



** *使用的磁碟*
+
*** 有效類型
+
表示聚合中用於快取的磁碟類型為 SSD。

*** 資料磁碟
+
顯示指派給快取聚合的資料磁碟的數量和容量。

*** 奇偶校驗磁碟
+
顯示指派給聚合用於快取的奇偶校驗磁碟的數量和容量。



** *備用磁碟*
+
顯示選定聚合中可用於快取的節點的備用磁碟的有效類型、數量和容量。

+
[NOTE]
====
當聚合故障轉移到配對節點時，Unified Manager 不會顯示與聚合相容的所有備用磁碟。

====


+
提供共享快取的以下詳細資訊：

+
** *儲存池*
+
顯示儲存池的名稱。您可以將指標移到儲存池名稱上以查看以下詳細資訊：

+
*** 地位
+
顯示儲存池的狀態，可以是健康或不健康。

*** 總分配
+
顯示儲存池中的分配單元總數和大小。

*** 分配單元大小
+
顯示儲存池中可指派給聚合的最小空間量。

*** 磁碟
+
顯示用於建立儲存池的磁碟數量。如果儲存池列中的磁碟數量與該儲存池的「磁碟資訊」標籤中顯示的磁碟數量不匹配，則表示一個或多個磁碟損壞，儲存池不健康。

*** 已用分配
+
顯示聚合使用的分配單元的數量和大小。您可以按一下聚合名稱以查看聚合詳細資訊。

*** 可用分配
+
顯示節點可用的分配單元的數量和大小。您可以點擊節點名稱以查看聚合詳細資訊。



** *分配的快取*
+
顯示聚合使用的分配單元的大小。

** *分配單位*
+
顯示聚合使用的分配單元數。

** *磁碟*
+
顯示儲存池中包含的磁碟數量。

** *細節*
+
*** 儲存池
+
顯示儲存池的數量。

*** 總大小
+
顯示儲存池的總大小。





* *雲層*
+
如果您已設定啟用FabricPool的聚合，則顯示雲層的名稱，並顯示已使用的總空間。當雲層鏡像到另一個雲端提供者（鏡像層）時，兩個雲層的詳細資訊都會顯示在這裡





== “配置”選項卡

配置標籤顯示有關所選聚合的詳細信息，例如其叢集節點、區塊類型、RAID 類型、RAID 大小和 RAID 群組數量：

* *概述*
+
** 節點
+
顯示包含選定聚合的節點的名稱。

** 區塊類型
+
顯示聚合的區塊格式：32 位元或 64 位元。

** RAID類型
+
顯示 RAID 類型（RAID0、RAID4、RAID-DP、 RAID-TEC或混合 RAID）。

** RAID尺寸
+
顯示 RAID 群組的大小。

** RAID 群組
+
顯示聚合中的 RAID 群組的數量。

** SnapLock類型
+
顯示聚合的SnapLock類型。



* *雲層*
+
如果這是啟用FabricPool的聚合，則會顯示雲層的詳細資訊。某些欄位因儲存提供者的不同而不同。當雲層鏡像到另一個雲端提供者（「鏡像層」）時，兩個雲層都會顯示在這裡。

+
** 提供者
+
顯示儲存提供者的名稱，例如StorageGRID、Amazon S3、IBM Cloud Object Storage、Microsoft Azure Cloud、Google Cloud Storage 或 Alibaba Cloud Object Storage。

** Name
+
顯示由ONTAP建立雲層時的名稱。

** 伺服器
+
顯示雲層的 FQDN。

** 港口
+
用於與雲端提供者通訊的連接埠。

** 存取金鑰或帳戶
+
顯示雲層的存取金鑰或帳戶。

** 容器名稱
+
顯示雲層的儲存桶或容器名稱。

** SSL
+
顯示是否為雲層啟用了 SSL 加密。







== 歷史區

歷史記錄區域顯示提供有關所選聚合容量的資訊的圖表。此外，您可以按一下「*匯出*」按鈕為您正在查看的圖表建立 CSV 格式的報表。

您可以從歷史記錄窗格頂部的下拉清單中選擇圖表類型。您也可以透過選擇 1 週、1 個月或 1 年來查看特定時間段的詳細資訊。歷史圖表可以幫助您識別趨勢：例如，如果整體使用情況持續突破「接近滿」閾值，您可以採取適當的措施。

歷史圖表顯示以下資訊：

* *已使用總容量（%）*
+
以百分比形式在垂直 (y) 軸上顯示已使用的容量總量和基於使用歷史記錄的容量總量使用趨勢（折線圖）。時間段顯示在水平（x）軸上。您可以選擇一周、一個月或一年的時間段。您可以將遊標放在特定區域上以查看圖表上特定點的詳細資訊。您可以透過點選對應的圖例來隱藏或顯示折線圖。例如，當您按一下「已使用容量」圖例時，「已使用容量」圖形線將會被隱藏。

* *已使用總容量與總容量*
+
根據使用歷史記錄顯示聚合容量的使用趨勢，以及已使用容量和總容量，以折線圖形式在垂直 (y) 軸上以位元組、千位元組、兆位元組等為單位顯示。時間段顯示在水平（x）軸上。您可以選擇一周、一個月或一年的時間段。您可以將遊標放在特定區域上以查看圖表上特定點的詳細資訊。您可以透過點選對應的圖例來隱藏或顯示折線圖。例如，當您按一下「趨勢容量已使用」圖例時，「趨勢容量已使用」圖形線將會被隱藏。

* *已使用總容量 (%) 與已承諾容量 (%)*
+
根據使用歷史記錄顯示聚合容量的使用趨勢，並以折線圖的形式顯示已提交空間（以百分比表示，位於垂直 (y) 軸上）。時間段顯示在水平（x）軸上。您可以選擇一周、一個月或一年的時間段。您可以將遊標放在特定區域上以查看圖表上特定點的詳細資訊。您可以透過點選對應的圖例來隱藏或顯示折線圖。例如，當您按一下「已承諾空間」圖例時，「已承諾空間」圖形線將會被隱藏。





== 事件列表

事件清單顯示有關新事件和已確認事件的詳細資訊：

* *嚴重性*
+
顯示事件的嚴重性。

* *事件*
+
顯示事件名稱。

* *觸發時間*
+
顯示事件產生以來經過的時間。如果時間超過一周，則會顯示事件產生的時間戳記。





== 相關設備窗格

透過「相關設備」窗格，您可以查看與聚合相關的叢集節點、磁碟區和磁碟：

* *節點*
+
顯示包含聚合的節點的容量和運作狀況。容量表示可用容量與可用容量之比。

* *節點中的聚合*
+
顯示包含選定聚合的叢集節點中所有聚合的數量和容量。也會根據最高嚴重程度顯示聚合體的健康狀況。例如，如果一個叢集節點包含十個聚合，其中五個顯示「警告」狀態，其餘五個顯示「嚴重」狀態，則顯示的狀態為「嚴重」。

* *卷*
+
顯示聚合中的FlexVol捲和FlexGroup磁碟區的數量和容量；數量不包括FlexGroup組成部分。也會根據最高嚴重性等級顯示捲的健康狀況。

* 資源池
+
顯示與聚合相關的資源池。

* *磁碟*
+
顯示選定聚合中的磁碟數。





== 相關警報窗格

透過「相關警報」窗格，您可以查看為選定聚合所建立的警報清單。您也可以透過點擊新增警報連結來新增警報，或透過點擊警報名稱來編輯現有警報。

*相關資訊*

link:../health-checker/task_view_storage_pool_details.html["查看儲存池詳細信息"]
