---
permalink: health-checker/task_restore_snapshot_backup.html 
sidebar: sidebar 
keywords: restore, unified manager, snapshot copy, copies, 
summary: 如果發生資料遺失或資料損壞，您可以將 Unified Manager 還原到先前的穩定狀態，同時將資料損失降至最低。您可以使用 Unified Manager 維護控制台將 Unified Manager Snapshot 資料庫還原到本機或遠端作業系統。 
---
= 使用 Snapshot 副本還原 Unified Manager
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
如果發生資料遺失或資料損壞，您可以將 Unified Manager 還原到先前的穩定狀態，同時將資料損失降至最低。您可以使用 Unified Manager 維護控制台將 Unified Manager Snapshot 資料庫還原到本機或遠端作業系統。

.開始之前
* 您必須擁有 Linux 主機的 root 使用者憑證以及安裝了 Unified Manager 的 Windows 主機的管理權限。
* 您必須擁有授權登入 Unified Manager 伺服器維護控制台的使用者 ID 和密碼。


恢復功能是特定於平台和特定於版本的。您只能在相同版本的 Unified Manager 上還原 Unified Manager 備份。

.步驟
. 連接到 Unified Manager 系統的 IP 位址或完全限定網域名稱。
+
** Linux：安全殼
** Windows：Power Shell


. 使用 root 使用者憑證登入系統。
. 輸入命令 `maintenance_console`然後按 Enter 鍵。
. 在維護控制台*主選單*中，輸入 4 作為*備份還原*選項。
. 輸入 2 選擇 *使用NetApp Snapshot 備份和還原*。
+
如果您要在新伺服器上執行還原，則安裝 Unified Manager 後，請勿在安裝完成後啟動 UI 或設定任何叢集、使用者或驗證設定。輸入 1 選擇 *配置NetApp Snapshot Backup* 並配置 Snapshot 副本的設置，就像它們在原始系統上一樣。

. 輸入 3 選擇 *使用NetApp Snapshot 恢復*。
. 選擇要從中還原 Unified Manager 的 Snapshot 副本。按 *Enter*。
. 復原過程完成後，登入 Unified Manager 使用者介面。


恢復備份後，如果工作流程自動化伺服器無法運作，請執行下列步驟：

. 在工作流程自動化伺服器上，將 Unified Manager 伺服器的 IP 位址變更為指向最新的機器。
. 在 Unified Manager 伺服器上，如果在步驟 1 中取得失敗，請重設資料庫密碼。

