---
permalink: health-checker/task_migrate_um_virtual_appliance_to_rhel_system.html 
sidebar: sidebar 
keywords: unified manager, migrate, virtual, appliance, linux system 
summary: 如果您想要變更執行 Unified Manager 的主機作業系統，您可以將 Unified Manager MySQL 資料庫轉儲備份從虛擬裝置還原到 Red Hat Enterprise Linux 系統。 
---
= 將 Unified Manager 虛擬設備遷移到 Linux 系統
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
如果您想要變更執行 Unified Manager 的主機作業系統，您可以將 Unified Manager MySQL 資料庫轉儲備份從虛擬裝置還原到 Red Hat Enterprise Linux 系統。

.開始之前
* 在虛擬設備上：
+
** 您必須具有操作員、應用程式管理員或儲存管理員角色。
** 您必須知道執行復原作業的 Unified Manager 會維護使用者的名稱。


* 在Linux系統上：
+
** 您必須按照link:../install-linux/concept_install_unified_manager_on_rhel.html["在 Linux 系統上安裝 Unified Manager"]。
** 此伺服器上的 Unified Manager 版本必須與您使用備份檔案的虛擬裝置上的版本相同。
** 安裝後，請勿啟動 UI 或在 Linux 系統上設定任何叢集、使用者或驗證設定。備份檔案在復原過程中填入此資訊。
** 您必須擁有 Linux 主機的 root 使用者憑證。




這些步驟描述如何在虛擬設備上建立備份文件，將備份文件複製到 Red Hat Enterprise Linux，然後將資料庫備份還原到新系統。

.步驟
. 在虛擬設備上，按一下*管理*>*資料庫備份*。
. 在*資料庫備份*頁面中，按一下*備份設定*。
. 將備份路徑變更為/jail/support。
. 在“計劃”部分中，選擇“每日計劃”，然後輸入比當前時間晚幾分鐘的時間，以便盡快建立備份。
. 按一下“*應用*”。
. 等待幾個小時即可產生備份。
+
完整備份可能超過 1 GB，並且可能需要三到四個小時才能完成。

. 以 root 使用者身分登入安裝了 Unified Manager 的 Linux 主機，然後使用 SCP 從虛擬裝置上的 /support 複製備份文件.`root@<rhel_server>:/# scp -r admin@<vapp_server_ip_address>:/support/* .`
+
`root@ocum_rhel-21:/# scp -r admin@10.10.10.10:/support/* .`

+
確保您已複製 .7z 備份檔案和 /database-dumps-repo 子目錄中的所有 .7z 儲存庫檔案。

. 在命令提示字元下，恢復備份： `um backup restore -f /<backup_file_path>/<backup_file_name>`
+
`um backup restore -f /UM_9.7.N151113.1348_backup_unix_02-12-2019-04-16.7z`

. 復原作業完成後，登入 Unified Manager Web UI。


您應該執行以下任務：

* 產生新的 HTTPS 安全性憑證並重新啟動 Unified Manager 伺服器。
* 將備份路徑變更為 Linux 系統的預設設定（/data/ocum-backup），或變更為您選擇的新路徑，因為 Linux 系統上沒有 /jail/support 路徑。
* 如果正在使用 WFA，請重新配置工作流程自動化連接的兩側。
* 如果您使用 SAML，請重新設定 SAML 驗證設定。


驗證 Linux 系統上的所有內容均如預期運作後，您可以關閉並刪除 Unified Manager 虛擬裝置。
