---
permalink: health-checker/task_generate_and_upload_support_bundle.html 
sidebar: sidebar 
keywords: generate, upload, support bundle 
summary: 您可以產生包含診斷資訊的支援包，以便將其傳送給技術支援以獲得故障排除協助。您也可以從維護控制台將支援包上傳到NetApp 。 
---
= 產生並上傳支援包
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以產生包含診斷資訊的支援包，以便將其傳送給技術支援以獲得故障排除協助。

從 Unified Manager 9.8 開始，如果您的 Unified Manager 伺服器已連接到互聯網，您也可以從維護控制台將支援套件上傳到NetApp 。

.開始之前
您必須以維護使用者身分存取維護控制台。

由於某些類型的支援資料可能會使用大量叢集資源或需要很長時間才能完成，因此當您選擇完整支援包時，您可以指定要包含或排除的資料類型以減少支援包的大小。您也可以選擇建立一個輕量級支援包，其中僅包含 30 天的日誌和設定資料庫記錄 - 它不包括效能資料、擷取記錄檔和伺服器堆轉儲。

Unified Manager 僅儲存最近產生的兩個支援包。較舊的支援包已從系統中刪除。

.步驟
. 在維護控制台*主選單*中，選擇*支援/診斷*。
. 根據您希望在支援包中擁有的詳細程度，選擇*產生輕量支援包*或*生成支援包*。
. 如果選擇完整支援包，請選擇或取消選擇以下資料類型以在支援包中包含或排除：
+
** *資料庫轉儲*
+
MySQL 伺服器資料庫的轉儲。

** *堆轉儲*
+
主 Unified Manager 伺服器進程狀態的快照。此選項預設為停用狀態，僅應在客戶支援要求時選擇。

** *採集記錄*
+
Unified Manager 與受監控叢集之間的所有通訊的記錄。



+
[NOTE]
====
如果取消選擇所有資料類型，則支援包仍會與其他 Unified Manager 資料一起產生。

====
. 類型 `g`，然後按 Enter 鍵產生支援包。
+
由於產生支援包是一項佔用大量記憶體的操作，因此系統會提示您確認是否確定要在此時產生支援包。

. 類型 `y`，然後按 Enter 鍵產生支援包。
+
如果您現在不想產生支援包，請鍵入 `n`，然後按 Enter。

. 如果您在完整支援包中包含了資料庫轉儲文件，系統將提示您指定要包含效能統計資料的時間段。包含效能統計資訊可能會佔用大量時間和空間，因此您也可以轉儲資料庫而不包含效能統計資料：
+
.. 以 YYYYMMDD 格式輸入開始日期。
+
例如，輸入 `20210101`截至 2021 年 1 月 1 日。進入 `n`如果您不想包含效能統計資料。

.. 輸入要包含的統計資料的天數，從指定開始日期的凌晨 12 點開始。
+
您可以輸入 1 到 10 之間的數字。



+
如果包括效能統計數據，系統將顯示將收集效能統計資料的時間段。

. 建立支援包後，系統會提示您是否要將其上傳到NetApp。類型 `y`，然後按 Enter。
+
系統會提示您輸入支援案例編號。

. 如果您已經有案件編號，請輸入該編號並按 Enter。否則只需按 Enter 鍵。
+
支援包已上傳至NetApp。



如果您的 Unified Manager 伺服器未連接到互聯網，或者您因任何其他原因無法上傳支援包，那麼您可以檢索它並手動傳送。您可以使用 SFTP 用戶端或使用 UNIX 或 Linux CLI 命令檢索它。在 Windows 安裝中，您可以使用遠端桌面 (RDP) 來擷取支援包。

產生的支援包位於 VMware 系統上的 /support 目錄中、Linux 系統上的 /opt/netapp/data/support/ 中以及 Windows 系統上的 ProgramData\ NetApp\OnCommandAppData\ocum\support 中。

*相關資訊*

link:../config/reference_unified_manager_roles_and_capabilities.html["Unified Manager 使用者角色和功能"]
