---
permalink: install-vapp/qsg-vapp.html 
sidebar: sidebar 
keywords: quick start guide, getting started, QSG, VMWare QSG, vApp QSG, quick installation 
summary: VMWare vSphere 平台上 Unified Manager 的快速入門指南。 
---
= VMware 安裝快速入門說明
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以下載 `.tar`包含根證書的文件 `README`文件，以及 `OVA`文件，並將 Unified Manager 部署為虛擬設備。



== 系統需求

* 作業系統：VMware ESXi 8.0
* 記憶體：12 GB
* CPU：總計 9572 MHz
* 可用磁碟空間：5 GB（精簡配置），152 GB（厚配置）


有關詳細的系統需求，請參閱link:../install-vapp/concept_requirements_for_installing_unified_manager.html["安裝 Unified Manager 的要求"]和link:http://mysupport.netapp.com/matrix["互通性矩陣"]。



== 安裝Active IQ Unified Manager



=== 下載安裝程式

. 下載 `.tar`包含根證書的文件 `README`文件，以及 `OVA`文件。
. 將檔案儲存到 vSphere Client 可以存取的本機目錄或網路目錄。
. 在下載的目錄中 `.tar`文件，輸入 `tar -xvzf ActiveIQUnifiedManager-<version>.tar.gz`命令。  + 必需的 `OVA`文件、根證書和 `README`檔案解壓縮到目標目錄。




=== 驗證完整性

您可以驗證 `OVA`依照提供的步驟 `README`文件。



=== 安裝 Unified Manager

. 在 vSphere Client 中，按一下「檔案」>「部署 OVF 範本」。
. 找到 OVA 檔案並使用精靈在 ESXi 伺服器上部署虛擬設備。
. 在「評論詳情」頁面的「發布者」部分中，訊息 `Entrust Code Signing - OVCS2 (Trusted certificate)`確認下載的完整性 `OVA`文件。對於訊息 `Entrust Code Signing - OVCS2 (Invalid certificate)`，將 VMware vCenter Server 升級至 7.0U3E 或更高版本。
. 在「自訂範本」頁面的「屬性」標籤中，根據要執行的安裝類型填入所需的欄位：
+
** 對於靜態配置，請在所有欄位中輸入所需的資訊。不需要新增「*輔助 DNS*」欄位的資訊。
** 對於使用 IPv4 的 DHCP，請勿在任何欄位中新增任何資訊。
** 對於使用 IPv6 的 DHCP，請勾選「啟用自動 IPv6 尋址」方塊。不要在任何其他欄位中添加任何資訊。


. 啟動虛擬機器。
. 按一下「控制台」標籤以查看初始啟動程序。
. 配置時區。
. 輸入 Unified Manager 維護使用者名稱和密碼。


安裝結束時，將顯示連接到 Unified Manager Web UI 的資訊。
