---
permalink: install-windows/qsg-windows.html 
sidebar: sidebar 
keywords: quick start guide, getting started, QSG, Windows QSG, quick installation, Windows installer 
summary: Windows 平台上 Unified Manager 的快速入門指南。 
---
= Windows 安裝快速入門說明
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以下載安裝套件並安裝 Unified Manager 來監控和排除資料儲存容量、可用性、效能和保護問題。



== 系統需求

* 作業系統
+
** Microsoft Windows Server 2019 標準版與資料中心版
** Microsoft Windows Server 2022 標準版與資料中心版
+
Unified Manager 在 64 位元 Windows 作業系統上支援下列語言：

** 英語
** 日本人
** 簡體中文


* 記憶體：12 GB
* CPU：總計 9572 MHz
* 可用磁碟空間：100 GB 磁碟空間用於安裝目錄，50 GB 磁碟空間用於 MySQL 資料目錄


有關詳細的系統需求，請參閱link:../install-windows/concept_requirements_for_installing_unified_manager.html["安裝 Unified Manager 的要求"]和link:http://mysupport.netapp.com/matrix["互通性矩陣"^]。



== 安裝Active IQ Unified Manager



=== 下載安裝程式

. 下載 `ActiveIQUnifiedManager-<version>.exe`安裝包。
. 將安裝檔案複製到目標系統上的目錄。




=== 安裝 Unified Manager

若要安裝 Unified Manager，請確保已安裝 Microsoft .NET 4.5.2 或更高版本。作為安裝過程的一部分，Unified Manager 會根據需要安裝其他第三方軟體套件。有關依賴軟體包的更多信息，請參閱link:../install-windows/reference_windows_software_and_installation_requirements.html["Windows 軟體和安裝要求"]。

. 使用預設本機管理員帳戶登入 Windows。
. 在下載安裝檔案的目錄中，以滑鼠右鍵按一下並以管理員身分執行 Unified Manager 執行檔 (.exe)。
. 出現提示時，輸入使用者名稱和密碼以建立 Unified Manager 維護使用者。
. 在資料庫連線精靈中，輸入 MySQL 根密碼。
. 請按照其餘提示完成安裝。
. 安裝結束時按一下“完成”，將顯示 Unified Manager Web UI。

