---
permalink: install-windows/reference_windows_software_and_installation_requirements.html 
sidebar: sidebar 
keywords: windows, software, installation, requirements, system, active iq unified manager 
summary: 為了在 Windows 上成功安裝 Unified Manager，您應該確保安裝 Unified Manager 的系統符合軟體需求。 
---
= Windows 軟體和安裝要求
:allow-uri-read: 
:icons: font
:imagesdir: ../media/
:pp: &#43;&#43;


[role="lead"]
為了在 Windows 上成功安裝 Unified Manager，您應該確保安裝 Unified Manager 的系統符合軟體需求。



== 作業系統軟體

您可以在下列 Windows 版本上安裝 Unified Manager：

* Microsoft Windows Server 2019 標準版與資料中心版
* Microsoft Windows Server 2022 標準版與資料中心版


Unified Manager 在 64 位元 Windows 作業系統上支援下列語言：

* 英語
* 日本人
* 簡體中文


請參閱互通性矩陣以取得受支援 Windows 版本的完整和最新清單。

http://mysupport.netapp.com/matrix["mysupport.netapp.com/matrix"^]


NOTE: NetApp不支援使用第三方工具（例如 Microsoft System Center Configuration Manager (SCCM)）安裝 Unified Manager。

該伺服器應專用於執行 Unified Manager。伺服器上不應安裝任何其他應用程式。由於公司規定，您的 Windows 系統上可能安裝了活動的防毒軟體。您應該在安裝 Unified Manager 之前停用防毒軟體，以防止安裝失敗。



== 第三方軟體

以下第三方軟體套件與 Unified Manager 捆綁在一起。如果您的系統上未安裝這些第三方軟體包，Unified Manager 會在安裝過程中安裝它們。

* 適用於 Visual Studio 2015 版本 14.26.28720.3 的 Microsoft Visual C&#43;&#43; 可再發行元件套件
* MySQL 社群版 8.4.4
* Python 3.12.4
* OpenJDK 版本 11.0.25
* 7-zip 23.01 或更高版本


[NOTE]
====
從 Unified Manager 9.5 開始，OpenJDK 在 Unified Manager 安裝套件中提供並自動安裝。從 Unified Manager 9.5 開始不再支援 Oracle Java。

====
如果已預先安裝 MySQL，則應確保：

* 它使用預設連接埠。
* 未安裝範例資料庫。
* 服務名稱是「`MYSQL84`」。


Unified Manager 部署在 WildFly Web 伺服器上。  WildFly 26.1.3 與 Unified Manager 捆綁並配置。

[NOTE]
====
在升級任何第三方軟體之前，您應該關閉正在執行的 Unified Manager 實例。第三方軟體安裝完成後，您可以重新啟動Unified Manager。

====


== 安裝要求

* 應安裝 Microsoft .NET 4.5.2 或更高版本。
* 這 `temp`目錄應配置 2 GB 的磁碟空間用於提取安裝檔。若要驗證目錄是否已創建，請在命令列介面上執行以下命令： `echo %temp%`
* 您應該在 Windows 磁碟機中保留 2 GB 的磁碟空間來快取 Unified Manager MSI 檔案。
* 您要安裝 Unified Manager 的 Microsoft Windows Server 應設定完全限定網域名稱 (FQDN)，以便 `ping`對主機名稱和 FQDN 的回應成功。
* 您應該停用 Microsoft IIS 全球網路發布服務並確保連接埠 80 和 443 是空閒的。
* 您應該確保在安裝過程中停用「Windows Installer RDS 相容性」的遠端桌面會話主機設定。
* UDP 連接埠 514 應該是空閒的，並且不應被任何其他服務使用。
* 在安裝 Unified Manager 之前，您應該停用系統上的所有防毒軟體。安裝完成後，請確保手動將以下路徑從防毒掃描中排除：
+
** Unified Manager 資料目錄，例如， `C:\ProgramData\NetApp\OnCommandAppData\`
** Unified Manager 安裝目錄，例如， `\C:\Program Files\NetApp\`
** MySQL 資料目錄，例如， `C:\ProgramData\MySQL\MySQLServerData`



