---
permalink: install-windows/task_change_jboss_password_on_windows.html 
sidebar: sidebar 
keywords: change, jboss, password 
summary: 您可以重設安裝期間設定的特定於實例的 JBoss 密碼。如果您的網站需要此安全功能來覆寫 Unified Manager 安裝設置，您可以選擇重設密碼。此操作也會更改 JBoss 用於存取 MySQL 的密碼。 
---
= 更改 JBoss 密碼
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以重設安裝期間設定的特定於實例的 JBoss 密碼。如果您的網站需要此安全功能來覆寫 Unified Manager 安裝設置，您可以選擇重設密碼。此操作也會更改 JBoss 用於存取 MySQL 的密碼。

.開始之前
* 您應該擁有安裝 Unified Manager 的系統的 Windows 管理員權限。
* 您應該擁有 MySQL 根使用者的密碼。
* 您應該能夠存取NetApp提供的 `password.bat`目錄中的腳本
+
`C:\Program Files\NetApp\essentials\bin`。



.步驟
. 以管理員使用者身分登入 Unified Manager 主機。
. 使用 Windows 服務控制台停止下列 Unified Manager 服務：
+
** NetApp Active IQ收購服務 (Ocie-au)
** NetApp Active IQ管理伺服器服務 (Oncommandsvc)


. 啟動 `password.bat`腳本開始密碼更改流程：
+
`C:\Program Files\NetApp\essentials\bin> password.bat resetJBossPassword`

. 出現提示時，輸入 MySQL 根使用者密碼。
. 出現提示時，輸入新的 JBoss 使用者密碼，然後再次輸入以進行確認。
+
請注意，密碼應介於 8 到 16 個字元之間，並且必須至少包含一個數字、一個大寫字母和一個小寫字母，以及至少一個以下特殊字元：

+
`+!@%^*-_+=[]:<>.?/~+`

. 腳本完成後，使用 Windows 服務控制台啟動 Unified Manager 服務：
+
** NetApp Active IQ管理伺服器服務 (Oncommandsvc)
** NetApp Active IQ收購服務 (Ocie-au)


. 所有服務啟動後，您可以登入 Unified Manager UI。

