---
permalink: config/concept_audit_logging.html 
sidebar: sidebar 
keywords: audit, logging 
summary: 您可以使用稽核日誌偵測稽核日誌是否已外洩。使用者執行的所有活動都受到監控並記錄在稽核日誌中。審核針對Active IQ Unified Manager的所有使用者介面和公開的 API 功能進行。 
---
= 審計日誌
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以使用稽核日誌偵測稽核日誌是否已外洩。使用者執行的所有活動都受到監控並記錄在稽核日誌中。審核針對Active IQ Unified Manager的所有使用者介面和公開的 API 功能進行。

您可以使用*稽核日誌：檔案檢視*來檢視和存取Active IQ Unified Manager中可用的所有稽核日誌檔案。審計日誌：文件視圖中的文件根據其建立日期列出。此視圖顯示從安裝或升級到系統中現在捕獲的所有審計日誌的資訊。每當您在 Unified Manager 中執行操作時，資訊都會更新並可在日誌中取得。使用「檔案完整性狀態」屬性擷取每個日誌檔案的狀態，該屬性受到主動監控以偵測日誌檔案的篡改或刪除。當系統中有稽核日誌時，稽核日誌可以具有下列狀態之一：

[cols="2*"]
|===
| 狀態 | 描述 


 a| 
積極的
 a| 
目前正在記錄日誌的檔案。



 a| 
普通的
 a| 
系統中處於非活動狀態、壓縮並儲存的檔案。



 a| 
被竄改
 a| 
該文件已被手動編輯過的使用者破壞。



 a| 
手動刪除
 a| 
已被授權使用者刪除的檔案。



 a| 
滾動刪除
 a| 
根據滾動配置策略，由於滾動而被刪除的檔案。



 a| 
意外刪除
 a| 
由於未知原因而被刪除的檔案。

|===
審計日誌頁麵包括以下命令按鈕：

* 配置
* 刪除
* 下載


使用 *DELETE* 按鈕可以刪除稽核日誌檢視中所列的任何稽核日誌。您可以刪除審計日誌，並可選擇提供刪除檔案的原因，這有助於將來確定有效的刪除。  REASON 欄位列出了原因以及執行刪除操作的使用者的姓名。

[NOTE]
====
刪除日誌檔案將導致檔案從系統中刪除，但資料庫表中的條目不會被刪除。

====
您可以使用稽核日誌部分中的 *DOWNLOAD* 按鈕從Active IQ Unified Manager下載稽核日誌並匯出稽核日誌檔案。標記為“正常”或“篡改”的檔案以壓縮檔案形式下載 `.gzip`格式。

審計日誌檔案定期歸檔並保存到資料庫以供參考。在存檔之前，審計日誌經過數位簽章以維護安全性和完整性。

產生完整的AutoSupport套件時，支援包將包括存檔和活動審計日誌檔案。但是，當產生輕量級支援包時，它僅包含活動審計日誌。不包括存檔的稽核日誌。
