---
permalink: config/reference_regenerate_https_certificate_dialog_box.html 
sidebar: sidebar 
keywords: regenerate, https certificate, dialog, box 
summary: 「重新產生 HTTPS 憑證」對話方塊可讓您自訂安全訊息，然後使用該資訊產生新的 HTTPS 憑證。 
---
= 重新產生 HTTPS 憑證對話框
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
「重新產生 HTTPS 憑證」對話方塊可讓您自訂安全訊息，然後使用該資訊產生新的 HTTPS 憑證。

當前證書資訊出現在此頁面上。

「使用目前憑證屬性重新產生」和「更新目前憑證屬性」選擇可讓您使用目前資訊重新產生憑證或使用新資訊產生憑證。

* *通用名稱*
+
必需的。您希望保護的完全限定網域名稱 (FQDN)。

+
在 Unified Manager 高可用性設定中，使用虛擬 IP 位址。

* *電子郵件*
+
選修的。用於聯絡您組織的電子郵件地址；通常是憑證管理員或 IT 部門的電子郵件地址。

* *公司*
+
選修的。通常是您公司的註冊名稱。

* *部門*
+
選修的。貴公司部門的名稱。

* *城市*
+
選修的。貴公司所在的城市。

* *狀態*
+
選修的。貴公司所在的州或省位置（不縮寫）。

* *國家*
+
選修的。貴公司所在的國家。這通常是該國家的兩個字母的 ISO 代碼。

* *其他名稱*
+
必需的。除了現有的本地主機或其他網路位址之外，還可用於存取此伺服器的附加非主要網域名稱。用逗號分隔每個備用名稱。

+
如果您想要從憑證中的備用名稱欄位中刪除本機識別訊息，請勾選「排除本機識別資訊（例如 localhost）」複選框。選取此核取方塊後，只有您在欄位中輸入的內容才會在備用名稱欄位中使用。當留空時，產生的憑證將根本沒有備用名稱欄位。

* *金鑰大小（金鑰演算法：RSA）*
+
金鑰演算法設定為RSA。您可以從下列密鑰大小中選擇一個：2048、3072 或 4096 位元。預設密鑰大小設定為 2048 位元。

* *有效期限*
+
預設有效期為397天。如果您從先前的版本升級，您可能會看到先前的憑證有效性保持不變。



有關詳細信息，請參閱 link:../config/task_generate_an_https_security_certificate_ocf.html["產生 HTTPS 憑證"]。
