---
permalink: config/reference_remote_authentication_page.html 
sidebar: sidebar 
keywords: remote authentication, page 
summary: 您可以使用遠端身份驗證頁面設定 Unified Manager 與您的身份驗證伺服器通信，以對嘗試登入 Unified Manager Web UI 的遠端使用者進行身份驗證。 
---
= 遠端身份驗證頁面
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以使用遠端身份驗證頁面設定 Unified Manager 與您的身份驗證伺服器通信，以對嘗試登入 Unified Manager Web UI 的遠端使用者進行身份驗證。

您必須具有應用程式管理員或儲存管理員角色。

選取啟用遠端身份驗證複選框後，您可以使用身份驗證伺服器啟用遠端身份驗證。

* *認證服務*
+
使您能夠設定管理伺服器以在目錄服務提供者（例如 Active Directory、OpenLDAP）中對使用者進行驗證，或指定您自己的驗證機制。只有當您啟用了遠端身份驗證時，您才可以指定身份驗證服務。

+
** *活動目錄*
+
*** 管理員姓名
+
指定認證伺服器的管理員名稱。

*** 密碼
+
指定存取認證伺服器的密碼。

*** 基本可分辨名稱
+
指定遠端使用者在認證伺服器中的位置。例如，如果認證伺服器的網域是+ou@domain.com+，那麼基本可分辨名稱就是*cn=ou,dc=domain,dc=com*。

*** 禁用嵌套組查找
+
指定是否啟用或停用嵌套組查找選項。預設此選項是禁用的。如果您使用 Active Directory，則可以透過停用對嵌套群組的支援來加快身份驗證速度。

*** 使用安全連接
+
指定用於與身份驗證伺服器通訊的身份驗證服務。



** *OpenLDAP*
+
*** 綁定可分辨名稱
+
指定與基本可分辨名稱一起使用的綁定可分辨名稱，以在身份驗證伺服器中尋找遠端使用者。

*** 綁定密碼
+
指定存取認證伺服器的密碼。

*** 基本可分辨名稱
+
指定遠端使用者在認證伺服器中的位置。例如，如果認證伺服器的網域是+ou@domain.com+，那麼基本可分辨名稱就是*cn=ou,dc=domain,dc=com*。

*** 使用安全連接
+
指定使用安全 LDAP 與 LDAP 驗證伺服器進行通訊。



** *其他的*
+
*** 綁定可分辨名稱
+
指定綁定可分辨名稱，該名稱與基本可分辨名稱一起使用，以在您配置的身份驗證伺服器中尋找遠端使用者。

*** 綁定密碼
+
指定存取認證伺服器的密碼。

*** 基本可分辨名稱
+
指定遠端使用者在認證伺服器中的位置。例如，如果認證伺服器的網域是+ou@domain.com+，那麼基本可分辨名稱就是*cn=ou,dc=domain,dc=com*。

*** 協議版本
+
指定您的驗證伺服器支援的輕量級目錄存取協定 (LDAP) 版本。您可以指定是否必須自動偵測協定版本或將版本設定為 2 或 3。

*** 使用者名稱屬性
+
指定驗證伺服器中的屬性名稱，該屬性包含要由管理伺服器進行驗證的使用者登入名稱。

*** 群組成員身分屬性
+
指定一個值，該值根據使用者的身份驗證伺服器中指定的屬性和值為遠端使用者指派管理伺服器群組成員身分。

*** UGID
+
如果遠端使用者作為身分驗證伺服器中 GroupOfUniqueNames 物件的成員，則此選項可讓您根據該 GroupOfUniqueNames 物件中的指定屬性將管理伺服器群組成員身分指派給遠端使用者。

*** 禁用嵌套組查找
+
指定是否啟用或停用嵌套組查找選項。預設此選項是禁用的。如果您使用 Active Directory，則可以透過停用對嵌套群組的支援來加快身份驗證速度。

*** 成員
+
指定身份驗證伺服器用於儲存有關群組的各個成員的資訊的屬性名稱。

*** 使用者物件類別
+
指定遠端認證伺服器中使用者的物件類別。

*** 群組物件類別
+
指定遠端認證伺服器中所有群組的物件類別。

+

NOTE: 您為_Member_、_User Object Class_ 和 _Group Object Class_ 屬性輸入的值應與在 Active Directory、OpenLDAP 和 LDAP 配置中新增的值相同。否則，身份驗證可能會失敗。

*** 使用安全連接
+
指定用於與身份驗證伺服器通訊的身份驗證服務。





+
[NOTE]
====
如果要修改身份驗證服務，請確保刪除所有現有的身份驗證伺服器並新增新的身份驗證伺服器。

====




== 身份驗證伺服器區域

身份驗證伺服器區域顯示管理伺服器與之通訊以尋找和驗證遠端使用者的身份驗證伺服器。遠端使用者或群組的憑證由身份驗證伺服器維護。

* *命令按鈕*
+
使您能夠新增、編輯或刪除身份驗證伺服器。

+
** 添加
+
使您能夠新增身份驗證伺服器。

+
如果您要新增的身份驗證伺服器是高可用性對的一部分（使用相同的資料庫），那麼您也可以新增合作夥伴驗證伺服器。當其中一個身份驗證伺服器無法存取時，這使得管理伺服器能夠與合作夥伴進行通訊。

** 編輯
+
使您能夠編輯選定身份驗證伺服器的設定。

** 刪除
+
刪除選定的認證伺服器。



* *姓名或 IP 位址*
+
顯示用於在管理伺服器上驗證使用者的驗證伺服器的主機名稱或 IP 位址。

* *港口*
+
顯示認證伺服器的連接埠號碼。

* *測試認證*
+
此按鈕透過驗證遠端使用者或群組來驗證您的身份驗證伺服器的配置。

+
測試時，如果僅指定用戶名，管理伺服器會在認證伺服器中搜尋遠端用戶，但不會對用戶進行認證。如果您同時指定使用者名稱和密碼，管理伺服器將搜尋並驗證遠端使用者。

+
如果遠端身份驗證已停用，則您無法測試身份驗證。


