---
permalink: config/reference_network_configuration_menu.html 
sidebar: sidebar 
keywords: network configuration menu 
summary: 網路配置選單可讓您管理網路設定。當 Unified Manager 使用者介面不可用時，您應該使用此功能表。 
---
= 網路設定選單
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
網路配置選單可讓您管理網路設定。當 Unified Manager 使用者介面不可用時，您應該使用此功能表。

[NOTE]
====
如果 Unified Manager 安裝在 Red Hat Enterprise Linux 或 Microsoft Windows 上，則此功能表不可用。

====
有以下選單選項可供選擇。

* *顯示 IP 位址設定*
+
顯示虛擬設備的目前網路設置，包括 IP 位址、網路、廣播位址、網路遮罩、網關和 DNS 伺服器。

* *更改 IP 位址設定*
+
使您能夠更改虛擬設備的任何網路設置，包括 IP 位址、網路遮罩、網關或 DNS 伺服器。如果您使用維護控制台將網路設定從 DHCP 切換到靜態網絡，則無法編輯主機名稱。您必須選擇“*提交更改*”才能使更改生效。

* *顯示網域搜尋設定*
+
顯示用於解析主機名稱的網域搜尋清單。

* *更改網域搜尋設定*
+
使您能夠變更解析主機名稱時要搜尋的網域名稱。您必須選擇“*提交更改*”才能使更改生效。

* *顯示靜態路由*
+
顯示目前靜態網路路由。

* *更改靜態路由*
+
使您能夠新增或刪除靜態網路路由。您必須選擇“*提交更改*”才能使更改生效。

+
** *新增路線*
+
使您能夠新增靜態路由。

** *刪除路線*
+
使您能夠刪除靜態路由。

** *後退*
+
帶您返回*主選單*。

** *出口*
+
退出維護控制台。



* *停用網路介面*
+
停用任何可用的網路介面。如果只有一個網路介面可用，則無法停用它。您必須選擇“*提交更改*”才能使更改生效。

* *啟用網路介面*
+
啟用可用的網路介面。您必須選擇“*提交更改*”才能使更改生效。

* *提交更改*
+
應用對虛擬設備的網路設定所做的任何變更。您必須選擇此選項才能實施所做的任何更改，否則不會發生更改。

* *Ping 主機*
+
對目標主機執行 ping 操作以確認 IP 位址變更或 DNS 配置。

* *恢復預設值*
+
將所有設定重設為出廠預設值。您必須選擇“*提交更改*”才能使更改生效。

* *後退*
+
帶您返回*主選單*。

* *出口*
+
退出維護控制台。


