---
permalink: config/task_add_authentication_servers.html 
sidebar: sidebar 
keywords: add, authentication servers 
summary: 您可以在管理伺服器上新增身份驗證伺服器並啟用遠端身份驗證，以便身份驗證伺服器內的遠端使用者可以存取 Unified Manager。 
---
= 新增身份驗證伺服器
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以在管理伺服器上新增身份驗證伺服器並啟用遠端身份驗證，以便身份驗證伺服器內的遠端使用者可以存取 Unified Manager。

.開始之前
* 必須提供以下資訊：
+
** 認證伺服器的主機名稱或IP位址
** 認證伺服器的連接埠號


* 您必須啟用遠端身份驗證並設定身份驗證服務，以便管理伺服器可以對身份驗證伺服器中的遠端使用者或群組進行身份驗證。
* 您必須具有應用程式管理員角色。


如果您要新增的身份驗證伺服器是高可用性 (HA) 對的一部分（使用相同的資料庫），那麼您也可以新增合作夥伴驗證伺服器。當其中一個身份驗證伺服器無法存取時，這使得管理伺服器能夠與合作夥伴進行通訊。

.步驟
. 在左側導覽窗格中，按一下「*常規*」>「*遠端驗證*」。
. 啟用或停用*使用安全連線*選項：
+
[cols="2*"]
|===
| 如果你想... | 然後這樣做... 


 a| 
啟用它
 a| 
.. 選擇*使用安全連線*選項。
.. 在身份驗證伺服器區域，按一下「*新增*」。
.. 在新增認證伺服器對話方塊中，輸入伺服器的認證名稱或IP位址（IPv4或IPv6）。
.. 在授權主機對話方塊中，按一下檢視憑證。
.. 在「檢視證書」對話方塊中，驗證證書訊息，然後按一下「*關閉*」。
.. 在授權主機對話方塊中，按一下「是」。
+
[NOTE]
====
當您啟用*使用安全連線驗證*選項時，Unified Manager 會與身分驗證伺服器通訊並顯示憑證。  Unified Manager 使用 636 作為安全通訊的預設端口，使用連接埠號碼 389 作為非安全通訊的預設連接埠。

====




 a| 
禁用它
 a| 
.. 清除*使用安全連線*選項。
.. 在身份驗證伺服器區域，按一下「*新增*」。
.. 在新增驗證伺服器對話方塊中，指定伺服器的主機名稱或 IP 位址（IPv4 或 IPv6）以及連接埠詳細資訊。
.. 按一下“*新增*”。


|===
+
您新增的身份驗證伺服器將顯示在伺服器區域。

. 執行測試身份驗證以確認您可以在新增的身份驗證伺服器中對使用者進行身份驗證。

