---
permalink: config/task_change_um_host_name_on_rhel.html 
sidebar: sidebar 
keywords: change, unified manager, host name, linux systems 
summary: 在某些時候，您可能會想要變更已安裝 Unified Manager 的 Red Hat Enterprise Linux 機器的主機名稱。例如，您可能想要重新命名主機，以便在列出 Linux 機器時更輕鬆地按類型、工作群組或受監控的叢集群組識別 Unified Manager 伺服器。 
---
= 在 Linux 系統上變更 Unified Manager 主機名
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
在某些時候，您可能會想要變更已安裝 Unified Manager 的 Red Hat Enterprise Linux 機器的主機名稱。例如，您可能想要重新命名主機，以便在列出 Linux 機器時更輕鬆地按類型、工作群組或受監控的叢集群組識別 Unified Manager 伺服器。

.開始之前
您必須具有安裝 Unified Manager 的 Linux 系統的 root 使用者存取權限。

您可以使用主機名稱（或主機 IP 位址）存取 Unified Manager Web UI。如果您在部署期間為網路配置了靜態 IP 位址，那麼您將為網路主機指定名稱。如果您使用 DHCP 設定網絡，則主機名稱應從 DNS 伺服器中取得。

無論主機名稱為何分配，如果您變更主機名稱並打算使用新主機名稱存取 Unified Manager Web UI，則必須產生新的安全性憑證。

如果您使用伺服器的 IP 位址而不是主機名稱存取 Web UI，則變更主機名稱時無需產生新憑證。但是，最佳做法是更新證書，以便證書中的主機名稱與實際主機名稱相符。直到 Linux 機器重新啟動後，新憑證才會生效。

如果您在 Unified Manager 中變更主機名，則必須在OnCommand Workflow Automation (WFA) 中手動更新主機名稱。主機名稱不會在 WFA 中自動更新。

.步驟
. 以 root 使用者身分登入要修改的 Unified Manager 系統。
. 輸入以下指令停止 Unified Manager 軟體和相關的 MySQL 軟體：
+
`systemctl stop ocieau ocie mysqld`

. 使用 Linux 更改主機名 `hostnamectl`命令：
+
`hostnamectl set-hostname new_FQDN`

+
`hostnamectl set-hostname nuhost.corp.widget.com`

. 為伺服器重新產生HTTPS憑證：
+
`/opt/netapp/essentials/bin/cert.sh create`

. 重啟網路服務：
+
`systemctl restart NetworkManager.service`

. 服務重啟後，驗證新的主機名稱是否能ping通自己：
+
`ping new_hostname`

+
`ping nuhost`

+
此命令應傳回先前為原始主機名稱設定的相同 IP 位址。

. 完成並驗證主機名稱變更後，輸入以下命令重新啟動 Unified Manager：
+
`systemctl start mysqld ocie ocieau`


