---
permalink: config/task_configure_unified_manager_to_send_alert_notifications.html 
sidebar: sidebar 
keywords: configure, unified manager, send, alert, notifications 
summary: 您可以設定 Unified Manager 來傳送有關您環境中的事件的警報通知。在傳送通知之前，您必須設定其他幾個 Unified Manager 選項。 
---
= 配置 Unified Manager 以發送警報通知
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以設定 Unified Manager 來傳送有關您環境中的事件的警報通知。在傳送通知之前，您必須設定其他幾個 Unified Manager 選項。

.開始之前
您必須具有應用程式管理員角色。

部署 Unified Manager 並完成初始設定後，您應該考慮設定您的環境以根據收到的事件觸發警報並產生通知電子郵件或 SNMP 陷阱。

.步驟
. link:task_configure_event_notification_settings.html["配置事件通知設定"]。
+
如果您希望在您的環境中發生某些事件時發送警報通知，則必須設定 SMTP 伺服器並提供用於傳送警報通知的電子郵件地址。如果您想使用 SNMP 陷阱，您可以選擇該選項並提供必要的資訊。

. link:task_enable_remote_authentication.html["啟用遠端身份驗證"]。
+
如果您希望遠端 LDAP 或 Active Directory 使用者存取 Unified Manager 實例並接收警報通知，則必須啟用遠端驗證。

. link:task_add_authentication_servers.html["新增身份驗證伺服器"]。
+
您可以新增身份驗證伺服器，以便身份驗證伺服器內的遠端使用者可以存取 Unified Manager。

. link:task_add_users.html["新增用戶"]。
+
您可以新增幾種不同類型的本機或遠端使用者並指派特定的角色。建立警報時，您會指定一個使用者來接收警報通知。

. link:task_add_alerts.html["添加警報"]。
+
新增了用於發送通知的電子郵件地址、新增了用於接收通知的使用者、配置了網路設定以及配置了環境所需的 SMTP 和 SNMP 選項後，您就可以指派警報了。


