---
permalink: config/task_configure_event_notification_settings.html 
sidebar: sidebar 
keywords: configure, event, notification, settings 
summary: 您可以設定 Unified Manager 在產生事件或將事件指派給使用者時傳送警報通知。您可以設定用於傳送警報的 SMTP 伺服器，並且可以設定各種通知機制 - 例如，警報通知可以作為電子郵件或 SNMP 陷阱傳送。 
---
= 配置事件通知設定
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以設定 Unified Manager 在產生事件或將事件指派給使用者時傳送警報通知。您可以設定用於傳送警報的 SMTP 伺服器，並且可以設定各種通知機制 - 例如，警報通知可以作為電子郵件或 SNMP 陷阱傳送。

.開始之前
您必須具有以下資訊：

* 發送警報通知的電子郵件地址
+
電子郵件地址出現在已發送警報通知的「寄件者」欄位中。如果電子郵件因任何原因無法送達，則該電子郵件地址也將用作無法送達郵件的收件者。

* SMTP 伺服器主機名稱以及存取該伺服器的使用者名稱和密碼
* 將接收 SNMP 陷阱的陷阱目標主機的主機名稱或 IP 位址，以及 SNMP 版本、出站陷阱連接埠、社群和其他所需的 SNMP 設定值
+
若要指定多個陷阱目標，請用逗號分隔每個主機。在這種情況下，清單中所有主機的所有其他 SNMP 設定（例如版本和出站陷阱連接埠）必須相同。



您必須具有應用程式管理員或儲存管理員角色。

.步驟
. 在左側導覽窗格中，按一下「*常規*」>「*通知*」。
. 在通知頁面中，配置適當的設定。
+
*筆記：*

+
** 如果寄件者地址預先填寫了地址“+ActiveIQUnifiedManager@localhost.com+”，則應將其變更為真實有效的電子郵件地址，以確保所有電子郵件通知都成功送達。
** 如果無法解析 SMTP 伺服器的主機名，則可以指定 SMTP 伺服器的 IP 位址（IPv4 或 IPv6）來取代主機名稱。


. 點選“儲存”。
. 如果您選擇了「使用 STARTTLS」或「使用 SSL」選項，則按一下「儲存」按鈕後將顯示憑證頁面。驗證證書詳細資訊並接受證書以保存通知設定。
+
您可以點擊*查看證書詳情*按鈕來查看證書詳情。如果現有憑證已過期，請取消選取 *使用 STARTTLS* 或 *使用 SSL* 框，儲存通知設置，然後再次選取 *使用 STARTTLS* 或 *使用 SSL* 框以查看新憑證。


