---
permalink: config/task_generate_an_https_security_certificate_ocf.html 
sidebar: sidebar 
keywords: generate, https, security, certificate 
summary: 首次安裝Active IQ Unified Manager時，會安裝預設 HTTPS 憑證。您可以產生一個新的 HTTPS 安全性憑證來取代現有的憑證。 
---
= 產生HTTPS安全證書
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
首次安裝Active IQ Unified Manager時，會安裝預設 HTTPS 憑證。您可以產生一個新的 HTTPS 安全性憑證來取代現有的憑證。

.開始之前
您必須具有應用程式管理員角色。

重新產生憑證的原因可能有多種，例如，如果您想要更好的可分辨名稱 (DN) 值，或者您想要更大的金鑰大小，或更長的有效期，或目前憑證已過期。

如果您無法存取 Unified Manager Web UI，則可以使用維護控制台重新產生具有相同值的 HTTPS 憑證。在重新產生憑證時，您可以定義金鑰大小和金鑰的有效期限。如果您使用 `Reset Server Certificate`選項，則會建立一個有效期為 397 天的新 HTTPS 憑證。此憑證將具有大小為 2048 位元的 RSA 金鑰。

.步驟
. 在左側導覽窗格中，按一下「*常規*」>「*HTTPS 憑證*」。
. 按一下「重新產生 HTTPS 憑證」。
+
系統彈出「重新產生HTTPS證書」對話框。

. 根據您想要產生憑證的方式選擇以下選項之一：
+
[cols="2*"]
|===
| 如果你想... | 這樣做... 


 a| 
使用當前值重新產生證書
 a| 
按一下「使用目前憑證屬性重新產生」選項。



 a| 
使用不同的值產生證書
 a| 
按一下“更新目前憑證屬性”選項。

如果您不輸入新值，則通用名稱和備用名稱欄位將使用現有憑證中的值。 “通用名稱”應設定為主機的 FQDN。其他欄位不需要值，但您可以輸入值，例如，如果您希望在憑證中填入這些值，則為 EMAIL、COMPANY、DEPARTMENT、City、State 和 Country 輸入這些值。您也可以從可用的金鑰大小（金鑰演算法為「RSA」）和有效期限中進行選擇。

[NOTE]
====
** 密鑰大小的允許值為 `2048`， `3072`和 `4096`。
** 有效期限最短1天，最長36500天。
+
儘管允許有效期為 36500 天，但建議您使用不超過 397 天或 13 個月的有效期。因為如果您選擇的有效期超過 397 天，併計劃匯出此憑證的 CSR 並由知名 CA 進行簽名，則 CA 返回給您的簽名憑證的有效期將減少到 397 天。

** 如果您想要從憑證中的備用名稱欄位中刪除本機識別訊息，可以勾選「排除本機識別資訊（例如 localhost）」複選框。選取此核取方塊後，只有您在欄位中輸入的內容才會在備用名稱欄位中使用。當留空時，產生的憑證將根本沒有備用名稱欄位。


====
|===
. 按一下「是」重新產生憑證。
. 重新啟動 Unified Manager 伺服器，以使新憑證生效。
. 透過查看HTTPS證書來驗證新的證書資訊。

