---
permalink: config/task_enable_remote_logging_of_audit_logs.html 
sidebar: sidebar 
keywords: enable, remote, logging, audit, logs 
summary: 您可以勾選「設定稽核日誌」對話方塊中的「啟用遠端日誌記錄」核取方塊來啟用遠端稽核日誌記錄。您可以使用此功能將稽核日誌傳輸到遠端 Syslog 伺服器。這將使您能夠在空間受限的情況下管理稽核日誌。 
---
= 啟用稽核日誌的遠端記錄
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以在「設定稽核日誌」對話方塊中選取「啟用遠端日誌記錄」核取方塊來啟用遠端稽核日誌記錄。您可以使用此功能將稽核日誌傳輸到遠端 Syslog 伺服器。這將使您能夠在空間受限的情況下管理稽核日誌。

稽核日誌的遠端記錄提供了防篡改備份，以防Active IQ Unified Manager伺服器上的稽核日誌檔案被篡改。

.步驟
. 在*設定稽核日誌*對話方塊中，選取*啟用遠端日誌記錄*複選框。
+
顯示用於配置遠端日誌記錄的附加欄位。

. 輸入您想要連接的遠端伺服器的 *HOSTNAME* 和 *PORT*。
. 在*伺服器 CA 憑證*欄位中，按一下*瀏覽*以選擇目標伺服器的公共憑證。
+
證書應上傳至 `.pem`格式。此憑證應從目標 Syslog 伺服器取得，且不應過期。憑證應包含所選的「主機名稱」作為 `SubjectAltName`（SAN）屬性。

. 輸入以下欄位的值：*CHARSET*、*CONNECTION TIMEOUT*、*RECONNECTION DELAY*。
+
這些欄位的值應以毫秒為單位。

. 在 *FORMAT* 和 *PROTOCOL* 欄位中選擇所需的 Syslog 格式和 TLS 協定版本。
. 如果目標 Syslog 伺服器需要基於憑證的驗證，請勾選「*啟用用戶端驗證*」複選框。
+
在儲存審計日誌配置之前，您需要下載用戶端身份驗證憑證並將其上傳到 Syslog 伺服器，否則連線將失敗。根據 Syslog 伺服器的類型，您可能需要建立用戶端身份驗證憑證的雜湊值。

+
範例：syslog-ng 需要使用下列命令建立憑證的 <hash> `openssl x509 -noout -hash -in cert.pem` ，然後您應該將客戶端身份驗證憑證符號連結到以 <hash> .0 命名的檔案。

. 按一下「*儲存*」以設定與伺服器的連線並啟用遠端日誌記錄。
+
您將被重新導向到稽核日誌頁面。

+
[NOTE]
====
*連線逾時*值會影響配置。如果配置回應的時間比定義值長，則可能會因連線錯誤而導致配置失敗。若要建立成功的連接，請增加*連接逾時*值，然後再次嘗試配置。

====

