---
permalink: install-linux/qsg-linux.html 
sidebar: sidebar 
keywords: quick start guide, getting started, QSG, Linux QSG, RHEL QSG, quick installation 
summary: Linux 平台上 Unified Manager 的快速入門指南。 
---
= Linux 安裝的快速入門說明
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以下載安裝套件並在實體或虛擬 Red Hat Enterprise Linux 平台上安裝 Unified Manager。



== 系統需求

* 作業系統：Red Hat Enterprise Linux 8.x 和 9.4 版本，基於 x86_64 架構，使用作業系統安裝程式的「軟體選擇」選項中的「帶有 GUI 的伺服器」基礎環境進行安裝
* RAM：12 GB，CPU：總計 9572 MHz
* 可用磁碟空間：100 GB 磁碟空間 `/opt/netapp/data`目錄，根分割區中 50 GB。對於單獨安裝 `/opt`和 `/var/log`目錄，確保 `/opt`有 15 GB， `/var/log`有 16 GB，並且 `/tmp`有 10 GB 的可用空間。


有關詳細的系統要求以及在安全站點安裝產品的信息，請參閱link:../install-linux/concept_requirements_for_install_unified_manager.html["安裝 Unified Manager 的要求"]以及link:http://mysupport.netapp.com/matrix["互通性矩陣"]。



== 安裝Active IQ Unified Manager



=== 下載安裝程式

. 下載 `ActiveIQUnifiedManager-<version>.zip`安裝套件以及代碼簽署證書(`.pem`) 和數位簽名(`.sig`）。
. 在下載安裝檔的目錄中，運行：
+
`# unzip ActiveIQUnifiedManager-<version>.zip`





=== 驗證完整性

執行以下命令驗證安裝程式包的完整性：

* 跑步 `openssl x509 -pubkey -noout -in AIQUM-RHEL-CLIENT-INTER-ROOT.pem > <public_key_file_name>`使用程式碼簽署憑證中的公鑰建立檔案。
* 跑步 `openssl dgst -sha256 -verify <public_key_file_name> -signature <signature_file_name> ActiveIQUnifiedManager-<version>.zip`驗證安裝程式包上的簽章。




=== 驗證儲存庫配置

配置 Red Hat Enterprise Linux 儲存庫的過程是特定於站點的。您可以使用 `pre_install_check.sh`安裝套件中包含的腳本來驗證您的作業系統的配置。如果您的系統已連接到互聯網，您將自動收到設定 Red Hat Enterprise Linux 儲存庫的說明。

`# sudo ./pre_install_check.sh`



=== 安裝 Unified Manager

Unified Manager 使用 `yum`實用程式來安裝軟體和任何相關軟體。由於 Red Hat Enterprise Linux 的映像各不相同，因此安裝的軟體包取決於映像中存在的軟體。這 `yum`實用程式確定安裝所依賴的軟體包。如果您需要有關依賴軟體包的更多信息，請參閱link:../install-linux/reference_red_hat_software_and_installation_requirements.html["Linux 軟體和安裝需求"]。

若要安裝 Unified Manager，請以 root 使用者身分或使用下列命令執行 `sudo`，從安裝檔案解壓縮的目錄中：

`# yum install netapp-um<version>.x86_64.rpm`

或者

`% sudo yum install netapp-um<version>.x86_64.rpm`

安裝結束時，將顯示連接到 Unified Manager Web UI 的資訊。如果您無法連線到 Web UI，請參閱 `README`有關連接埠 443 限制的更多信息，請參閱軟體隨附的文件。
