---
permalink: install-linux/reference_protocol_and_port_requirements.html 
sidebar: sidebar 
keywords: unified manager, port, requirements, protocol, server 
summary: 所需的連接埠和協定支援 Unified Manager 伺服器與託管儲存系統、伺服器和其他元件之間的通訊。 
---
= 協定和連接埠要求
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
所需的連接埠和協定支援 Unified Manager 伺服器與託管儲存系統、伺服器和其他元件之間的通訊。



== 與 Unified Manager 伺服器的連接

在典型安裝中，連接到 Unified Manager Web UI 時無需指定連接埠號，因為請務必使用預設連接埠。例如，由於 Unified Manager 始終嘗試在其預設連接埠上執行，因此您可以輸入 `+https://<host>+`而不是 `+https://<host>:443+`。

Unified Manager 伺服器使用特定協定存取下列介面：

[cols="4*"]
|===
| 介面 | 協定 | 港口 | 描述 


 a| 
Unified Manager Web UI
 a| 
HTTP
 a| 
80
 a| 
用於存取 Unified Manager Web UI；自動重定向到安全連接埠 443。



 a| 
Unified Manager Web UI 和使用 API 的程式
 a| 
HTTPS
 a| 
443
 a| 
用於安全存取 Unified Manager Web UI 或進行 API 呼叫；API 呼叫只能使用 HTTPS 進行。



 a| 
維護控制台
 a| 
SSH/SFTP
 a| 
22
 a| 
用於存取維護控制台和檢索支援包。



 a| 
Linux 命令列
 a| 
SSH/SFTP
 a| 
22
 a| 
用於存取 Red Hat Enterprise Linux 命令列並檢索支援包。



 a| 
MySQL 資料庫
 a| 
MySQL
 a| 
3306
 a| 
用於啟用OnCommand Workflow Automation和OnCommand API Services 對 Unified Manager 的存取。



 a| 
系統日誌
 a| 
UDP
 a| 
514
 a| 
用於從ONTAP系統存取基於訂閱的 EMS 訊息並根據這些訊息建立事件。



 a| 
休息
 a| 
HTTPS
 a| 
9443
 a| 
用於從經過驗證的ONTAP系統存取基於即時 REST API 的 EMS 事件。



 a| 
MySQL 資料庫
 a| 
MySQL
 a| 
3306
 a| 
用於啟用OnCommand Workflow Automation和OnCommand API Services 對 Unified Manager 的存取。



 a| 
AMQP QPID 代理
 a| 
TCP/IP
 a| 
56072
 a| 
用於內部訊息通訊。



 a| 
AMQP QPID 代理
 a| 
透過 TCP 的 WebSocket
 a| 
56080
 a| 
用於在此連接埠上偵聽從ONTAP （雲端代理）接收的訊息。



 a| 
AMQP QPID 代理
 a| 
透過 TCP 的 WebSocket
 a| 
56443
 a| 
用於在此連接埠上偵聽從ONTAP （雲端代理）接收的訊息。透過此連接埠的通訊支援 TLS 或 SSL 提供的加密。

|===
[NOTE]
====
在 Linux 系統上安裝 Unified Manager 時，MySQL 的預設連接埠 3306 僅限於本機。這不會影響任何升級方案，因為先前的配置會保留。可以修改此配置，並且可以使用 `Control access to MySQL port 3306`維護控制台上的選項。有關信息，請參閱link:../config/reference_additional_menu_options.html["附加選單選項"]。可以使用 Unified Manager 維護控制台變更用於 HTTP 和 HTTPS 通訊的連接埠（連接埠 80 和 443）。有關詳細信息，請參閱 link:../config/concept_maintenance_console_menu.html["維護控制台選單"]。

====


== 來自 Unified Manager 伺服器的連接

您應該配置防火牆以開啟端口，以便 Unified Manager 伺服器與託管儲存系統、伺服器和其他元件之間進行通訊。如果連接埠未打開，則通訊失敗。

根據您的環境，您可以選擇修改 Unified Manager 伺服器用於連接到特定目的地的連接埠和協定。

Unified Manager 伺服器使用下列協定和連接埠連接到託管儲存系統、伺服器和其他元件：

[cols="4*"]
|===
| 目的地 | 協定 | 港口 | 描述 


 a| 
儲存系統
 a| 
HTTPS
 a| 
443/TCP
 a| 
用於監控和管理儲存系統。



 a| 
儲存系統
 a| 
NDMP
 a| 
10000/TCP
 a| 
用於某些快照復原操作。



 a| 
AutoSupport伺服器
 a| 
HTTPS
 a| 
443
 a| 
用於發送AutoSupport資訊。需要網路存取才能執行此功能。



 a| 
身份驗證伺服器
 a| 
LDAP
 a| 
389
 a| 
用於發出身份驗證請求以及使用者和群組查找請求。



 a| 
LDAPS
 a| 
636
 a| 
用於安全 LDAP 通訊。



 a| 
郵件伺服器
 a| 
SMTP
 a| 
25
 a| 
用於發送警報通知電子郵件。



 a| 
SNMP 陷阱發送器
 a| 
SNMPv1 或 SNMPv3
 a| 
162/UDP
 a| 
用於發送警報通知 SNMP 陷阱。



 a| 
外部資料提供伺服器
 a| 
TCP
 a| 
2003
 a| 
用於將效能資料傳送至外部資料提供者，例如 Graphite。



 a| 
NTP 伺服器
 a| 
NTP
 a| 
123/UDP
 a| 
用於將 Unified Manager 伺服器上的時間與外部 NTP 時間伺服器同步。  （僅限 VMware 系統）



 a| 
系統日誌
 a| 
UDP
 a| 
514
 a| 
由 Unified Manager 使用，將稽核日誌傳送到遠端系統日誌伺服器。

|===