---
permalink: install-linux/task_remove_unified_manager.html 
sidebar: sidebar 
keywords: remove, unified manager 
summary: 您可以使用單一指令從 Red Hat Enterprise Linux 主機停止並解除安裝 Unified Manager。 
---
= 刪除 Unified Manager
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以使用單一指令從 Red Hat Enterprise Linux 主機停止並解除安裝 Unified Manager。

.開始之前
* 您必須具有要從中刪除 Unified Manager 的伺服器的 root 使用者存取權限。
* 必須在 Linux 系統上停用安全增強 Linux (SELinux)。使用下列命令將 SELinux 運行時模式變更為“Permissive” `setenforce 0`命令。
* 在刪除該軟體之前，必須從 Unified Manager 伺服器中刪除所有叢集（資料來源）。
* 您應該手動刪除為允許或封鎖 MySQL 連接埠 3306 而建立的防火牆規則。防火牆規則不會被自動刪除。


.步驟
. 以 root 使用者身分登入要刪除 Unified Manager 的伺服器。
. 停止並從伺服器中刪除 Unified Manager：
+
`rpm -e netapp-um`

+
此步驟將移除所有相關的NetApp RPM 軟體包。它不會刪除必備的軟體模組，例如 Java、MySQL 和 p7zip。

. *可選：*如果適用，請移除支援軟體模組，例如 Java、MySQL 和 p7zip：
+
`rpm -e p7zip mysql-community-client mysql-community-server mysql-community-common mysql-community-libs java-x.y`



此操作完成後，軟體將被刪除。所有數據來自 `/opt/netapp/data`目錄被移動到 `/opt/netapp/data/BACKUP`卸載後的資料夾。卸載 Unified Manager 也會刪除 Java 和 MySQL 軟體包，除非系統上的任何其他應用程式需要並使用這些軟體包。但是，MySQL 資料不會被刪除。
