---
permalink: install-linux/task_install_unified_manager_linux.html 
sidebar: sidebar 
keywords: install, unified manager 
summary: 您可以在實體或虛擬 Red Hat Enterprise Linux 平台上安裝 Unified Manager。 
---
= 安裝 Unified Manager
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以在實體或虛擬 Red Hat Enterprise Linux 平台上安裝 Unified Manager。

.開始之前
* 您要安裝 Unified Manager 的系統必須符合系統和軟體需求。
+
看link:concept_virtual_infrastructure_or_hardware_system_requirements.html["硬體系統需求"]。

+
看link:reference_red_hat_software_and_installation_requirements.html["Linux 軟體和安裝需求"]。

* 您必須已下載 Unified Manager `.zip`檔案從NetApp支援網站複製到目標系統。
* 您應該已經驗證了下載的 `.zip`文件。
* 您必須擁有受支援的 Web 瀏覽器。
* 您的終端模擬軟體必須啟用回溯功能。


Red Hat Enterprise Linux 系統可能安裝了所有必要的支援軟體（Java、MySQL、附加實用程式）的必要版本，可能只安裝了部分必要的軟體，或者可能是新安裝的系統，沒有安裝任何必要的軟體。

.步驟
. 登入要安裝 Unified Manager 的伺服器。
. 輸入適當的命令來評估哪些軟體可能需要在目標系統上安裝或升級以支援安裝：
+
[cols="2*"]
|===
| 所需軟體和最低版本 | 驗證軟體和版本的命令 


 a| 
OpenJDK 版本 11.0.25
 a| 
`java -version`



 a| 
MySQL 8.4.4 社群版
 a| 
`rpm -qa | grep -i mysql`



 a| 
p7zip 16.02
 a| 
`rpm -qa | grep p7zip`

|===
. 如果安裝的MySQL版本低於MySQL 8.4.4社群版，請輸入下列指令進行解除安裝：
+
`rpm -e <mysql_package_name>`

+
如果收到依賴性錯誤，則必須新增 `--nodeps`卸載組件的選項。

. 導航至下載安裝的目錄 `.zip`檔案並展開 Unified Manager 套裝組合：
+
`unzip ActiveIQUnifiedManager-_<version>_.zip`

+
所需的 `.rpm`Unified Manager 的模組解壓縮到目標目錄。

. 驗證目錄中是否有以下模組：
+
`ls *.rpm`

+
`netapp-um<version>.x86_64.rpm`

. 執行預先安裝腳本以確保沒有系統設定設定或任何可能與 Unified Manager 安裝衝突的已安裝軟體：
+
`sudo ./pre_install_check.sh`

+
預先安裝腳本檢查系統是否有有效的 Red Hat Enterprise Linux 訂閱，以及是否可以存取所需的軟體儲存庫。如果腳本發現任何問題，則必須在安裝 Unified Manager 之前修復這些問題。

+
對於 Red Hat Enterprise Linux 8 系統，如果您有帶有 JDK 11 的內部儲存庫 - OpenJDK、p7zip 和 AppStream 儲存庫提供的其他軟體包，則必須停用您的 AppStream 儲存庫並安裝 MySQL Community Server。運行以下命令：

+
[listing]
----
# sudo yum --disablerepo=rhel-8-for-x86_64-appstream-rpms install  mysql-community-server
----
. *可選：*只有當您的系統未連接到互聯網並且必須手動下載安裝所需的軟體包時，您才必須執行步驟 7。如果您的系統可以存取網路並且所有必需的軟體包都可用，請前往步驟 8。對於未連接到網際網路或未使用 Red Hat Enterprise Linux 儲存庫的系統，請執行下列步驟來確定是否缺少任何所需的軟體包，然後下載這些軟體包：
+
.. 在安裝 Unified Manager 的系統上，檢視可用和不可用軟體套件的清單：+
`yum install netapp-um<version>.x86_64.rpm --assumeno`
+
「安裝：」部分中的項目是目前目錄中可用的軟體包，「安裝依賴項：」部分中的項目是系統中缺少的軟體包。

.. 在可以存取網路的系統上，下載缺少的軟體包：
+
`yum install <package_name> --downloadonly --downloaddir=.`

+
[NOTE]
====
由於外掛程式「yum-plugin-downloadonly」在 Red Hat Enterprise Linux 系統上並不總是啟用的，您可能需要啟用該功能來下載軟體包而不安裝它：
`yum install yum-plugin-downloadonly`

====
.. 將缺少的軟體包從網路連線的系統複製到您的安裝系統。


. 以 root 使用者身份，或使用 `sudo`，執行以下命令安裝軟體：
+
`yum install netapp-um<version>.x86_64.rpm`

+
此命令安裝 .rpm 軟體包、所有其他必要的支援軟體以及 Unified Manager 軟體。

+
如果安裝失敗並出現 GPG NOKEY 錯誤，請使用 `rpm --import`從 URL 匯入金鑰：

+
rpm --導入 https://repo.mysql.com/RPM-GPG-KEY-mysql-2023[]

+
[NOTE]
====
不要嘗試使用其他命令進行安裝（例如 `rpm -ivh`）。在 Red Hat Enterprise Linux 系統上成功安裝 Unified Manager 要求所有 Unified Manager 檔案和相關檔案都依照特定順序安裝到由 `yum install netapp-um<version>.x86_64.rpm`命令。

====
. 忽略安裝訊息後立即顯示的電子郵件通知。
+
該電子郵件通知 root 使用者初始 cron 作業失敗，但這對安裝沒有不利影響。

. 安裝訊息完成後，向後捲動訊息，直到看到系統顯示 Unified Manager Web UI 的 IP 位址或 URL、維護使用者名稱 (umadmin) 和預設密碼的訊息。
+
該訊息類似於以下內容：

+
[listing]
----
Active IQ Unified Manager installed successfully.
Use a web browser and one of the following URL(s) to configure and access the Unified Manager GUI.
https://default_ip_address/    (if using IPv4)
https://[default_ip_address]/  (if using IPv6)
https://fully_qualified_domain_name/

Log in to Unified Manager in a web browser by using following details:
  username: umadmin
  password: admin
----
. 記錄 IP 位址或 URL、指派的使用者名稱 (umadmin) 和目前密碼。
. 如果您在安裝 Unified Manager 之前建立了具有自訂主目錄的 umadmin 使用者帳戶，則必須指定 umadmin 使用者登入 shell：
+
`usermod -s /bin/maintenance-user-shell.sh umadmin`



存取 Web UI 以變更 umadmin 使用者的預設密碼，並執行 Unified Manager 的初始設置，如中所述link:../config/concept_configure_unified_manager.html["配置Active IQ Unified Manager"]。必須更改 umadmin 使用者的預設密碼。
