---
permalink: events/concept_guidelines_for_adding_alerts.html 
sidebar: sidebar 
keywords: guidelines, adding, alerts 
summary: 您可以根據資源（例如叢集、節點、聚合或磁碟區）以及特定嚴重性類型的事件新增警報。作為最佳實踐，您可以在新增物件所屬的叢集後為任何關鍵物件新增警報。 
---
= 新增警報的指南
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以根據資源（例如叢集、節點、聚合或磁碟區）以及特定嚴重性類型的事件新增警報。作為最佳實踐，您可以在新增物件所屬的叢集後為任何關鍵物件新增警報。

您可以根據以下指南和注意事項來建立警報，以有效管理您的系統：

* 警報描述
+
您應該提供警報的描述，以便幫助您有效地追蹤警報。

* 資源
+
您應該決定哪些實體或邏輯資源需要警報。您可以根據需要包含或排除資源。例如，如果您想要透過設定警報來密切監視您的聚合，則必須從資源清單中選擇所需的聚合。

+
如果您選擇一個資源類別，例如 *+<<All User or Group Quotas>> +*，那麼您將收到該類別中所有物件的警報。

+
[NOTE]
====
選擇叢集作為資源並不會自動選擇該叢集內的儲存物件。例如，如果您為所有叢集的所有關鍵事件建立警報，那麼您將只收到叢集關鍵事件的警報。您將不會收到有關節點、聚合等的關鍵事件的警報。

====
* 事件嚴重性
+
您應該決定指定嚴重性類型（嚴重、錯誤、警告）的事件是否應觸發警報，如果是，則應決定觸發哪種嚴重性類型。

* 精選活動
+
如果您根據產生的事件類型新增警報，則應該決定哪些事件需要警報。

+
如果您選擇事件嚴重性，但不選擇任何單一事件（如果您將「選定事件」列留空），那麼您將收到該類別中所有事件的警報。

* 行動
+
您必須提供接收通知的使用者的使用者名稱和電子郵件地址。您也可以指定 SNMP 陷阱作為通知模式。您可以將腳本與警報關聯，以便在產生警報時執行它們。

* 通知頻率
+
您可以設定警報以在指定時間內重複向收件人發送通知。您應該確定事件通知對於警報生效的時間。如果您希望重複發送事件通知直到事件已確認，則應確定重複發送通知的頻率。

* 執行腳本
+
您可以將腳本與警報關聯起來。當警報產生時，您的腳本就會執行。


