---
permalink: events/reference_dynamic_performance_event_chart_details.html 
sidebar: sidebar 
keywords: dynamic, performance, event, chart, details 
summary: 對於動態效能事件，事件詳細資訊頁面的系統診斷部分列出了爭用叢集元件中延遲或使用率最高的頂級工作負載。效能統計資料是基於偵測到效能事件的時間直到上次分析該事件的時間。圖表也顯示處於爭用的群集組件的歷史效能統計資料。 
---
= 動態效能事件圖表詳情
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
對於動態效能事件，事件詳細資訊頁面的系統診斷部分列出了爭用叢集元件中延遲或使用率最高的頂級工作負載。

效能統計資料是基於偵測到效能事件的時間直到上次分析該事件的時間。圖表也顯示處於爭用的群集組件的歷史效能統計資料。

例如，您可以識別組件利用率高的工作負載，以確定將哪些工作負載移至使用率較低的組件。移動工作負載將會減少目前元件的工作量，甚至可能使該元件不再發生爭用。此部分的頂部是偵測和最後分析事件的時間和日期範圍。對於活動事件（新事件或已確認事件），最後分析的時間會更新。

當您將遊標停留在圖表上時，延遲和活動圖表會顯示主要工作負載的名稱。點擊圖表右側的“工作負載類型”選單，您可以根據工作負載在事件中的角色對其進行排序，包括“sharks”、“bullies”或“victims”，並顯示有關其延遲及其在爭用叢集元件上的使用情況的詳細資訊。您可以將實際值與預期值進行比較，以查看何時工作負載超出其預期的延遲或使用範圍。有關信息，請參閱link:..//performance-checker/concept_types_of_workloads_monitored_by_unified_manager.html["Unified Manager 監控的工作負載類型"]。

[NOTE]
====
當您按延遲的峰值偏差排序時，系統定義的工作負載不會顯示在表中，因為延遲僅適用於使用者定義的工作負載。具有非常低延遲值的工作負載不會顯示在表格中。

====
有關動態效能閾值的更多信息，請參閱link:../performance-checker/concept_analyze_events_from_dynamic_performance_thresholds.html["從動態效能閾值分析事件"]。

有關 Unified Manager 如何對工作負載進行排名並確定排序順序的信息，請參閱link:../performance-checker/concept_how_um_determines_performance_impact_for_incident.html["Unified Manager 如何決定事件對效能的影響"]。

圖表中的數據顯示了上次分析事件之前 24 小時的效能統計。每個工作負載的實際值和預期值均基於工作負載參與事件的時間。例如，工作負載可能會在偵測到事件後才參與其中，因此其效能統計資料可能與事件偵測時的值不符。預設情況下，工作負載會依延遲的峰值（最高）偏差排序。

[NOTE]
====
由於 Unified Manager 最多保留 30 天的 5 分鐘歷史效能和事件數據，因此如果事件超過 30 天，則不會顯示任何效能數據。

====
* *工作負載排序列*
+
** *延遲圖表*
+
顯示上次分析時該事件對工作負載延遲的影響。

** *組件使用狀況列*
+
顯示有​​關爭用中的叢集元件的工作負載使用情況的詳細資訊。在圖表中，實際使用情況是一條藍線。紅色條突出顯示事件持續時間，從偵測時間到最後分析時間。有關詳細信息，請參閱 link:../performance-checker/reference_workload_performance_measurement_values.html["工作負載效能測量值"]。

+
[NOTE]
====
對於網路元件，由於網路效能統計資料來自群集外的活動，因此不會顯示此列。

====
** 組件使用
+
顯示網路處理、資料處理和聚合元件的使用率歷史記錄（以百分比表示），或顯示 QoS 策略群組元件的活動記錄（以百分比表示）。此圖表不顯示網路或互連組件。您可以指向統計資料來查看特定時間點的使用情況統計資料。

** *總寫入 MB/s 歷史記錄*
+
僅適用於MetroCluster資源元件，顯示MetroCluster配置中鏡像到配對叢集的所有磁碟區工作負載的總寫入吞吐量（以兆位元組/秒 (MBps) 為單位）。

** *事件歷史*
+
顯示紅色陰影線來指示爭用元件的歷史事件。對於過時的事件，圖表顯示在偵測到所選事件之前和解決之後發生的事件。




