---
permalink: events/reference_notifications_page.html 
sidebar: sidebar 
keywords: notifications page, email, smtp, server, snmp 
summary: 您可以設定 Unified Manager 伺服器，使其在產生事件或將事件指派給使用者時傳送通知。您也可以配置通知機制。例如，通知可以作為電子郵件或 SNMP 陷阱發送。 
---
= 通知頁面
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以設定 Unified Manager 伺服器，使其在產生事件或將事件指派給使用者時傳送通知。您也可以配置通知機制。例如，通知可以作為電子郵件或 SNMP 陷阱發送。

您必須具有應用程式管理員或儲存管理員角色。



== 電子郵件

此區域使您能夠配置以下警報通知的電子郵件設定：

* *寄件者地址*
+
指定發送警報通知的電子郵件地址。共用時，此值也可用作報告的寄件者地址。如果寄件者地址預先填寫了“ActiveIQUnifiedManager@localhost.com”，您應該將其變更為真實有效的電子郵件地址，以確保所有電子郵件通知都成功送達。





== SMTP 伺服器

此區域可讓您設定下列 SMTP 伺服器設定：

* *主機名稱或 IP 位址*
+
指定 SMTP 主機伺服器的主機名，用於將警報通知傳送給指定的收件者。

* *使用者名稱*
+
指定 SMTP 使用者名稱。僅當 SMTP 伺服器中啟用 SMTPAUTH 時才需要 SMTP 使用者名稱。

* *密碼*
+
指定 SMTP 密碼。僅當 SMTP 伺服器中啟用 SMTPAUTH 時才需要 SMTP 使用者名稱。

* *港口*
+
指定 SMTP 主機伺服器用於發送警報通知的連接埠。

+
預設值為 25。

* *使用 START/TLS*
+
勾選此方塊可使用 TLS/SSL 協定（也稱為 start_tls 和 StartTLS）在 SMTP 伺服器和管理伺服器之間提供安全通訊。

* *使用 SSL*
+
勾選此方塊可使用 SSL 協定在 SMTP 伺服器和管理伺服器之間提供安全通訊。





== SNMP

此區域可讓您設定以下 SNMP 陷阱設定：

* *版本*
+
根據您所需的安全性類型指定要使用的 SNMP 版本。選項包括版本 1、版本 3、帶有身份驗證的版本 3 和帶有身份驗證和加密的版本 3。預設值為版本 1。

* *陷阱目標主機*
+
指定接收管理伺服器傳送的 SNMP 陷阱的主機名稱或 IP 位址（IPv4 或 IPv6）。若要指定多個陷阱目標，請用逗號分隔每個主機。

+
[NOTE]
====
清單中所有主機的所有其他 SNMP 設定（例如「版本」和「出站連接埠」）必須相同。

====
* *出站陷阱端口*
+
指定 SNMP 伺服器透過其接收管理伺服器傳送的陷阱的連接埠。

+
預設值為 162。

* *社區*
+
存取主機的社群字串。

* *引擎ID*
+
指定 SNMP 代理程式的唯一標識符，由管理伺服器自動產生。引擎 ID 適用於 SNMP 版本 3、具有身份驗證的 SNMP 版本 3 以及具有身份驗證和加密的 SNMP 版本 3。

* *使用者名稱*
+
指定 SNMP 使用者名稱。使用者名稱適用於 SNMP 版本 3、具有身份驗證的 SNMP 版本 3 以及具有身份驗證和加密的 SNMP 版本 3。

* *身份驗證協定*
+
指定用於驗證使用者的協定。協定選項包括 MD5 和 SHA。 MD5 是預設值。身份驗證協定適用於具有身份驗證的 SNMP 版本 3 和具有身份驗證和加密的 SNMP 版本 3。

* *認證密碼*
+
指定驗證使用者時使用的密碼。帶有身份驗證的 SNMP 版本 3 和帶有身份驗證和加密的 SNMP 版本 3 均提供身份驗證密碼。

* *隱私協議*
+
指定用於加密 SNMP 訊息的隱私協定。協定選項包括 AES 128 和 DES。預設值為 AES 128。具有身份驗證和加密功能的 SNMP 版本 3 提供隱私協定。

* *隱私密碼*
+
指定使用隱私協定時的密碼。具有身份驗證和加密功能的 SNMP 版本 3 提供隱私密碼。



有關 SNMP 物件和陷阱的更多信息，您可以下載link:https://mysupport.netapp.com/site/tools/tool-eula/aiqum-mib["Active IQ Unified ManagerMIB"^]來自NetApp支援站點。
