---
permalink: events/reference_add_alert_dialog_box.html 
sidebar: sidebar 
keywords: add, alert, dialog, box, name, resources, events, actions, command buttons 
summary: 您可以建立警報，在產生特定事件時通知您，以便您可以快速解決問題並最大限度地減少對環境的影響。您可以為單一資源或一組資源以及特定嚴重性類型的事件建立警報。您也可以指定警報的通知方法和頻率。 
---
= 新增警報對話框
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以建立警報，在產生特定事件時通知您，以便您可以快速解決問題並最大限度地減少對環境的影響。您可以為單一資源或一組資源以及特定嚴重性類型的事件建立警報。您也可以指定警報的通知方法和頻率。

您必須具有應用程式管理員或儲存管理員角色。



== Name

此區域使您能夠指定警報的名稱和描述：

* *警報名稱*
+
使您能夠指定警報名稱。

* *警報描述*
+
使您能夠指定警報的描述。





== 資源

該區域可讓您選擇單一資源或根據要觸發警報的動態規則對資源進行分組。 _動態規則_是根據您指定的文字字串過濾的資源集。您可以從下拉清單中選擇資源類型來搜尋資源，也可以指定確切的資源名稱來顯示特定資源。

如果您從任何儲存物件詳細資料頁面建立警報，則該儲存物件將自動包含在警報中。

* *包括*
+
使您能夠包含想要觸發警報的資源。您可以指定一個文字字串來將與該字串相符的資源進行分組，並選擇該群組包含在警報中。例如，您可以將名稱包含“abc”字串的所有磁碟區分組。

* *排除*
+
使您能夠排除不想觸發警報的資源。例如，您可以排除名稱包含“xyz”字串的所有磁碟區。

+
僅當您選擇特定資源類型的所有資源時才會顯示「排除」標籤：例如，+<<All Volumes>>或者<<All Volumes whose name contains 'xyz'>>+。

+
如果資源同時符合您指定的包含規則和排除規則，則排除規則優先於包含規則，並且不會為事件產生警報。





== 活動

此區域使您能夠選擇要為其建立警報的事件。您可以根據特定嚴重性或一組事件建立事件警報。

若要選擇多個事件，您應該在選擇時按住 Ctrl 鍵。

* *事件嚴重性*
+
使您能夠根據嚴重性類型選擇事件，嚴重性類型可以是「嚴重」、「錯誤」或「警告」。

* *事件名稱包含*
+
使您能夠選擇名稱包含指定字元的事件。





== 行動

此區域使您能夠指定在觸發警報時要通知的使用者。您也可以指定通知方法和通知頻率。

* *提醒這些使用者*
+
使您能夠指定接收通知的使用者的電子郵件地址或使用者名稱。

+
如果您修改為使用者指定的電子郵件地址並重新開啟警報進行編輯，則「名稱」欄位將顯示為空白，因為修改後的電子郵件地址不再對應到先前選取的使用者。此外，如果您從「使用者」頁面修改了所選使用者的電子郵件地址，則所選使用者的修改後的電子郵件地址不會更新。

* *通知頻率*
+
使您能夠指定管理伺服器發送通知的頻率，直到事件被確認、解決或移至過時狀態。

+
您可以選擇以下通知方式：

+
** 僅通知一次
** 按指定頻率通知
** 在指定時間範圍內以指定頻率通知


* *發出 SNMP 陷阱*
+
選擇此方塊可讓您指定是否應將 SNMP 陷阱傳送至全域設定的 SNMP 主機。

* *執行腳本*
+
使您能夠將自訂腳本新增至警報中。當產生警報時執行此腳本。

+
[NOTE]
====
如果您在使用者介面中沒有看到此功能，那是因為您的管理員已停用該功能。如果需要，您可以從*儲存管理* > *功能設定*啟用此功能。

====




== 命令按鈕

* *節省*
+
建立警報並關閉對話框。

* *取消*
+
放棄更改並關閉對話框。


