---
permalink: events/reference_edit_alert_dialog_box.html 
sidebar: sidebar 
keywords: edit, alert, dialog box, name, resources, events, actions 
summary: 您可以編輯警報屬性，例如與警報關聯的資源、事件、腳本和通知選項。 
---
= 編輯警報對話框
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以編輯警報屬性，例如與警報關聯的資源、事件、腳本和通知選項。



== Name

此區域使您能夠編輯警報的名稱和描述。

* *警報名稱*
+
使您能夠編輯警報名稱。

* *警報描述*
+
使您能夠指定警報的描述。

* *警戒狀態*
+
使您能夠啟用或停用警報。





== 資源

該區域可讓您選擇單一資源或根據要觸發警報的動態規則對資源進行分組。您可以從下拉清單中選擇資源類型來搜尋資源，也可以指定確切的資源名稱來顯示特定資源。

* *包括*
+
使您能夠包含想要觸發警報的資源。您可以指定一個文字字串來將與該字串相符的資源進行分組，並選擇該群組包含在警報中。例如，您可以將名稱包含「`vol0`」字串的所有磁碟區進行分組。

* *排除*
+
使您能夠排除不想觸發警報的資源。例如，您可以排除名稱包含「`xyz`」字串的所有磁碟區。

+
[NOTE]
====
僅當您選擇特定資源類型的所有資源時才會顯示「排除」標籤 - 例如，+<<All Volumes>> + 或 +<<All Volumes whose name contains 'xyz'>> +。

====




== 活動

此區域使您能夠選擇想要觸發警報的事件。您可以根據特定嚴重性或一組事件觸發事件警報。

* *事件嚴重性*
+
使您能夠根據嚴重性類型選擇事件，嚴重性類型可以是「嚴重」、「錯誤」或「警告」。

* *事件名稱包含*
+
使您能夠選擇名稱包含指定字元的事件。





== 行動

此區域使您能夠指定通知方法和通知頻率。

* *提醒這些使用者*
+
使您能夠編輯電子郵件地址或使用者名，或指定新的電子郵件地址或使用者名稱來接收通知。

* *通知頻率*
+
使您能夠編輯管理伺服器發送通知的頻率，直到事件被確認、解決或移至過時狀態。

+
您可以選擇以下通知方式：

+
** 僅通知一次
** 按指定頻率通知
** 在指定時間範圍內以指定頻率通知


* *發出 SNMP 陷阱*
+
使您能夠指定是否應將 SNMP 陷阱傳送至全域設定的 SNMP 主機。

* *執行腳本*
+
使您能夠將腳本與警報關聯。當產生警報時執行此腳本。





== 命令按鈕

* *節省*
+
儲存變更並關閉對話框。

* *取消*
+
放棄更改並關閉對話框。


