---
permalink: events/reference_management_station_events.html 
sidebar: sidebar 
keywords: management, station, events, impact area, configuration, performance 
summary: 管理站事件為您提供有關安裝 Unified Manager 的伺服器狀態的信息，以便您監控潛在問題。事件按影響區域分組，包括事件和陷阱名稱、影響等級、來源類型和嚴重性。 
---
= 管理站事件
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
管理站事件為您提供有關安裝 Unified Manager 的伺服器狀態的信息，以便您監控潛在問題。事件按影響區域分組，包括事件和陷阱名稱、影響等級、來源類型和嚴重性。



== 影響區域：配置

|===
| 事件名稱（陷阱名稱） | 影響等級 | 來源類型 | 嚴重程度 


 a| 
管理伺服器磁碟空間幾乎已滿（ocumEvtUnifiedManagerDiskSpaceNearlyFull）
 a| 
風險
 a| 
管理站
 a| 
警告



 a| 
管理伺服器磁碟空間已滿（ocumEvtUnifiedManagerDiskSpaceFull）
 a| 
事件
 a| 
管理站
 a| 
批判的



 a| 
管理伺服器記憶體不足（ocumEvtUnifiedManagerMemoryLow）
 a| 
風險
 a| 
管理站
 a| 
警告



 a| 
管理伺服器記憶體即將耗盡（ocumEvtUnifiedManagerMemoryAlmostOut）
 a| 
事件
 a| 
管理站
 a| 
批判的



 a| 
MySQL 日誌檔案大小增加；需要重新啟動（ocumEvtMysqlLogFileSizeWarning）
 a| 
事件
 a| 
管理站
 a| 
警告



 a| 
總審計日誌大小分配即將滿
 a| 
風險
 a| 
管理站
 a| 
警告



 a| 
Syslog 伺服器憑證即將過期
 a| 
風險
 a| 
管理站
 a| 
警告



 a| 
Syslog 伺服器憑證已過期
 a| 
風險
 a| 
管理站
 a| 
錯誤



 a| 
審計日誌檔案被篡改
 a| 
風險
 a| 
管理站
 a| 
警告



 a| 
審計日誌檔已刪除
 a| 
風險
 a| 
管理站
 a| 
警告



 a| 
Syslog 伺服器連線錯誤
 a| 
風險
 a| 
管理站
 a| 
錯誤



 a| 
Syslog 伺服器設定已更改
 a| 
事件
 a| 
管理站
 a| 
警告

|===


== 影響領域：性能

|===
| 事件名稱（陷阱名稱） | 影響等級 | 來源類型 | 嚴重程度 


 a| 
效能資料分析受到影響（ocumEvtUnifiedManagerDataMissingAnalyze）
 a| 
風險
 a| 
管理站
 a| 
警告



 a| 
效能資料收集受到影響（ocumEvtUnifiedManagerDataMissingCollection）
 a| 
事件
 a| 
管理站
 a| 
批判的

|===
[NOTE]
====
最後兩個效能事件僅適用於 Unified Manager 7.2。如果其中任何一個事件處於「新」狀態，然後您升級到較新版本的 Unified Manager 軟體，則不會自動清除這些事件。您需要手動將事件移至「已解決」狀態。

====