---
permalink: events/reference_supported_unified_manager_cli_commands.html 
sidebar: sidebar 
keywords: supported, unified manager, cli, commands, cmd, um cli, um run, 
summary: 身為儲存管理員，您可以使用 CLI 指令對儲存物件執行查詢；例如，對叢集、聚合、磁碟區、qtree 和 LUN 執行查詢。 
---
= 支援的 Unified Manager CLI 命令
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
身為儲存管理員，您可以使用 CLI 指令對儲存物件執行查詢；例如，對叢集、聚合、磁碟區、qtree 和 LUN 執行查詢。您可以使用 CLI 指令查詢 Unified Manager 內部資料庫和ONTAP資料庫。您也可以在操作開始或結束時執行的腳本中使用 CLI 命令，或在觸發警報時執行的腳本。

所有命令必須以命令開頭 `um cli login`以及用於身份驗證的有效使用者名稱和密碼。


NOTE: 若要執行 _um run_ 命令，請確保您的帳戶具有 _console_ 應用程式存取權限。

|===
| CLI 命令 | 描述 | 輸出 


 a| 
`um cli login -u <username> [-p <password>]`
 a| 
登入 CLI。出於安全考慮，您應該只在“-u”選項後輸入使用者名稱。以這種方式使用時，系統將提示您輸入密碼，並且密碼不會被捕獲在歷史記錄或進程表中。會話登入後三小時過期，之後使用者必須再次登入。
 a| 
顯示相應的訊息。



 a| 
`um cli logout`
 a| 
退出 CLI。
 a| 
顯示相應的訊息。



 a| 
`um help`
 a| 
顯示所有第一級子命令。
 a| 
顯示所有第一級子命令。



 a| 
`um run cmd [ -t <timeout> ] <cluster> <command>`
 a| 
在一個或多個主機上運行命令的最簡單方法。主要用於警報腳本以取得或執行對ONTAP 的操作。可選的超時參數設定在客戶端完成命令的最大時間限制（以秒為單位）。預設值為 0（永遠等待）。
 a| 
從ONTAP收到。



 a| 
`um run query <sql command>`
 a| 
執行 SQL 查詢。只允許從資料庫讀取的查詢。不支援任何更新、插入或刪除操作。
 a| 
結果以表格顯示。如果傳回空集，或有任何語法錯誤或錯誤要求，則會顯示對應的錯誤訊息。



 a| 
`um datasource add -u <username> -P <password> [ -t <protocol> ] [ -p <port> ] <hostname-or-ip>`
 a| 
將資料來源新增至託管儲存系統清單。資料來源描述如何建立與儲存系統的連線。新增資料來源時必須指定選項 -u（使用者名稱）和 -P（密碼）。選項 -t（協定）指定用於與叢集通訊的協定（http 或 https）。如果未指定協議，則將嘗試兩種協議。選項 -p（連接埠）指定用於與叢集通訊的連接埠。如果未指定端口，則將嘗試相應協定的預設值。此命令只能由儲存管理員執行。
 a| 
提示使用者接受證書並列印相應的訊息。



 a| 
`um datasource list [ <datasource-id>]`
 a| 
顯示託管儲存系統的資料來源。
 a| 
以表格形式顯示以下值： `ID Address Port, Protocol Acquisition Status, Analysis Status, Communication status, Acquisition Message, and Analysis Message` 。



 a| 
`um datasource modify [ -h <hostname-or-ip> ] [ -u <username> ] [ -P <password> ] [ -t <protocol> ] [ -p <port> ] <datasource-id>`
 a| 
修改一個或多個資料來源選項。只能由儲存管理員執行。
 a| 
顯示相應的訊息。



 a| 
`um datasource remove <datasource-id>`
 a| 
從 Unified Manager 中刪除資料來源（叢集）。
 a| 
顯示相應的訊息。



 a| 
`um option list [ <option> .. ]`
 a| 
列出可以使用 set 指令配置的所有選項。
 a| 
以表格形式顯示以下值： `Name, Value, Default Value, and Requires Restart.`



 a| 
`um option set <option-name>=<option-value> [ <option-name>=<option-value> ... ]`
 a| 
設定一個或多個選項。此命令只能由儲存管理員執行。
 a| 
顯示相應的訊息。



 a| 
`um version`
 a| 
顯示 Unified Manager 軟體版本。
 a| 
`Version ("9.6")`



 a| 
`um lun list [-q] [ -ObjectType <object-id>]`
 a| 
列出按指定物件篩選後的 LUN。  -q 適用於所有指令，不顯示標題。  ObjectType 可以是 lun、qtree、cluster、volume、quota 或 svm。

例如：

*`um lun list -cluster 1`*

在這個範例中，「-cluster」是 objectType，「1」是 objectId。此指令列出了叢集內 ID 為 1 的所有 LUN。
 a| 
以表格形式顯示以下值： `ID and LUN path.`



 a| 
`um svm list [-q] [ -ObjectType <object-id>]`
 a| 
依指定物件過濾後列出儲存虛擬機器。  ObjectType 可以是 lun、qtree、cluster、volume、quota 或 svm。

例如：

*`um svm list -cluster 1`*

在這個範例中，「-cluster」是 objectType，「1」是 objectId。此指令列出了叢集內 ID 為 1 的所有儲存虛擬機器。
 a| 
以表格形式顯示以下值： `Name and Cluster ID.`



 a| 
`um qtree list [-q] [ -ObjectType <object-id>]`
 a| 
列出按指定物件過濾後的 qtree。  -q 適用於所有指令，不顯示標題。  ObjectType 可以是 lun、qtree、cluster、volume、quota 或 svm。

例如：

*`um qtree list -cluster 1`*

在這個範例中，「-cluster」是 objectType，「1」是 objectId。該指令列出了叢集內 ID 為 1 的所有 qtree。
 a| 
以表格形式顯示以下值： `Qtree ID and Qtree Name.`



 a| 
`um disk list [-q] [-ObjectType <object-id>]`
 a| 
列出按指定物件過濾後的磁碟。  ObjectType 可以是磁碟、聚合、節點或叢集。

例如：

*`um disk list -cluster 1`*

在這個範例中，「-cluster」是 objectType，「1」是 objectId。該指令列出了叢集內 ID 為 1 的所有磁碟。
 a| 
以表格形式顯示以下值 `ObjectType and object-id`。



 a| 
`um cluster list [-q] [-ObjectType <object-id>]`
 a| 
列出根據指定物件進行過濾後的集群。  ObjectType 可以是磁碟、aggr、節點、叢集、lun、qtree、磁碟區、配額或 svm。

例如：

*`um cluster list -aggr 1`*

在此範例中，「-aggr」是 objectType，「1」是 objectId。此指令列出了 ID 為 1 的聚合所屬的群集。
 a| 
以表格形式顯示以下值： `Name, Full Name, Serial Number, Datasource Id, Last Refresh Time, and Resource Key` 。



 a| 
`um cluster node list [-q] [-ObjectType <object-id>]`
 a| 
根據指定物件進行過濾後列出叢集節點。  ObjectType 可以是磁碟、聚合、節點或叢集。

例如：

*`um cluster node list -cluster 1`*

在這個範例中，「-cluster」是 objectType，「1」是 objectId。該指令列出了叢集內 ID 為 1 的所有節點。
 a| 
以表格形式顯示以下值 `Name and Cluster ID`。



 a| 
`um volume list [-q] [-ObjectType <object-id>]`
 a| 
列出按指定物件篩選後的磁碟區。  ObjectType 可以是 lun、qtree、cluster、volume、quota、svm 或 aggregate。

例如：

*`um volume list -cluster 1`*

在這個範例中，「-cluster」是 objectType，「1」是 objectId。此指令列出了集群內 ID 為 1 的所有磁碟區。
 a| 
以表格形式顯示以下值 `Volume ID and Volume Name`。



 a| 
`um quota user list [-q] [-ObjectType <object-id>]`
 a| 
列出按指定物件篩選後的配額使用者。  ObjectType 可以是 qtree、cluster、volume、quota 或 svm。

例如：

*`um quota user list -cluster 1`*

在這個範例中，「-cluster」是 objectType，「1」是 objectId。此指令列出了叢集內 ID 為 1 的所有配額使用者。
 a| 
以表格形式顯示以下值 `ID, Name, SID and Email`。



 a| 
`um aggr list [-q] [-ObjectType <object-id>]`
 a| 
列出按指定物件過濾後的聚合。  ObjectType 可以是磁碟、聚合、節點、叢集或磁碟區。

例如：

*`um aggr list -cluster 1`*

在這個範例中，「-cluster」是 objectType，「1」是 objectId。該指令列出了叢集中 ID 為 1 的所有聚合。
 a| 
以表格形式顯示以下值 `Aggr ID, and Aggr Name`。



 a| 
`um event ack <event-ids>`
 a| 
確認一個或多個事件。
 a| 
顯示相應的訊息。



 a| 
`um event resolve <event-ids>`
 a| 
解決一個或多個事件。
 a| 
顯示相應的訊息。



 a| 
`um event assign -u <username> <event-id>`
 a| 
將事件分配給使用者。
 a| 
顯示相應的訊息。



 a| 
`um event list [ -s <source> ] [ -S <event-state-filter-list>.. ] [ <event-id> .. ]`
 a| 
列出系統或使用者產生的事件。根據來源、狀態和 ID 過濾事件。
 a| 
以表格形式顯示以下值 `Source, Source type, Name, Severity, State, User and Timestamp`。



 a| 
`um backup restore -f <backup_file_path_and_name>`
 a| 
使用 .7z 檔案還原 MySQL 資料庫備份。
 a| 
顯示相應的訊息。

|===