---
permalink: events/reference_node_events.html 
sidebar: sidebar 
keywords: node, events, impact area, availability, capacity, configuration, performance, security 
summary: 節點事件為您提供有關節點狀態的信息，以便您可以監控潛在問題。事件按影響區域分組，包括事件和陷阱名稱、影響等級、來源類型和嚴重性。 
---
= 節點事件
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
節點事件為您提供有關節點狀態的信息，以便您可以監控潛在問題。事件按影響區域分組，包括事件和陷阱名稱、影響等級、來源類型和嚴重性。

星號 (*) 標識已轉換為 Unified Manager 事件的 EMS 事件。



== 影響領域：可用性

|===
| 事件名稱（陷阱名稱） | 影響等級 | 來源類型 | 嚴重程度 


 a| 
節點根捲空間幾乎已滿（ocumEvtClusterNodeRootVolumeSpaceNearlyFull）
 a| 
風險
 a| 
節點
 a| 
警告



 a| 
雲端 AWS MetaDataConnFail *(ocumCloudAwsMetadataConnFail)
 a| 
風險
 a| 
節點
 a| 
錯誤



 a| 
雲 AWS IAMCredsExpired *(ocumCloudAwsIamCredsExpired)
 a| 
風險
 a| 
節點
 a| 
錯誤



 a| 
雲 AWS IAMCredsInvalid *(ocumCloudAwsIamCredsInvalid)
 a| 
風險
 a| 
節點
 a| 
錯誤



 a| 
雲端 AWS IAMCredsNotFound *(ocumCloudAwsIamCredsNotFound)
 a| 
風險
 a| 
節點
 a| 
錯誤



 a| 
雲 AWS IAMCredsNotInitialized *(ocumCloudAwsIamCredsNotInitialized)
 a| 
事件
 a| 
節點
 a| 
資訊



 a| 
雲端 AWS IAMRoleInvalid *(ocumCloudAwsIamRoleInvalid)
 a| 
風險
 a| 
節點
 a| 
錯誤



 a| 
雲端 AWS IAMRoleNotFound *(ocumCloudAwsIamRoleNotFound)
 a| 
風險
 a| 
節點
 a| 
錯誤



 a| 
雲層主機無法解析 *(ocumObjstoreHostUnresolvable)
 a| 
風險
 a| 
節點
 a| 
錯誤



 a| 
雲層叢集間網路介面關閉*(ocumObjstoreInterClusterLifDown)
 a| 
風險
 a| 
節點
 a| 
錯誤



 a| 
其中一個 NFSv4 池已耗盡 *(nbladeNfsv4PoolEXhaust)
 a| 
事件
 a| 
節點
 a| 
批判的



 a| 
請求不符雲層簽名*（oscSignatureMismatch）
 a| 
風險
 a| 
節點
 a| 
錯誤

|===


== 影響區域：容量

|===
| 事件名稱（陷阱名稱） | 影響等級 | 來源類型 | 嚴重程度 


 a| 
QoS 監視器記憶體最大值 *(ocumQosMonitorMemoryMaxed)
 a| 
風險
 a| 
節點
 a| 
錯誤



 a| 
QoS 監視器記憶體減少 *(ocumQosMonitorMemoryAbated)
 a| 
事件
 a| 
節點
 a| 
資訊

|===


== 影響區域：配置

|===
| 事件名稱（陷阱名稱） | 影響等級 | 來源類型 | 嚴重程度 


 a| 
節點重命名（不適用）
 a| 
事件
 a| 
節點
 a| 
資訊

|===


== 影響領域：性能

|===
| 事件名稱（陷阱名稱） | 影響等級 | 來源類型 | 嚴重程度 


 a| 
節點 IOPS 臨界閾值被突破（ocumNodeIopsIncident）
 a| 
事件
 a| 
節點
 a| 
批判的



 a| 
節點 IOPS 警告閾值超出 (ocumNodeIopsWarning)
 a| 
風險
 a| 
節點
 a| 
警告



 a| 
節點 MB/s 臨界閾值突破（ocumNodeMbpsIncident）
 a| 
事件
 a| 
節點
 a| 
批判的



 a| 
節點 MB/s 警告閾值超出 (ocumNodeMbpsWarning)
 a| 
風險
 a| 
節點
 a| 
警告



 a| 
節點延遲 ms/op 臨界閾值突破（ocumNodeLatencyIncident）
 a| 
事件
 a| 
節點
 a| 
批判的



 a| 
節點延遲 ms/op 警告閾值超出 (ocumNodeLatencyWarning)
 a| 
風險
 a| 
節點
 a| 
警告



 a| 
節點效能容量使用臨界閾值已突破 (ocumNodePerfCapacityUsedIncident)
 a| 
事件
 a| 
節點
 a| 
批判的



 a| 
節點效能容量使用警告閾值超出 (ocumNodePerfCapacityUsedWarning)
 a| 
風險
 a| 
節點
 a| 
警告



 a| 
已使用節點效能容量 - 超出接管臨界閾值 (ocumNodePerfCapacityUsedTakeoverIncident)
 a| 
事件
 a| 
節點
 a| 
批判的



 a| 
已使用節點效能容量 - 超出接管警告閾值 (ocumNodePerfCapacityUsedTakeoverWarning)
 a| 
風險
 a| 
節點
 a| 
警告



 a| 
節點利用率臨界閾值被突破 (ocumNodeUtilizationIncident)
 a| 
事件
 a| 
節點
 a| 
批判的



 a| 
節點利用率警告閾值超出 (ocumNodeUtilizationWarning)
 a| 
風險
 a| 
節點
 a| 
警告



 a| 
節點 HA 對過度利用閾值被突破 (ocumNodeHaPairOverUtilizedInformation)
 a| 
事件
 a| 
節點
 a| 
資訊



 a| 
節點磁碟碎片閾值超出（ocumNodeDiskFragmentationWarning）
 a| 
風險
 a| 
節點
 a| 
警告



 a| 
效能容量使用閾值超出 (ocumNodeOverUtilizedWarning)
 a| 
風險
 a| 
節點
 a| 
警告



 a| 
節點動態閾值被突破（ocumNodeDynamicEventWarning）
 a| 
風險
 a| 
節點
 a| 
警告

|===


== 影響領域：安全

|===
| 事件名稱（陷阱名稱） | 影響等級 | 來源類型 | 嚴重程度 


 a| 
諮詢 ID：NTAP-<__advisory ID__>(ocumx)
 a| 
風險
 a| 
節點
 a| 
批判的

|===