---
permalink: events/reference_event_details_page.html 
sidebar: sidebar 
keywords: event, details, page 
summary: 在事件詳情頁面中，您可以查看所選事件的詳細信息，例如事件嚴重性、影響程度、影響區域和事件來源。您也可以查看有關解決問題的可能補救措施的其他資訊。 
---
= 活動詳情頁面
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
在事件詳情頁面中，您可以查看所選事件的詳細信息，例如事件嚴重性、影響程度、影響區域和事件來源。您也可以查看有關解決問題的可能補救措施的其他資訊。

* *活動名稱*
+
事件的名稱以及最後看到事件的時間。

+
對於非績效事件，當事件處於「新」或「已確認」狀態時，最後看到的資訊是未知的，因此是隱藏的。

* *活動描述*
+
事件的簡要描述。

+
在某些情況下，事件描述中會提供觸發事件的原因。

* *有爭議的組件*
+
對於動態效能事件，此部分顯示代表叢集的邏輯和實體元件的圖示。如果某個組件存在爭用，其圖示將被圈出並以紅色突出顯示。

+
有關此處顯示的組件的描述，請參閱_集群組件以及它們為何會發生爭用_。



事件資訊、系統診斷和建議的操作部分在其他主題中描述。



== 命令按鈕

命令按鈕使您能夠執行以下任務：

* *註釋圖示*
+
使您能夠新增或更新有關事件的註釋，並查看其他使用者留下的所有註釋。



*操作選單*

* *分配給我*
+
將事件分配給您。

* *分配給其他人*
+
開啟「指派所有者」對話框，您可以將事件指派或重新指派給其他使用者。

+
當您將事件指派給使用者時，使用者的姓名和指派事件的時間將會新增至所選事件的事件清單中。

+
您也可以透過將所有權欄位留空來取消分配事件。

* *承認*
+
確認選定的事件，以便您不會繼續收到重複的警報通知。

+
當您確認某個事件時，您的使用者名稱和確認該事件的時間將會加入所選事件的事件清單（確認人）中。當您確認某個事件時，您就承擔起管理該事件的責任。

* *標記為已解決*
+
使您能夠將事件狀態變更為“已解決”。

+
當您解決某個事件時，您的使用者名稱和解決該事件的時間將會新增到所選事件的事件清單（解決者）中。對事件採取糾正措施後，您必須將該事件標記為已解決。

* *新增警報*
+
顯示「新增警報」對話框，您可以在此為選定事件新增警報。


