---
permalink: data-protection/concept_storage_virtual_machine_and_resource_pool_requirements.html 
sidebar: sidebar 
keywords: svm, resource pool requirements, support, storage services 
summary: 如果您觀察到某些特定於儲存服務的 SVM 關聯和資源池需求，則可以更好地確保合作夥伴應用程式中的一致性：例如，當您關聯 SVM 並在 Unified Manager 中建立資源池以支援合作夥伴應用程式提供的儲存服務中的保護拓撲時。 
---
= 支援儲存服務的 SVM 和資源池需求
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
如果您觀察到某些特定於儲存服務的 SVM 關聯和資源池需求，則可以更好地確保合作夥伴應用程式中的一致性：例如，當您關聯 SVM 並在 Unified Manager 中建立資源池以支援合作夥伴應用程式提供的儲存服務中的保護拓撲時。

一些應用程式與 Unified Manager 伺服器合作，提供在來源磁碟區和二級或三級位置的保護磁碟區之間自動設定和執行SnapMirror或SnapVault備份保護的服務。為了支援這些保護儲存服務，您必須使用 Unified Manager 設定必要的 SVM 關聯和資源池。

若要支援儲存服務單跳或級聯保護（包括從SnapMirror來源或SnapVault主磁碟區複製到目標SnapMirror或位於二級或三級位置的SnapVault備份磁碟區），請遵守下列要求：

* 必須在包含SnapMirror來源或SnapVault主磁碟區的 SVM 與任何二級磁碟區或三級磁碟區所在的 SVM 之間設定 SVM 關聯。
+
** 例如，要支援來源磁碟區 Vol_A 位於 SVM_1 上、 SnapMirror二級目標磁碟區 Vol_B 位於 SVM_2 上、三級SnapVault備份磁碟區 Vol_C 位於 SVM_3 上的保護拓撲，您必須使用 Unified Manager Web UI 在 SVM_1和SVM_2 之間設定的保護拓撲，您必須使用 Unified Manager Web UI 在 SVM_1和SVM_2 之間設定關聯配置。
+
在此範例中，SVM_2 和 SVM_3 之間的任何SnapMirror關聯或SnapVault備份關聯都不是必需的，也不會使用。

** 若要支援來源磁碟區 Vol_A 和SnapMirror目標磁碟區 Vol_B 都位於 SVM_1 上的保護拓撲，您必須在 SVM_1 和 SVM_1 之間設定SnapMirror關聯。


* 資源池必須包含可供關聯 SVM 使用的叢集聚合資源。
+
您可以透過 Unified Manager Web UI 設定資源池，然後透過合作夥伴應用程式指派儲存服務二級目標和三級目標節點。


