---
permalink: data-protection/concept_types_of_snapmirror_protection.html 
sidebar: sidebar 
keywords: types, snapmirror, protection, consistency group, SnapMirror active sync 
summary: 根據資料儲存拓撲的部署，Unified Manager 可讓您設定多種類型的SnapMirror保護關係。  SnapMirror保護的所有變體都提供故障轉移災難復原保護，但在效能、版本靈活性和多備份副本保護方面提供不同的功能。 
---
= SnapMirror保護類型
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
根據資料儲存拓撲的部署，Unified Manager 可讓您設定多種類型的SnapMirror保護關係。  SnapMirror保護的所有變體都提供故障轉移災難復原保護，但在效能、版本靈活性和多備份副本保護方面提供不同的功能。



== 傳統SnapMirror非同步保護關係

傳統的SnapMirror非同步保護在來源磁碟區和目標磁碟區之間提供區塊複製鏡像保護。

在傳統的SnapMirror關係中，鏡像操作的執行速度比在替代SnapMirror關係中更快，因為鏡像操作是基於區塊複製。但是，傳統的SnapMirror保護要求目標磁碟區在與同一主要版本中的來源磁碟區相同或更高版本的ONTAP軟體下運作（例如，版本 8.x 到 8.x，或 9.x 到 9.x）。不支援從 9.1 來源複製到 9.0 目標，因為目標正在運行早期主要版本。



== SnapMirror非同步保護，具有版本靈活的複製

SnapMirror非同步保護與版本靈活的複製功能可在來源磁碟區和目標磁碟區之間提供邏輯複製鏡像保護，即使這些磁碟區在不同版本的ONTAP 8.3 或更高版本軟體下運作（例如，版本 8.3 到 8.3.1、8.3 到 9.1 或 9.2.2 到 9.2）。

在具有版本靈活複製的SnapMirror關係中，鏡像操作的執行速度不如傳統SnapMirror關係中那麼快。

由於執行速度較慢，具有版本靈活複製保護的SnapMirror不適合在以下任一情況下實施：

* 來源物件包含超過 1000 萬個需要保護的檔案。
* 受保護資料的恢復點目標是兩小時或更短。  （也就是說，目標必須始終包含鏡像的、可恢復的數據，而這些數據的保存時間不能比來源數據早兩個小時。）


在列出的任何一種情況下，都需要基於更快的區塊複製執行預設SnapMirror保護。



== SnapMirror非同步保護，具有版本靈活的複製和備份選項

SnapMirror非同步保護具有版本靈活的複製和備份選項，可在來源磁碟區和目標磁碟區之間提供鏡像保護，並能夠在目標位置儲存鏡像資料的多個副本。

儲存管理員可以指定從來源到目標鏡像哪些 Snapshot 副本，也可以指定在目標保留這些副本多長時間，即使它們在來源中被刪除。

在具有版本靈活複製和備份選項的SnapMirror關係中，鏡像操作的執行速度不如傳統SnapMirror關係中那麼快。



== SnapMirror統一複製（鏡像和保管庫）

SnapMirror統一複製可讓您在同一目標磁碟區上設定災難復原和歸檔。與SnapMirror一樣，統一資料保護在第一次呼叫時執行基線傳輸。預設統一資料保護策略「MirrorAndVault」下的基準傳輸會對來源磁碟區進行快照複製，然後將該副本及其引用的資料區塊傳輸到目標磁碟區。與SnapVault一樣，統一資料保護不包括基線中的舊 Snapshot 副本。



== SnapMirror同步保護，嚴格同步

SnapMirror同步保護採用「嚴格」同步，確保主磁碟區和輔助磁碟區始終是彼此的真實副本。如果在嘗試將資料寫入輔助磁碟區時發生複製失敗，則用戶端對主磁碟區的 I/O 將會中斷。



== SnapMirror同步保護與定期同步

SnapMirror同步保護採用「常規」同步，不要求主磁碟區和輔助磁碟區始終是彼此的真實副本；從而確保主磁碟區的可用性。如果在嘗試將資料寫入輔助磁碟區時發生複製失敗，則主磁碟區和輔助磁碟區將不同步，且用戶端 I/O 將繼續至主磁碟區。

[NOTE]
====
從「健康狀況：所有磁碟區」檢視或「磁碟區/健康狀況詳細資料」頁面監控同步保護關係時，「復原」按鈕和「關係操作」按鈕不可用。

====


== SnapMirror主動同步

SnapMirror主動同步功能在ONTAP 9.8 及更高版本中可用，您可以使用它來保護具有 LUN 的應用程序，使應用程式能夠透明地進行故障轉移，確保在發生災難時業務連續性。

它可讓您從 Unified Manager 發現和監控叢集和儲存虛擬機器上可用的一致性群組 (CG) 的同步SnapMirror關係。  AFF叢集或所有 SAN 陣列 (ASA ) 叢集均支援SnapMirror主動同步，其中主叢集和輔助叢集可以是AFF或ASA。  SnapMirror主動同步使用 iSCSI 或 FCP LUN 保護應用程式。

當您查看受SnapMirror主動同步關係保護的捲和 LUN 時，您可以獲得保護關係、卷清單中的一致性組的統一視圖，查看一致性組關係的保護拓撲，查看長達一年的一致性組關係的歷史資料。您也可以下載該報告。您也可以查看一致性群組關係的摘要、搜尋一致性群組關係的支持，並取得有關受一致性群組保護的磁碟區的資訊。

在「關係」頁面上，您還可以對一致性群組保護的來源和目標儲存物件及其關係進行排序、篩選和擴充保護。

要了解有關SnapMirror主動同步的更多信息，請參閱link:https://docs.netapp.com/us-en/ontap/smbc/index.html["Snapmirror 主動同步（以前稱為 SM-BC）的ONTAP 9 文檔"]。
