---
permalink: data-protection/reference_resynchronize_dialog_box.html 
sidebar: sidebar 
keywords: resynchronize, dialog box 
summary: 透過重新同步對話框，您可以重新同步先前已中斷且隨後目標變為讀/寫卷的SnapMirror或SnapVault關係上的資料。當來源磁碟區上所需的通用 Snapshot 副本被刪除導致SnapMirror或SnapVault更新失敗時，您可能還需要重新同步。 
---
= 重新同步對話框
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
透過重新同步對話框，您可以重新同步先前已中斷且隨後目標變為讀/寫卷的SnapMirror或SnapVault關係上的資料。當來源磁碟區上所需的通用 Snapshot 副本被刪除導致SnapMirror或SnapVault更新失敗時，您可能還需要重新同步。



== 重新同步選項選項卡

透過「重新同步選項」標籤，您可以設定正在重新同步的保護關係的傳輸優先順序和最大傳輸速率。

* *轉移優先權*
+
傳輸運行的優先權。您可以選擇正常或低。具有指定正常傳輸優先權的策略的關係先於具有指定低傳輸優先權的策略的關係運作。

* *最大傳輸速率*
+
指定透過網路在集群之間傳輸資料的最大速率。選取後，網路頻寬將限制為您指定的值。您可以輸入一個數值，然後選擇每秒千位元組 (KBps)、每秒兆位元組 (MBps)、每秒千兆位元組 (GBps) 或 TBps。如果您選擇不使用最大轉移率，則關係之間的基準轉移是無限制的。





== 來源 Snapshot 副本選項卡

「來源 Snapshot 副本」標籤顯示用於基準傳輸的來源 Snapshot 副本的下列資訊：

* *來源磁碟區*
+
顯示對應來源磁碟區的名稱。

* *目標音量*
+
顯示選定目標磁碟區的名稱。

* *來源類型*
+
顯示磁碟區類型：讀取/寫入或資料保護。

* *快照副本*
+
顯示用於資料傳輸的 Snapshot 副本。按一下 Snapshot 副本值將顯示「選擇來源 Snapshot 副本」對話框，您可以在其中根據您擁有的保護關係類型和正在執行的操作選擇要傳輸的特定 Snapshot 副本。





== 命令按鈕

* *提交*
+
開始重新同步程序並關閉「重新同步」對話方塊。

* *取消*
+
取消您的選擇並關閉“重新同步”對話框。


