---
permalink: data-protection/reference_create_schedule_dialog_box.html 
sidebar: sidebar 
keywords: create, schedule, dialog box 
summary: 使用「建立計畫」對話方塊可以為SnapMirror和SnapVault關係傳輸建立基本或進階保護計畫。您可以建立一個新的計劃來增加資料傳輸的頻率（因為資料更新頻繁），或者當資料不頻繁更改時，您可以建立一個不太頻繁的計劃。 
---
= 建立計劃對話框
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
使用「建立計畫」對話方塊可以為SnapMirror和SnapVault關係傳輸建立基本或進階保護計畫。您可以建立一個新的計劃來增加資料傳輸的頻率（因為資料更新頻繁），或者當資料不頻繁更改時，您可以建立一個不太頻繁的計劃。

無法為SnapMirror同步關係配置計劃。

* *目標集群*
+
您在「配置保護」對話方塊的SnapVault標籤或SnapMirror標籤中選擇的叢集的名稱。

* *日程表名稱*
+
您為計劃提供的名稱。計劃名稱可以由字元 A 到 Z、a 到 z、0 到 9 以及以下任何特殊字元組成：！ @#$​​%{插入符號}&*()_-。計劃名稱不得包含以下字元：< >。

* *基礎版或進階版*
+
您想要使用的計劃模式。

+
基本模式包含以下元素：

+
** 重複
+
預定的轉移發生的頻率。選擇包括每小時、每天和每週。

** 天
+
當選擇每週重複時，傳輸將在星期幾發生。

** 時間
+
當選擇每日或每週時，傳輸發生的時間是一天中的時間。



+
進階模式包括以下內容：

+
** 月
+
以逗號分隔的數字列表，代表一年中的月份。有效值為 0 到 11，其中零代表一月，依此類推。此元素是可選的。將此欄位留空表示每月都會發生轉帳。

** 天
+
以逗號分隔的數字列表，表示月份中的日期。有效值為 1 至 31。此元素是可選的。將該欄位留空意味著每月每天都會發生轉帳。

** 工作日
+
以逗號分隔的數字列表，表示一週的每一天。有效值為 0 到 6，其中 0 代表星期日，依此類推。此元素是可選的。將該欄位留空意味著每週每天都會發生轉帳。如果指定了星期幾，但未指定月份中的某天，則轉移僅在指定的星期幾發生，而不是每天發生。

** 小時
+
以逗號分隔的數字列表，表示一天的小時數。有效值為 0 到 23，其中 0 代表午夜。此元素是可選的。

** 分分鐘
+
以逗號分隔的數字列表，表示一小時內的分鐘數。有效值為 0 到 59。此元素是必需的。




