---
permalink: data-protection/reference_configure_protection_dialog_box.html 
sidebar: sidebar 
keywords: configure, protection, dialog box 
summary: 您可以使用「設定保護」對話方塊為叢集上的所有讀取、寫入和資料保護磁碟區建立SnapMirror和SnapVault關係，以確保複製來源磁碟區或主磁碟區上的資料。 
---
= 配置保護對話框
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以使用「設定保護」對話方塊為叢集上的所有讀取、寫入和資料保護磁碟區建立SnapMirror和SnapVault關係，以確保複製來源磁碟區或主磁碟區上的資料。



== 來源選項卡

* *拓樸視圖*
+
顯示您正在建立的關係的視覺表示。拓撲中的來源預設為突出顯示。

* *來源資訊*
+
顯示有​​關所選來源磁碟區的詳細信息，包括以下資訊：

+
** 來源叢集名稱
** 來源 SVM 名稱
** 累計卷總大小
+
顯示所有選定來源磁碟區的總大小。

** 累計已用卷大小
+
顯示所有選定來源磁碟區的累計已使用磁碟區大小。

** 來源磁碟區
+
在表中顯示以下資訊：

+
*** 源體積
+
顯示選定來源磁碟區的名稱。

*** 類型
+
顯示卷類型。

*** SnapLock類型
+
顯示磁碟區的SnapLock類型。選項包括 Compliance、Enterprise 和 Non- SnapLock。

*** 快照複製
+
顯示用於基線傳輸的 Snapshot 副本。如果來源磁碟區是讀取/寫入的，則 Snapshot 副本列中的 Default 值表示預設建立新的 Snapshot 副本，並用於基線傳輸。如果來源磁碟區是資料保護磁碟區，則 Snapshot 副本列中的值 Default 表示不會建立新的 Snapshot 副本，並且所有現有的 Snapshot 副本都會傳送到目標。點擊 Snapshot 副本值將顯示 Snapshot 副本列表，您可以從中選擇一個現有 Snapshot 副本用於基線傳輸。如果來源類型是資料保護，則無法選擇不同的預設 Snapshot 副本。









== SnapMirror選項卡

使您能夠在建立SnapMirror關係時​​指定保護關係的目標叢集、儲存虛擬機器 (SVM) 和聚合，以及目標的命名約定。您也可以指定SnapMirror策略和計畫。

* *拓樸視圖*
+
顯示您正在建立的關係的視覺表示。拓撲中的SnapMirror目標資源預設為反白顯示。

* *目的地資訊*
+
使您能夠選擇保護關係的目標資源：

+
** 高級連結
+
建立SnapMirror關係時​​啟動「進階目標設定」對話框。

** 簇
+
列出可作為保護目標主機的叢集。此欄位是必需的。

** 儲存虛擬機器 (SVM)
+
列出選定叢集上可用的 SVM。必須先選擇一個集群，然後才能填入 SVM 清單。此欄位是必需的。

** 總計的
+
列出選定 SVM 上可用的聚合。必須先選擇一個集群，然後才能填入聚合清單。此欄位是必需的。匯總清單顯示以下資訊：

+
*** 秩
+
當多個聚合滿足目標的所有要求時，排名表示聚合列出的優先級，根據以下條件：

+
.... 最好使用與來源磁碟區節點位於不同節點上的聚合來實現故障域分離。
.... 優先選擇具有較少磁碟區的節點上的聚合，以便在叢集中的節點之間實現負載平衡。
.... 為了實現容量平衡，優先選擇比其他聚合具有更多可用空間的聚合。排名為 1 表示根據這三個標準，該集合是最受歡迎的。


*** 聚合名稱
+
聚合的名稱

*** 可用容量
*** 聚合上可用於資料的空間量
*** 資源池
+
聚合所屬的資源池的名稱



** 命名約定
+
指定套用於目標磁碟區的預設命名約定。您可以接受提供的命名約定，也可以建立自訂的命名約定。命名約定可以具有以下屬性：%C、%M、%V 和 %N，其中 %C 是叢集名稱，%M 是 SVM 名稱，%V 是來源卷，%N 是拓撲目標節點名稱。

+
如果您的輸入無效，則命名約定欄位將以紅色突出顯示。按一下「預覽名稱」連結將顯示您輸入的命名約定的預覽，並且當您在文字欄位中鍵入命名約定時，預覽文字會動態更新。建立關係時，會在目標名稱後面附加 001 至 999 之間的後綴，以取代預覽文字中顯示的 nnn，其中首先分配 001，其次分配 002，依此類推。



* *關係設定*
+
使您能夠指定保護關係使用的最大傳輸速率、 SnapMirror策略和計劃：

+
** 最大傳輸速率
+
指定透過網路在集群之間傳輸資料的最大速率。如果您選擇不使用最大轉移率，則關係之間的基準轉移是無限制的。

** SnapMirror策略
+
指定該關係的ONTAP SnapMirror策略。預設值為 DPDefault。

** 創建策略
+
啟動「建立SnapMirror策略」對話框，在此可以建立和使用新的SnapMirror策略。

** SnapMirror計劃
+
指定該關係的ONTAP SnapMirror策略。可用的時間表包括無、5 分鐘、8 小時、每天、每小時和每週。預設值為 None，表示沒有與該關係關聯的計劃。沒有時間表的關係沒有滯後狀態值，除非它們屬於儲存服務。

** 創建時間表
+
啟動「建立計畫」對話框，在此可以建立新的SnapMirror計畫。







== SnapVault選項卡

使您能夠在建立SnapVault關係時指定保護關係的二級叢集、SVM 和聚合，以及二級磁碟區的命名約定。您也可以指定SnapVault策略和計劃。

* *拓樸視圖*
+
顯示您正在建立的關係的視覺表示。拓樸中的SnapVault二級資源預設為突出顯示。

* *次要訊息*
+
使您能夠選擇保護關係的輔助資源：

+
** 高級連結
+
啟動“進階輔助設定”對話框。

** 簇
+
列出可用作輔助保護主機的叢集。此欄位是必需的。

** 儲存虛擬機器 (SVM)
+
列出選定叢集上可用的 SVM。必須先選擇一個集群，然後才能填入 SVM 清單。此欄位是必需的。

** 總計的
+
列出選定 SVM 上可用的聚合。必須先選擇一個集群，然後才能填入聚合清單。此欄位是必需的。匯總清單顯示以下資訊：

+
*** 秩
+
當多個聚合滿足目標的所有要求時，排名表示聚合列出的優先級，根據以下條件：

+
.... 最好使用與主磁碟區節點位於不同節點上的聚合來實現故障域分離。
.... 優先選擇具有較少磁碟區的節點上的聚合，以便在叢集中的節點之間實現負載平衡。
.... 為了實現容量平衡，優先選擇比其他聚合具有更多可用空間的聚合。排名為 1 表示根據這三個標準，該集合是最受歡迎的。


*** 聚合名稱
+
聚合的名稱

*** 可用容量
*** 聚合上可用於資料的空間量
*** 資源池
+
聚合所屬的資源池的名稱



** 命名約定
+
指定套用於輔助磁碟區的預設命名約定。您可以接受提供的命名約定，也可以建立自訂的命名約定。命名約定可以具有以下屬性：%C、%M、%V 和 %N，其中 %C 是叢集名稱，%M 是 SVM 名稱，%V 是來源卷，%N 是拓撲輔助節點名稱。

+
如果您的輸入無效，則命名約定欄位將以紅色突出顯示。按一下「預覽名稱」連結將顯示您輸入的命名約定的預覽，並且當您在文字欄位中鍵入命名約定時，預覽文字會動態更新。如果輸入無效值，無效資訊將在預覽區域中顯示為紅色問號。建立關係時，會在輔助名稱後面附加 001 至 999 之間的後綴，以取代預覽文字中顯示的 nnn，其中首先分配 001，其次分配 002，依此類推。



* *關係設定*
+
使您能夠指定保護關係使用的最大傳輸速率、 SnapVault策略和SnapVault計劃：

+
** 最大傳輸速率
+
指定透過網路在集群之間傳輸資料的最大速率。如果您選擇不使用最大轉移率，則關係之間的基準轉移是無限制的。

** SnapVault策略
+
指定該關係的ONTAP SnapVault策略。預設值為 XDPDefault。

** 創建策略
+
啟動「建立SnapVault策略」對話框，您可以建立和使用新的SnapVault策略。

** SnapVault計劃
+
指定關係的ONTAP SnapVault計劃。可用的時間表包括無、5 分鐘、8 小時、每天、每小時和每週。預設值為 None，表示沒有與該關係關聯的計劃。沒有時間表的關係沒有滯後狀態值，除非它們屬於儲存服務。

** 創建時間表
+
啟動「建立計畫」對話框，在此可以建立SnapVault計畫。







== 命令按鈕

命令按鈕使您能夠執行以下任務：

* *取消*
+
放棄您的選擇，並關閉“配置保護”對話框。

* *申請*
+
應用您的選擇並開始保護過程。


