---
permalink: data-protection/reference_create_snapvault_policy_dialog_box.html 
sidebar: sidebar 
keywords: create, snapvault, policy, dialog box 
summary: 透過「建立SnapVault策略」對話框，您可以建立策略來設定SnapVault傳輸的優先順序。您可以使用策略來最大程度地提高從主磁碟區到輔助磁碟區的傳輸效率。 
---
= 建立SnapVault策略對話框
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
透過「建立SnapVault策略」對話框，您可以建立策略來設定SnapVault傳輸的優先順序。您可以使用策略來最大程度地提高從主磁碟區到輔助磁碟區的傳輸效率。

* *目標集群*
+
您在「配置保護」對話方塊的SnapVault標籤中選擇的叢集的名稱。

* *目標 SVM*
+
您在「配置保護」對話方塊的SnapVault標籤中所選的 SVM 的名稱。

* *政策名稱*
+
您為新策略提供的名稱。策略名稱可以由字元 A 到 Z、a 到 z、0 到 9、句點 (.)、連字號 (-) 和底線 (_) 組成。

* *轉移優先權*
+
傳輸運行的優先權。您可以選擇正常或低。具有指定正常傳輸優先權的策略的傳輸關係先於具有指定低傳輸優先權的策略的傳輸關係運作。預設為正常。

* *評論*
+
可選字段，您可以在其中添加有關SnapVault策略的最多 255 個字元的註釋。

* *忽略訪問時間*
+
指定是否忽略僅存取時間變更的檔案的增量傳輸。

* *複製標籤*
+
在表中列出與ONTAP選擇的在政策中具有特定複製標籤的 Snapshot 副本關聯的規則。還可以提供以下資訊和操作：

+
** 命令按鈕
+
命令按鈕使您能夠執行以下操作：

+
*** 添加
+
使您能夠建立 Snapshot 副本標籤和保留計數。

*** 編輯保留計數
+
使您能夠變更現有 Snapshot 副本標籤的保留計數。保留計數必須是 1 到 251 之間的數字。所有規則的保留計數總和不能超過 251。

*** 刪除
+
使您能夠刪除現有的 Snapshot 副本標籤。



** 快照複製標籤
+
顯示 Snapshot 副本標籤。如果您選擇一個或多個具有相同本機 Snapshot 副本原則的捲，則會顯示該原則中每個標籤的項目。如果您選擇具有兩個或更多本機 Snapshot 副本原則的多個卷，則該表將顯示所有策略的所有標籤

** 行程
+
顯示與每個 Snapshot 副本標籤相關的計劃。如果某個標籤關聯有多個計劃，則該標籤的計劃將顯示在以逗號分隔的清單中。如果選擇具有相同標籤但具有不同計劃的多個卷，則計劃將顯示「各種」以指示有多個計劃與所選卷相關聯。

** 目的地保留計數
+
顯示保留在SnapVault輔助節點上的指定標籤的 Snapshot 副本的數量。具有多個計劃的標籤的保留計數顯示每個標籤和計劃對的保留計數總和。如果您選擇具有兩個或更多本機 Snapshot 副本原則的多個卷，則保留計數為空。




