---
permalink: data-protection/reference_relationship_last_1_month_transfer_status_view.html 
sidebar: sidebar 
keywords: relationship, 1 month, transfer status, view 
summary: 關係：過去 1 個月的傳輸狀態視圖可讓您分析非同步關係中的磁碟區和儲存虛擬機器在一段時間內的傳輸趨勢。此頁面還顯示傳輸是否成功或失敗。 
---
= 關係：最近 1 個月的轉移狀態視圖
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
關係：過去 1 個月的傳輸狀態視圖可讓您分析非同步關係中的磁碟區和儲存虛擬機器在一段時間內的傳輸趨勢。此頁面還顯示傳輸是否成功或失敗。

頁面頂部的控制項可讓您執行搜尋以定位特定物件、建立和應用篩選器以縮小顯示的資料清單、新增/刪除/重新排序頁面上的列以及將頁面上的資料匯出到 `.csv`， `.pdf` ， 或者 `.xlsx`文件。自訂頁面後，您可以將結果儲存為自訂視圖，然後安排定期產生並透過電子郵件發送此資料的報告。您可以使用*篩選器*選項僅查看選定的儲存系統，例如僅磁碟區或僅儲存虛擬機器。相同的報告顯示在儲存頁面中，並且僅針對選定的儲存實體。例如，如果您想查看磁碟區關係，您可以從 *儲存* > *儲存虛擬機器* > *關係：過去 1 個月的傳輸狀態* 選單或 *保護* > *關係* > *關係：過去 1 個月的傳輸狀態* 選單存取儲存虛擬機器的關係：過去 1 個月的狀態報告，然後使用 *篩選器* 僅查看磁碟區的資料。

* *來源磁碟區*
+
顯示來源磁碟區名稱。

* *目標音量*
+
顯示目標磁碟區名稱。

* *操作類型*
+
顯示體積傳輸的類型。

* *操作結果*
+
顯示卷傳輸是否成功。

* *轉機開始時間*
+
顯示卷傳輸開始時間。

* *轉移結束時間*
+
顯示卷傳輸結束時間。

* *轉移時長*
+
顯示完成捲傳輸所需的時間（以小時為單位）。

* *傳輸大小*
+
顯示已傳輸磁碟區的大小（以 MB 為單位）。

* *來源 SVM*
+
顯示儲存虛擬機器 (SVM) 名稱。

* *來源集群*
+
顯示來源集群名稱。

* *目標 SVM*
+
顯示目標 SVM 名稱。

* *目標集群*
+
顯示目標群集名稱。



*相關資訊*

* 有關“關係：所有關係”視圖的信息，請參閱link:../data-protection/reference_relationship_all_relationships_view.html["關係：所有關係視圖"]。
* 有關 *關係： MetroCluster* 視圖的信息，請參閱link:../storage-mgmt/task_monitor_metrocluster_configurations.html["監控MetroCluster配置"]。
* 有關“關係：所有關係”視圖的信息，請參閱link:../data-protection/reference_relationship_last_1_month_transfer_rate_view.html["關係：過去 1 個月的轉移率視圖"]。

