---
permalink: data-protection/reference_relationship_last_1_month_transfer_rate_view.html 
sidebar: sidebar 
keywords: relationship, 1 month, transfer rate, view 
summary: 關係：過去 1 個月的傳輸率視圖使您能夠分析非同步關係中每天傳輸的資料量。此頁面還提供有關每日傳輸的詳細資訊以及完成磁碟區和儲存虛擬機器的傳輸操作所需的時間。 
---
= 關係：過去 1 個月的轉移率視圖
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
關係：過去 1 個月的傳輸率視圖使您能夠分析非同步關係中每天傳輸的資料量。此頁面還提供有關每日傳輸的詳細資訊以及完成磁碟區和儲存虛擬機器的傳輸操作所需的時間。

頁面頂部的控制項可讓您執行搜尋以定位特定物件、建立和套用篩選器以縮小顯示資料的清單、新增/刪除/重新排序頁面上的列，以及將頁面上的資料匯出至 .csv、.pdf 或 .xlsx 檔案。自訂頁面後，您可以將結果儲存為自訂視圖，然後安排定期產生並透過電子郵件發送此資料的報告。例如，如果您想查看卷宗關係，您可以訪問 *存儲* > *卷* > *關係：過去 1 個月的傳輸率* 菜單或訪問 *保護* > *關係* > *關係：過去 1 個月的傳輸率* 菜單，然後使用 *過濾器* 僅查看卷的數據。

* *總傳輸大小*
+
顯示磁碟區傳輸的總大小（以千兆位元組為單位）。

* *天*
+
顯示啟動磁碟區轉移的日期。

* *結束時間*
+
顯示卷傳輸結束時間和日期。



*相關資訊*

* 有關 *關係： MetroCluster* 視圖的信息，請參閱link:../storage-mgmt/task_monitor_metrocluster_configurations.html["監控MetroCluster配置"]。
* 有關*關係：過去 1 個月轉移狀態*視圖的信息，請參閱link:../data-protection/reference_relationship_last_1_month_transfer_status_view.html["關係：最近 1 個月的轉移狀態視圖"]。
* 有關“關係：所有關係”視圖的信息，請參閱link:../data-protection/reference_relationship_last_1_month_transfer_rate_view.html["關係：過去 1 個月的轉移率視圖"]

