---
permalink: data-protection/reference_advanced_secondary_setting_dialog_box.html 
sidebar: sidebar 
keywords: advanced, secondary, settings, dialog box 
summary: 您可以使用「進階輔助設定」對話方塊在輔助磁碟區上啟用版本彈性複製、多副本備份和空間相關設定。當您想要變更、啟用或停用目前設定時，可以使用「進階輔助設定」對話方塊。 
---
= 進階輔助設定對話框
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以使用「進階輔助設定」對話方塊在輔助磁碟區上啟用版本彈性複製、多副本備份和空間相關設定。當您想要變更、啟用或停用目前設定時，可以使用「進階輔助設定」對話方塊。

與空間相關的設定可最大限度地增加儲存的資料量，包括：重複資料刪除、資料壓縮、自動增長和空間保證。

此對話方塊包括以下欄位：

* *啟用版本靈活複製*
+
啟用具有版本靈活複製功能的SnapMirror 。即使目標磁碟區運行的ONTAP版本低於來源磁碟區的版本，版本靈活的複製也能為來源磁碟區提供SnapMirror保護。

+
** 啟用備份
+
如果啟用了版本靈活複製，也可以將SnapMirror來源資料的多個 Snapshot 副本傳輸到SnapMirror目標並保留在該目標。



* *啟用重複資料刪除*
+
在SnapVault關係中的二級磁碟區上啟用重複資料刪除，以便消除重複的資料區塊，從而節省空間。當空間節省至少 10% 且資料覆蓋率不是很快時，您可以使用重複資料刪除。重複資料刪除通常用於虛擬化環境、檔案共用和備份資料。預設情況下，此設定為停用。啟用後，每次傳輸後都會啟動此操作。

+
** 啟用壓縮
+
啟用透明資料壓縮。當空間節省至少 10%、潛在開銷可以接受、並且在非高峰時段有足夠的系統資源來完成壓縮時，您可以使用壓縮。在SnapVault關係中，此設定預設為停用狀態。僅當選擇重複資料刪除時才可以使用壓縮。

** 在線壓縮
+
透過在將資料寫入磁碟之前壓縮資料來立即節省空間。當您的系統在高峰時段的使用率不超過 50% 時，以及當系統在高峰時段可以容納新的寫入和額外的 CPU 時，您可以使用內聯壓縮。僅當選擇“啟用壓縮”時，此設定才可用。



* *啟用自動增長*
+
當可用空間百分比低於指定閾值時，只要關聯聚合上有可用空間，您就可以自動增加目標磁碟區。

* *最大尺寸*
+
設定卷可以增長的最大百分比。預設值比來源磁碟區大小大 20%。如果目前大小大於或等於最大自動增長百分比，則磁碟區不會自動增長。僅當啟用自動增長設定時，此欄位才可用。

* *增加尺寸*
+
指定在達到來源磁碟區的最大百分比之前磁碟區自動成長的百分比增量。

* *艙位保證*
+
確保在輔助磁碟區上分配足夠的空間，以便資料傳輸始終成功。空間保證設定可以是以下其中之一：

+
** 文件
** 體積
** 無 + 例如，您可能有一個 200 GB 的捲，其中包含總計 50 GB 的檔案；但是，這些檔案僅包含 10 GB 的資料。無論來源磁碟區上的內容如何，磁碟區保證都會為目標磁碟區分配 200 GB。文件保證分配 50 GB 以確保為來源上的檔案保留足夠的空間；在這種情況下選擇「無」意味著在目標上僅為來源上的檔案資料實際使用的空間分配 10 GB。


+
空間保證預設為磁碟區。





== 命令按鈕

命令按鈕使您能夠執行以下任務：

* *申請*
+
儲存選定的效率設置，並在按一下「配置保護」對話方塊中的「*套用*」時套用這些設定。

* *取消*
+
放棄您的選擇並關閉“高級目標設定”對話框。


