---
permalink: data-protection/reference_initialize_update_relationship_dialog_box.html 
sidebar: sidebar 
keywords: initialize, update, dialog box 
summary: 初始化/更新對話方塊可讓您對新的保護關係執行首次基準傳輸，或在關係已經初始化且您想要執行手動、非計劃、增量更新的情況下更新關係。 
---
= 初始化/更新對話框
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
初始化/更新對話方塊可讓您對新的保護關係執行首次基準傳輸，或在關係已經初始化且您想要執行手動、非計劃、增量更新的情況下更新關係。



== 傳輸選項選項卡

透過「傳輸選項」選項卡，您可以變更傳輸的初始化優先順序並變更傳輸期間使用的頻寬。

* *轉移優先權*
+
傳輸運行的優先權。您可以選擇正常或低。指定正常傳輸優先權的策略關係在指定低傳輸優先權的策略關係之前執行。預設選擇“正常”。

* *最大傳輸速率*
+
指定透過網路在集群之間傳輸資料的最大速率。如果您選擇不使用最大轉移率，則關係之間的基準轉移是無限制的。如果選擇具有不同最大傳輸速率的多個關係，則可以指定下列最大傳輸速率設定之一：

+
** 使用在個人關係設定期間指定的值或編輯
+
選擇後，初始化和更新操作將使用每個關係建立或編輯時指定的最大傳輸速率。僅當初始化或更新具有不同傳輸速率的多個關係時，此欄位才可用。

** 無限
+
表示關係之間的傳輸沒有頻寬限制。僅當初始化或更新具有不同傳輸速率的多個關係時，此欄位才可用。

** 將頻寬限制為
+
選取後，網路頻寬將限制為您指定的值。您可以輸入一個數值，然後選擇每秒千位元組 (KBps)、每秒兆位元組 (MBps)、每秒千兆位元組 (GBps) 或每秒太字節 (TBps)。您指定的最大傳輸速率必須大於 1 KBps 且小於 4 TBps。







== 來源 Snapshot 副本選項卡

「來源 Snapshot 副本」標籤顯示用於基準傳輸的來源 Snapshot 副本的下列資訊：

* *來源磁碟區*
+
顯示對應來源磁碟區的名稱。

* *目標音量*
+
顯示選定目標磁碟區的名稱。

* *來源類型*
+
顯示卷類型。類型可以是讀/寫或資料保護。

* *快照副本*
+
顯示用於資料傳輸的 Snapshot 副本。按一下 Snapshot 副本值將顯示「選擇來源 Snapshot 副本」對話框，您可以在其中根據您擁有的保護關係類型和正在執行的操作選擇要傳輸的特定 Snapshot 副本。對於資料保護類型來源，指定不同 Snapshot 副本的選項不可用。





== 命令按鈕

命令按鈕使您能夠執行以下任務：

* *取消*
+
放棄您的選擇並關閉初始化/更新對話框。

* *提交*
+
儲存您的選擇並開始初始化或更新作業。


