---
permalink: data-protection/reference_protection_storage_virtual_machine_associations_page.html 
sidebar: sidebar 
keywords: svm, association, page 
summary: 儲存虛擬機器關聯頁面可讓您查看來源儲存虛擬機器和目標儲存虛擬機器之間現有的儲存虛擬機器關聯。 
---
= 了解儲存虛擬機器關聯
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
儲存虛擬機器（儲存 VM）關聯是從來源儲存 VM 到目標儲存 VM 的映射，合作夥伴應用程式使用它來進行資源選擇和輔助磁碟區配置。

無論目標儲存虛擬機器是二級目標還是三級目標，都會在來源儲存虛擬機器和目標儲存虛擬機器之間建立關聯。您不能使用二級目標儲存虛擬機器作為來源來建立與三級目標儲存虛擬機器的關聯。

身為應用程式管理員或儲存管理員，您可以在*保護* > *儲存虛擬機器關聯*頁面上查看您環境中的儲存虛擬機器關聯。

您可以透過三種方式關聯 SVM：

* *關聯任何儲存虛擬機器*：您可以在任何主來源儲存虛擬機器和一個或多個目標 SVM 之間建立關聯。這意味著目前需要保護的所有現有 SVM 以及將來建立的任何 SVM 都與指定的目標 SVM 相關聯。例如，您可能希望將來自不同位置的多個不同來源的應用程式備份到一個位置的一個或多個目標 SVM。
* *關聯特定儲存虛擬機器*：您可以在特定來源儲存虛擬機器和一個或多個特定目標 SVM 之間建立關聯。例如，如果您為許多用戶端提供儲存服務，而這些用戶端的資料必須彼此分開，則可以選擇此選項將特定的來源儲存虛擬機器與僅指派給該用戶端的特定目標儲存虛擬機器關聯。
* *與外部儲存虛擬機器關聯*：您可以在來源儲存虛擬機器和目標儲存虛擬機器的外部靈活磁碟區之間建立關聯。




== 建立儲存虛擬機器關聯

建立儲存虛擬機器關聯精靈可讓合作夥伴保護應用程式能夠將來源儲存虛擬機器與目標儲存虛擬機器關聯，以便與SnapMirror和SnapVault關係一起使用。合作夥伴應用程式在初始配置目標磁碟區時使用這些關聯來決定選擇哪些資源。 dd

.開始之前
* 您要關聯的儲存虛擬機器必須已經存在。
* 您必須具有應用程式管理員或儲存管理員角色。


對於任何來源儲存虛擬機器和關係類型，您只能在每個目標叢集上選擇一個目標儲存虛擬機器。

使用刪除和建立功能變更關聯只會影響未來的配置操作。它不會移動現有的目標磁碟區。

.步驟
. 在左側導覽窗格中，按一下「*保護*」>「*儲存虛擬機器關聯*」。
. 在「儲存虛擬機器關聯」頁面上，按一下「建立」。
+
*建立儲存虛擬機器關聯*精靈已啟動。

. 選擇以下來源之一：
+
** *任何*
+
當您想要在任何主儲存 VM 來源和一個或多個目標儲存 VM 之間建立關聯時，請選擇此選項。這意味著目前需要保護的所有現有儲存虛擬機器以及將來建立的任何儲存虛擬機器都與指定的目標儲存虛擬機器相關聯。例如，您可能希望將來自不同位置的多個不同來源的應用程式備份到一個位置的一個或多個目標儲存虛擬機器。

** *單身的*
+
當您想要選擇與一個或多個目標儲存虛擬機器關聯的特定來源儲存虛擬機器時，請選擇此選項。例如，如果您要為許多用戶端提供儲存服務，而這些用戶端的資料必須彼此分開，請選擇此選項將特定的儲存 VM 來源與僅指派給該用戶端的特定儲存 VM 目標相關聯。

** *無（外部）*
+
當您想要在來源儲存虛擬機器和目標儲存虛擬機器的外部彈性磁碟區之間建立關聯時，請選擇此選項。



. 選擇要建立的一種或兩種保護關係類型：
+
** * SnapMirror*
** * SnapVault*


. 按一下“下一步”。
. 選擇一個或多個儲存虛擬機器保護目標。
. 按一下“完成”。




== 刪除儲存虛擬機器關聯

您可以刪除合作夥伴應用程式的儲存虛擬機器關聯，以刪除來源和目標儲存虛擬機器之間的輔助配置關係；例如，當目標儲存虛擬機器已滿並且您想要建立新的儲存虛擬機器保護關聯時，您可能會執行此操作。

.開始之前
您必須具有應用程式管理員或儲存管理員角色。

在選擇至少一個儲存虛擬機器關聯之前，「*刪除*」按鈕將被停用。使用刪除和建立功能變更關聯只會影響未來的配置操作；它不會移動現有的目標磁碟區。

.步驟
. 在左側導覽窗格中，按一下「*保護*」>「*儲存虛擬機器關聯*」。
. 選擇至少一個儲存虛擬機器關聯。
+
*刪除*按鈕已啟用。

. 按一下“刪除”。
+
將顯示一個警告對話框。

. 點選“是”繼續。
+
選定的儲存虛擬機器關聯將從清單中刪除。


