---
permalink: data-protection/task_update_protection_voldtls_page.html 
sidebar: sidebar 
keywords: initialize, update, protection, relationships, volume, health details page 
summary: 您可以對新的保護關係執行首次基線傳輸，或者如果關係已初始化並且您想要執行手動、非計劃增量更新以立即傳輸數據，則更新關係。 
---
= 從卷/健康詳情頁面初始化或更新保護關係
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以對新的保護關係執行首次基線傳輸，或者如果關係已初始化並且您想要執行手動、非計劃增量更新以立即傳輸數據，則更新關係。

*注意*：您無法初始化或更新受一致性群組保護的磁碟區。

.開始之前
* 您必須具有應用程式管理員或儲存管理員角色。
* 您必須已設定OnCommand Workflow Automation。


.步驟
. 從「*Volume / Health*」詳細資料頁面的「*Protection*」標籤中，在拓撲中找到要初始化或更新的保護關係，然後右鍵單擊它。
. 從選單中選擇*初始化/更新*。
+
或者，從*操作*選單中，選擇*關係*>*初始化/更新*來初始化或更新您目前正在查看詳細資訊的關係。

+
將顯示“初始化/更新”對話框。

. 在「傳輸選項」標籤中，選擇傳輸優先權和最大傳輸速率。
. 按一下「來源快照副本」；然後在「快照副本」欄位中按一下「預設」。
+
系統彈出「選擇來源Snapshot副本」對話框。

. 如果您想要指定現有的 Snapshot 副本而不是傳輸預設的 Snapshot 副本，請按一下「*現有 Snapshot 副本*」並從清單中選擇一個 Snapshot 副本。
. 點選“*提交*”。
+
您將返回初始化/更新對話框。

. 如果您選擇了多個來源進行初始化或更新，請按一下「*預設*」以選擇下一個要為其指定現有 Snapshot 副本的讀取/寫入來源。
+
您不能為資料保護磁碟區選擇不同的 Snapshot 副本。

. 按一下「*提交*」開始初始化或更新作業。
+
初始化或更新作業已啟動，您將返回捲/健康詳細資料頁面，並且頁面頂部會顯示作業連結。

. *可選：*按一下「磁碟區/健康」詳細資料頁面上的「檢視作業」以追蹤每個初始化或更新作業的狀態。
+
顯示經過篩選的作業清單。

. *可選：*按一下每個作業以查看其詳細資訊。
. *可選：*按一下瀏覽器上的「後退」箭頭返回「*Volume / Health*」詳細資料頁面。
+
當所有作業任務成功完成後，初始化或更新操作就完成了。


