---
permalink: data-protection/task_create_snapmirror_relationship_from_health_volume.html 
sidebar: sidebar 
keywords: create, snapmirror, protection, relationship,  volume, health details page 
summary: 您可以使用磁碟區/運行狀況詳細資料頁面建立SnapMirror關係，以便啟用資料複製來保護目的。  SnapMirror複製可讓您在來源磁碟區上發生資料遺失時從目標磁碟區復原資料。 
---
= 從磁碟區/運行狀況詳細資料頁面建立SnapMirror保護關係
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以使用磁碟區/運行狀況詳細資料頁面建立SnapMirror關係，以便啟用資料複製來保護目的。  SnapMirror複製可讓您在來源磁碟區上發生資料遺失時從目標磁碟區復原資料。

.開始之前
* 您必須具有應用程式管理員或儲存管理員角色。
* 您必須已經設定了工作流程自動化。


在下列情況下不會顯示「保護」選單：

* 如果 RBAC 設定不允許此操作：例如，如果您只有操作員權限
* 當磁碟區 ID 未知時：例如，當您具有群集間關係且尚未發現目標群集時


您可以同時執行最多 10 項保護作業，而不會對效能產生任何影響。當您同時執行 11 到 30 個作業時，可能會遇到一些效能影響。不建議同時執行超過 30 個作業。

.步驟
. 在「磁碟區/健康」詳細資料頁面的「保護」標籤中，在拓樸視圖中以滑鼠右鍵按一下要保護的磁碟區的名稱。
. 從選單中選擇*保護* > * SnapMirror*。
+
彈出“配置保護”對話框。

. 點擊 * SnapMirror* 以查看 * SnapMirror* 標籤並配置目標資訊。
. 按一下「*進階*」根據需要設定空間保證，然後按一下「*套用*」。
. 完成「配置保護」對話方塊中的「目標資訊」區域和「關係設定」區域。
. 按一下“*應用*”。
+
您將返回「音量/健康」詳細資訊頁面。

. 按一下「*Volume / Health*」詳細資料頁面頂部的保護配置作業連結。
+
作業的任務和詳細資料顯示在作業詳細資料頁面中。

. 在「*作業*」詳細資料頁面中，按一下「*重新整理*」以更新與保護設定作業相關的任務列表和任務詳細信息，並確定作業何時完成。
. 當作業任務完成後，按一下瀏覽器上的*返回*即可返回*Volume / Health*詳細資料頁面。
+
新的關係顯示在磁碟區/健康詳細資料頁面拓撲視圖中。



根據您在配置期間指定的目標 SVM 或在進階設定中啟用的選項，產生的SnapMirror關係可能是以下幾種可能的變更之一：

* 如果您指定的目標 SVM 在與來源磁碟區相同或更新版本的ONTAP下執行，則基於區塊複製的SnapMirror關係是預設結果。
* 如果您指定的目標 SVM 在與來源磁碟區相同或更新版本的ONTAP下運行，但在進階設定中啟用了版本彈性複製，則會產生具有版本靈活複製的SnapMirror關係。
* 如果您指定的目標 SVM 在ONTAP的早期版本或高於來源磁碟區的版本下運行，且早期版本支援版本靈活複製，則會自動產生具有版本靈活複製的SnapMirror關係。

