---
permalink: data-protection/task_create_snapmirror_relationship_from_health_volumes.html 
sidebar: sidebar 
keywords: create, snapmirror, protection, relationship, health, volumes view 
summary: 使用「運行狀況：所有磁碟區」視圖，您可以透過在同一儲存虛擬機器上選擇多個磁碟區來一次建立多個SnapMirror保護關係。 
---
= 從「Health: All Volumes」檢視建立SnapMirror保護關係
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
使用「運行狀況：所有磁碟區」視圖，您可以透過在同一儲存虛擬機器上選擇多個磁碟區來一次建立多個SnapMirror保護關係。

.開始之前
* 您必須具有應用程式管理員或儲存管理員角色。
* 您必須已經設定了工作流程自動化。


在下列情況下不會顯示「保護」選單：

* 如果 RBAC 設定不允許此操作：例如，如果您只有操作員權限
* 當磁碟區 ID 未知時：例如，當您具有群集間關係且尚未發現目標群集時


.步驟
. 在*Health:All Volumes*檢視中，選擇要保護的磁碟區。
+
或者，若要在同一個 SVM 上建立多個保護關係，請在「執行狀況：所有磁碟區」檢視中選取一個或多個捲，然後按一下工具列上的「保護」>「SnapMirror」。

+
彈出“配置保護”對話框。

. 點擊 * SnapMirror* 以查看 * SnapMirror* 標籤並配置目標資訊。
. 按一下「*進階*」根據需要設定空間保證，然後按一下「*套用*」。
. 完成「SnapMirror」標籤中的「目標資訊」區域和「關係設定」區域。
. 按一下“*應用*”。
+
您將返回「健康狀況：所有磁碟區」視圖。

. 按一下「健康：所有磁碟區視圖」頂部的保護配置作業連結。
+
如果您只建立一個保護關係，則會顯示「作業詳細資料」頁面；但是，如果您建立多個保護關係，則會顯示與保護操作相關的所有作業的清單。

. 執行下列操作之一：
+
** 如果您只有一項作業，請按一下「重新整理」以更新與保護設定作業相關的任務清單和任務詳細信息，並確定作業何時完成。
** 如果您有多份工作：
+
... 按一下作業清單中的一項作業。
... 點擊“*刷新*”以更新與保護配置作業相關的任務列表和任務詳細信息，並確定作業何時完成。
... 使用“*返回*”按鈕返回過濾清單並查看另一項工作。






根據您在配置期間指定的目標 SVM 或在進階設定中啟用的選項，產生的SnapMirror關係可能是以下幾種可能的變更之一：

* 如果您指定的目標 SVM 在與來源磁碟區相同或更新版本的ONTAP下執行，則基於區塊複製的SnapMirror關係是預設結果。
* 如果您指定的目標 SVM 在與來源磁碟區相同或更新版本的ONTAP下運行，但在進階設定中啟用了版本彈性複製，則會產生具有版本靈活複製的SnapMirror關係。
* 如果您指定的目標 SVM 在比來源磁碟區更早的ONTAP版本下運行，並且早期版本支援版本靈活複製，則會自動產生具有版本靈活複製的SnapMirror關係。

