---
permalink: data-protection/task_initialize_or_update_protection_relationships.html 
sidebar: sidebar 
keywords: initialize, update, protection, relationships, volume, page 
summary: 在「卷宗關係」頁面中，您可以對新的保護關係執行首次基線傳輸，或者如果關係已經初始化並且您想要執行手動、非計劃增量更新以立即傳輸，則可以更新關係。 
---
= 從磁碟區關係頁面初始化或更新保護關係
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
在「卷宗關係」頁面中，您可以對新的保護關係執行首次基線傳輸，或者如果關係已經初始化並且您想要執行手動、非計劃增量更新以立即傳輸，則可以更新關係。


NOTE: 您無法初始化或更新受一致性群組保護的磁碟區。

.開始之前
* 您必須具有應用程式管理員或儲存管理員角色。
* 您必須已設定OnCommand Workflow Automation。


.步驟
. 在「*卷關係*」頁面上，右鍵單擊一個卷並選擇一個或多個具有要更新或初始化的關係的捲，然後在工具列上按一下「*初始化/更新*」。
+
將顯示“*初始化/更新*”對話框。

. 在「傳輸選項」標籤中，選擇傳輸優先權和最大傳輸速率。
. 按一下「來源快照副本」；然後在「快照副本」欄位中按一下「預設」。
+
系統彈出「選擇來源Snapshot副本」對話框。

. 如果您想要指定現有的 Snapshot 副本而不是傳輸預設的 Snapshot 副本，請按一下「*現有 Snapshot 副本*」並從清單中選擇一個 Snapshot 副本。
. 點選“*提交*”。
+
您將返回*初始化/更新*對話框。

. 如果您選擇了多個來源進行初始化或更新，請按一下「*預設*」以選擇要為其指定現有 Snapshot 副本的下一個來源。
. 按一下「*提交*」開始初始化或更新作業。
+
初始化或更新作業已啟動，您將返回捲關係頁面，並且頁面頂部會顯示作業連結。

. *可選：*按一下*Health: All Volumes*視圖上的*View Jobs*來追蹤每個初始化或更新作業的狀態。
+
顯示經過篩選的作業清單。

. *可選：*按一下每個作業以查看其詳細資訊。
. *選用：*按一下瀏覽器上的*後退*箭頭返回*磁碟區關係*頁面。
+
當所有任務成功完成後，初始化或更新操作就完成了。


